<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free Hash Generator Online','description'=>'Generate SHA-256, SHA-512 and SHA-1 hashes from text instantly in your browser with SmartToolz.','url'=>'https://smarttoolz.in/tools/hash-generator/'];
smarttoolz_tool_page_start($tool);
?>
<main class="hash-page"><section class="tool-head"><span class="eyebrow">HASH GENERATOR</span><h1>Hash Generator</h1><p>Generate cryptographic hashes from text instantly. Your input stays in your browser.</p></section><section class="hash-card"><label>Text to hash<textarea id="input" placeholder="Enter or paste text here..." spellcheck="false"></textarea></label><div class="controls"><label>Algorithm<select id="algo"><option value="SHA-256">SHA-256</option><option value="SHA-512">SHA-512</option><option value="SHA-1">SHA-1</option></select></label><button id="generate" class="primary">Generate Hash</button></div><div class="result"><span>Hash result</span><div id="output">Your hash will appear here.</div><button id="copy">Copy Hash</button></div></section><section class="info-grid"><article><h2>Supported algorithms</h2><p>SHA-256, SHA-512 and SHA-1 are available for quick browser-based hashing.</p></article><article><h2>Private processing</h2><p>The text is processed locally in your browser and is not sent to SmartToolz.</p></article></section></main>
<style>.hash-page{width:min(900px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.hash-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.hash-card label{display:grid;gap:7px;color:#344054;font-size:11px;font-weight:800}.hash-card textarea{box-sizing:border-box;width:100%;min-height:210px;padding:14px;border:1px solid #dfe3eb;border-radius:12px;background:#fcfdff;color:#172033;font:13px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;resize:vertical;outline:0}.hash-card textarea:focus,.hash-card select:focus{border-color:#8d80ff}.controls{display:flex;gap:12px;align-items:end;margin-top:14px}.controls label{flex:1}.hash-card select{box-sizing:border-box;width:100%;height:45px;padding:0 11px;border:1px solid #dfe3eb;border-radius:10px;background:#fff;color:#172033}.primary{height:45px;padding:0 20px;border:0;border-radius:10px;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff;font-size:10px;font-weight:900;cursor:pointer}.result{margin-top:16px;padding:17px;border:1px solid #e7eaf0;border-radius:14px;background:#fafbff}.result>span{font-size:10px;color:#69738e;font-weight:800}.result>div{margin:10px 0 14px;padding:12px;border:1px solid #e7eaf0;border-radius:9px;background:#fff;color:#263052;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}.result button{padding:9px 13px;border:1px solid #111936;border-radius:9px;background:#111936;color:#fff;font-size:9px;font-weight:900;cursor:pointer}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:650px){.hash-page{width:calc(100% - 20px)}.hash-card{padding:16px}.controls{flex-direction:column;align-items:stretch}.primary{width:100%}.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{const input=document.getElementById('input'),algo=document.getElementById('algo'),output=document.getElementById('output');const bufHex=b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');document.getElementById('generate').onclick=async()=>{if(!input.value){output.textContent='Please enter some text.';return}const data=new TextEncoder().encode(input.value);const hash=await crypto.subtle.digest(algo.value,data);output.textContent=bufHex(hash)};document.getElementById('copy').onclick=async()=>{if(!output.textContent||output.textContent.includes('Your hash'))return;await navigator.clipboard.writeText(output.textContent);document.getElementById('copy').textContent='Copied';setTimeout(()=>document.getElementById('copy').textContent='Copy Hash',900)}})();</script>
<?php smarttoolz_tool_page_end(); ?>
