<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';
$admin=lh_require_admin();
$done=0;
if($_SERVER['REQUEST_METHOD']==='POST'){
  $hasCh=(bool)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='learning_lessons' AND column_name='chapter_id'")->fetchColumn();
  $sql=$hasCh?"SELECT l.id,l.title,l.content,c.title course_title FROM learning_lessons l JOIN learning_chapters ch ON ch.id=l.chapter_id JOIN learning_courses c ON c.id=ch.course_id WHERE l.enabled=1":"SELECT l.id,l.title,l.content,c.title course_title FROM learning_lessons l JOIN learning_courses c ON c.id=l.course_id WHERE l.enabled=1";
  $rows=$db->query($sql)->fetchAll(PDO::FETCH_ASSOC);
  $u=$db->prepare('UPDATE learning_lessons SET content=? WHERE id=?');
  foreach($rows as $r){
    $title=htmlspecialchars((string)$r['title'],ENT_QUOTES,'UTF-8');$course=htmlspecialchars((string)$r['course_title'],ENT_QUOTES,'UTF-8');
    $html='<article class="lh-prose"><p><strong>'.$title.'</strong> is an original SmartToolz lesson in <strong>'.$course.'</strong>.</p><h2>Overview</h2><p>This lesson introduces the topic, explains why it matters, and gives you a practical way to apply the skill.</p><h2>Learning objectives</h2><ul><li>Understand the main idea and key terms.</li><li>Follow a clear workflow from setup to result.</li><li>Recognize common mistakes.</li><li>Apply the concept in a small task.</li></ul><h2>Core concept</h2><p>Break the topic into smaller parts. Understand what each part does, then connect the parts into one repeatable workflow. Focus on the reason behind each step instead of memorizing a sequence.</p><h2>Step-by-step</h2><ol><li>Identify your goal and required inputs.</li><li>Prepare the required tools, files, or data.</li><li>Complete one step at a time and verify the result.</li><li>Review the final output and correct any issues.</li></ol><h2>Practical example</h2><p>Start with a small example based on this topic. Change one input at a time so you can see exactly what effect the change has.</p><div class="alert alert-primary"><strong>SmartTip:</strong> Keep your first attempt simple. Once it works, improve it gradually.</div><h2>Practice task</h2><p>Create your own small example related to this lesson. Complete it without copying a solution and explain the result in your own words.</p><h2>Common mistakes</h2><ul><li>Skipping prerequisites.</li><li>Changing several things while troubleshooting.</li><li>Ignoring warnings or errors.</li><li>Moving on without testing.</li></ul><h2>Quality checklist</h2><ul><li>I can explain the concept.</li><li>I can demonstrate the basic workflow.</li><li>I can spot a common mistake.</li><li>I can complete the practice task.</li></ul><h2>Quick check</h2><p>Write two sentences explaining the lesson and one situation where you could use the skill.</p><h2>Continue learning</h2><p>Finish the practice task, review your notes, and continue to the next lesson.</p></article>';
    $u->execute([$html,(int)$r['id']]);$done++;
  }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enrich Lessons | SmartToolz</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/learning-hub/assets/css/app.css" rel="stylesheet"></head><body><main class="container py-5"><div class="lh-card p-4 p-md-5"><span class="badge text-bg-primary mb-2">Learning Hub Admin</span><h1 class="h3 fw-bold">Add lesson content</h1><p class="text-secondary">Fill published lessons with structured original educational content. Safe to run again.</p><?php if($done):?><div class="alert alert-success"><?=number_format($done)?> lessons updated.</div><?php endif;?><form method="post"><button class="btn btn-primary">Build lesson content</button><a class="btn btn-outline-secondary ms-2" href="/learning-hub/courses.php">Open Courses</a></form></div></main></body></html>