<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';
$admin=lh_require_admin();
$done=0;

$topics=[
 'computer'=>[
 'Computer parts and their jobs','Input and output devices','CPU and how it works','RAM versus storage','Hard drives and SSDs','Files and folders','File extensions','Creating a folder structure','Copy, move and delete files','Windows desktop basics','Taskbar and Start menu','Keyboard shortcuts','Mouse actions','Installing an application','Uninstalling software','Updating applications','Device drivers','Printers and scanners','USB devices','Bluetooth basics','Wi-Fi basics','Web browsers','Safe web searching','Email basics','Downloading files safely','Cloud storage basics','Passwords and account security','Software updates','Backup basics','External storage','Computer maintenance','Disk space management','Task Manager basics','Troubleshooting slow computers','Startup applications','Safe application permissions','Windows settings','Display and accessibility settings','Date, time and language settings','Screen capture methods','PDF files and readers','ZIP files and extraction','Basic document organization','Sharing files safely','Malware awareness','Phishing awareness','Public computer safety','Data privacy basics','Creating a personal backup plan','Computer skills mini project'
 ],
 'office'=>[
 'Word document basics','Text formatting','Paragraph formatting','Styles and headings','Page setup','Headers and footers','Tables in Word','Images in documents','Links and bookmarks','Find and replace','Track changes','Word document review','Excel workbook basics','Rows columns and cells','Cell formatting','Basic formulas','Relative references','Absolute references','SUM AVERAGE and COUNT','IF formulas','Sorting data','Filtering data','Excel tables','Conditional formatting','Simple charts','Data validation','Cleaning spreadsheet data','Print settings in Excel','PowerPoint slide basics','Themes and layouts','Working with images','Shapes and icons','Speaker notes','Transitions and animations','Presentation design basics','PowerPoint charts','Creating a business report','Creating an invoice sheet','Creating a budget sheet','Creating a marksheet','Creating an attendance sheet','Organizing office files','Exporting to PDF','Keyboard shortcuts for office work','Common spreadsheet mistakes','Document quality checklist','Office productivity workflow','Mini Word project','Mini Excel project','Mini PowerPoint project'
 ],
 'web'=>[
 'What happens when you open a web page','HTML document structure','Headings paragraphs and text','Links and navigation','Images and alt text','Lists','Tables','Forms','Semantic HTML','HTML attributes','CSS selectors','CSS colors and backgrounds','Typography in CSS','Box model','Margins and padding','Borders and shadows','Display and positioning','Flexbox basics','Flexbox alignment','CSS Grid basics','Responsive layouts','Media queries','Mobile-first design','Buttons and UI states','Navigation bars','Cards and content sections','Forms with CSS','CSS variables','Reusable styles','Web accessibility basics','Browser developer tools','JavaScript in the browser','Variables and values','Conditions','Loops','Functions','Arrays','Objects','DOM selection','DOM events','Form interaction','Client-side validation','Fetch and APIs','JSON basics','Error handling','Local storage','Debugging JavaScript','Simple interactive component','Responsive landing page project','Portfolio page project','Web development mini project'
 ],
 'programming'=>[
 'Programming concepts','Algorithms and step-by-step thinking','Variables','Data types','Operators','Conditions','Loops','Functions','Parameters and return values','Arrays','Associative arrays','Strings','Date and time','Input validation','Error handling','Debugging techniques','Reusable code','File handling','Working with JSON','HTTP basics','APIs and requests','Authentication concepts','Database fundamentals','SQL tables','SELECT queries','WHERE conditions','ORDER BY and LIMIT','INSERT queries','UPDATE queries','DELETE queries','Joins','Indexes','Prepared statements','CRUD applications','Sessions and cookies','Security basics','Password handling','Form processing','Server-side validation','Git basics','Commits','Branches','Merging changes','GitHub repositories','Pull requests','Environment configuration','Logging','Testing fundamentals','Project structure','Deploying a small app','Programming mini project'
 ],
 'design'=>[
 'Design fundamentals','Visual hierarchy','Contrast and balance','Color theory','Color palettes','Typography basics','Font pairing','Spacing and alignment','Grid systems','Composition','Visual consistency','Brand basics','Creating a social post','Creating a banner','Creating a thumbnail','Creating a poster','Creating a presentation cover','Image selection','Cropping and framing','Background removal concepts','Working with shapes','Icons and symbols','Simple illustrations','Canva workspace','Reusable design templates','Designing for mobile','Designing for readability','Call-to-action elements','Before and after redesign','Common design mistakes','Social media dimensions','YouTube thumbnail principles','Instagram post principles','Business flyer design','Event poster design','Simple logo concepts','Brand color usage','Exporting images','Web image optimization','Accessible design','Design feedback checklist','Building a design system','Organizing design assets','Client-ready files','Design revision workflow','Mini branding project','Mini thumbnail project','Mini poster project','Mini social campaign','Graphic design portfolio project'
 ],
 'ai'=>[
 'What generative AI is','How large language models work','Prompt basics','Clear instructions','Context in prompts','Role prompting','Few-shot examples','Structured outputs','Prompt templates','Summarization prompts','Extraction prompts','Classification prompts','Brainstorming with AI','Writing with AI','Research assistance','Study assistance','Coding assistance','Data analysis assistance','Image generation concepts','Multimodal AI','Evaluating AI answers','Hallucinations','Fact checking AI output','Prompt refinement','Comparing model responses','Privacy when using AI','Sensitive information and AI','Responsible AI use','AI workflow design','Creating reusable prompts','AI for productivity','AI for learning','AI for marketing','AI for coding','AI for customer support','AI for content planning','AI limitations','Human review loops','Quality criteria','Prompt debugging','Structured AI experiments','Building an AI checklist','Documenting AI workflows','AI project planning','AI project evaluation','Small prompt library','Practical AI mini project','AI productivity project','AI research project','Responsible AI mini project'
 ],
 'marketing'=>[
 'Digital marketing basics','Search intent','Keyword research','Long-tail keywords','Content planning','Search-friendly titles','Meta descriptions','Heading structure','Internal linking','External references','Image SEO','URL structure','Technical SEO basics','Mobile SEO','Page speed concepts','Structured data concepts','Search Console basics','Analytics basics','Content quality','Helpful content principles','Duplicate content','Thin content','Content refreshes','Local SEO basics','Business listings','Social media content','Social media calendars','Email marketing basics','Call-to-action writing','Landing pages','Conversion basics','A/B testing concepts','Marketing funnels','Audience research','Competitor research','Content briefs','Blog post structure','Product page basics','Marketing metrics','Traffic versus conversions','Lead generation','Brand consistency','Campaign planning','Reporting basics','SEO checklist','Content audit','Marketing mini project','SEO content project','Social campaign project','Digital marketing capstone'
 ],
 'career'=>[
 'Understanding freelancing','Choosing a service','Finding a niche','Building a skill profile','Portfolio basics','Project case studies','Writing a professional bio','Creating service packages','Setting project scope','Client discovery','Writing proposals','Client communication','Requirement gathering','Pricing basics','Estimating project effort','Deadlines and milestones','Task management','Revision policies','Delivering files','Professional invoices','Payment safety','Record keeping','Client feedback','Handling difficult requirements','Building repeat clients','Creating a personal brand','LinkedIn basics','Resume basics','Job profile optimization','Interview preparation','Professional email writing','Time management','Remote work habits','Productivity systems','Learning plans','Skill gap analysis','Building credibility','Collecting testimonials','Publishing useful work','Networking basics','Finding opportunities','Freelance marketplaces','Avoiding common scams','Negotiation basics','Project closure','Monthly career review','Freelance mini project','Portfolio improvement project','Career action plan','Professional growth capstone'
 ],
 'advanced'=>[
 'Operating system concepts','Linux basics','Terminal navigation','Files and permissions','Processes and services','Package management','Shell commands','Environment variables','Networking fundamentals','IP addresses','DNS basics','HTTP and HTTPS','Ports and protocols','Routing concepts','Firewalls','Cloud computing basics','Virtual machines','Containers','Storage concepts','Backups','Monitoring basics','Logs','Authentication','Authorization','Encryption concepts','Secure passwords','Multi-factor authentication','Phishing defense','Web security basics','SQL injection concepts','XSS concepts','CSRF concepts','Secure coding habits','Version control workflows','Branches and releases','CI and deployment concepts','APIs and integrations','JSON and webhooks','Caching basics','Performance concepts','Scaling basics','Database performance','System troubleshooting','Incident response basics','Technical documentation','Architecture diagrams','Cloud cost awareness','Security checklist','Deployment project','Monitoring project','Technology capstone'
 ]
];

function pickTopic(array $topics,int $n):string{return $topics[($n-1)%count($topics)];}
function topicBucket(string $category,string $course):array{
 $s=strtolower($category.' '.$course);
 if(str_contains($s,'computer')||str_contains($s,'windows')||str_contains($s,'basic'))return $GLOBALS['topics']['computer'];
 if(str_contains($s,'office')||str_contains($s,'excel')||str_contains($s,'word')||str_contains($s,'powerpoint'))return $GLOBALS['topics']['office'];
 if(str_contains($s,'html')||str_contains($s,'web')||str_contains($s,'css')||str_contains($s,'javascript'))return $GLOBALS['topics']['web'];
 if(str_contains($s,'php')||str_contains($s,'program')||str_contains($s,'mysql')||str_contains($s,'database')||str_contains($s,'git'))return $GLOBALS['topics']['programming'];
 if(str_contains($s,'design')||str_contains($s,'canva')||str_contains($s,'graphic'))return $GLOBALS['topics']['design'];
 if(str_contains($s,'ai')||str_contains($s,'artificial'))return $GLOBALS['topics']['ai'];
 if(str_contains($s,'seo')||str_contains($s,'marketing')||str_contains($s,'content'))return $GLOBALS['topics']['marketing'];
 if(str_contains($s,'freelanc')||str_contains($s,'career')||str_contains($s,'job'))return $GLOBALS['topics']['career'];
 return $GLOBALS['topics']['advanced'];
}

if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $sql="SELECT l.id,l.title,l.content,c.title course_title,COALESCE(lc.name,'') category_name,l.sort_order FROM learning_lessons l LEFT JOIN learning_chapters ch ON ch.id=l.chapter_id LEFT JOIN learning_courses c ON c.id=ch.course_id LEFT JOIN learning_categories lc ON lc.id=c.category_id WHERE l.enabled=1 ORDER BY l.id";
  if(!(bool)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='learning_lessons' AND column_name='chapter_id'")->fetchColumn())$sql="SELECT l.id,l.title,l.content,c.title course_title,COALESCE(lc.name,'') category_name,l.sort_order FROM learning_lessons l LEFT JOIN learning_courses c ON c.id=l.course_id LEFT JOIN learning_categories lc ON lc.id=c.category_id WHERE l.enabled=1 ORDER BY l.id";
  $rows=$db->query($sql)->fetchAll(PDO::FETCH_ASSOC);$u=$db->prepare('UPDATE learning_lessons SET content=? WHERE id=?');
  foreach($rows as $r){
   $n=max(1,(int)$r['sort_order']);$course=htmlspecialchars((string)$r['course_title'],ENT_QUOTES,'UTF-8');$topic=pickTopic(topicBucket((string)$r['category_name'],(string)$r['course_title']),$n);$et=htmlspecialchars($topic,ENT_QUOTES,'UTF-8');
   $html='<article class="lh-prose"><div class="lh-lesson-intro"><p>This lesson focuses on <strong>'.$et.'</strong> as part of <strong>'.$course.'</strong>. You will learn the idea, see how it is used, and finish with a practical task.</p></div><h2>What you will learn</h2><ul><li>What '.$et.' means and where it fits.</li><li>The main terms, parts, or steps involved.</li><li>How to use the concept in a practical situation.</li></ul><h2>Understanding '.$et.'</h2><p><strong>'.$et.'</strong> is easier to understand when you connect it to a real task. Start with the goal, identify the information or tools you need, and work through the process in small steps. In professional work, this concept is useful because it helps you produce a predictable result rather than relying on guesswork.</p><h2>Step-by-step</h2><ol><li>Define the result you want to achieve.</li><li>Prepare the required inputs, files, settings, or data.</li><li>Complete the task one stage at a time.</li><li>Check the result and compare it with the expected outcome.</li><li>Improve the workflow after you have a working first attempt.</li></ol><h2>Practical example</h2><p>Imagine a beginner is working on a small task involving <strong>'.$et.'</strong>. They first create a simple version, verify each stage, and then improve it. This approach makes it easier to see which step produced a problem and makes the final workflow easier to repeat.</p><div class="alert alert-primary"><strong>Smart tip:</strong> Keep a small record of the inputs, steps, and result. It makes troubleshooting and revision much easier.</div><h2>Practice task</h2><p>Create a small hands-on example using <strong>'.$et.'</strong>. Try it yourself, change one part of the example, and note what changed in the final result.</p><h2>Common mistakes</h2><ul><li>Starting without understanding the goal.</li><li>Changing several inputs at once.</li><li>Skipping a verification step.</li><li>Ignoring useful warnings or errors.</li></ul><h2>Quick check</h2><p>Explain <strong>'.$et.'</strong> in your own words, name one practical use, and describe one mistake you would avoid.</p><h2>Next step</h2><p>Complete the practice task before moving to the next lesson. Repeating the concept with a second small example will help turn the idea into a usable skill.</p></article>';
   $u->execute([$html,(int)$r['id']]);$done++;
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Refresh Lesson Content | SmartToolz</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/learning-hub/assets/css/app.css" rel="stylesheet"></head><body><main class="container py-5"><div class="lh-card p-4 p-md-5 mx-auto" style="max-width:900px"><span class="badge text-bg-primary mb-2">Learning Hub Admin</span><h1 class="h3 fw-bold">Build topic-specific lesson content</h1><p class="text-secondary">Each lesson receives content based on its course/category and lesson position instead of the old identical template.</p><?php if(isset($done)&&$done):?><div class="alert alert-success"><?=number_format($done)?> lessons rebuilt with topic-specific content.</div><?php endif;if(isset($error)):?><div class="alert alert-danger"><strong>Error:</strong><?=lh_h($error)?></div><?php endif;?><form method="post"><button class="btn btn-primary btn-lg">Rebuild All Lesson Content</button><a class="btn btn-outline-secondary ms-2" href="/learning-hub/courses.php">Open Courses</a></form></div></main></body></html>