<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';
$admin=lh_require_admin();
$updated=0;$error=null;
$topics=[
'computer'=>['Computer Hardware Basics','Input and Output Devices','CPU: What It Does','RAM vs Storage','Hard Drives and SSDs','Files and Folders','File Extensions','Folder Organization','Copying and Moving Files','Windows Desktop','Taskbar and Start Menu','Essential Keyboard Shortcuts','Mouse Skills','Installing Software','Removing Software','Software Updates','Device Drivers','Printers and Scanners','USB Devices','Bluetooth Connections','Wi-Fi Basics','Web Browsers','Safe Web Searching','Email Basics','Downloading Files Safely','Cloud Storage','Password Security','Operating System Updates','Backup Basics','External Storage','Computer Maintenance','Managing Disk Space','Task Manager','Troubleshooting Slow PCs','Startup Apps','Application Permissions','Windows Settings','Accessibility Settings','Date, Time and Language','Screenshots and Screen Capture','PDF Files','ZIP Files','Document Organization','Safe File Sharing','Malware Awareness','Phishing Awareness','Public Computer Safety','Data Privacy','Personal Backup Plan','Computer Skills Project'],
'office'=>['Word: Getting Started','Text Formatting','Paragraph Formatting','Styles and Headings','Page Setup','Headers and Footers','Tables in Word','Images in Documents','Links and Bookmarks','Find and Replace','Track Changes','Document Review','Excel Workbooks','Rows, Columns and Cells','Cell Formatting','Basic Formulas','Relative References','Absolute References','SUM, AVERAGE and COUNT','IF Formulas','Sorting Data','Filtering Data','Excel Tables','Conditional Formatting','Charts','Data Validation','Cleaning Spreadsheet Data','Print Settings','PowerPoint Basics','Themes and Layouts','Working with Images','Shapes and Icons','Speaker Notes','Transitions and Animations','Presentation Design','PowerPoint Charts','Business Reports','Invoice Sheets','Budget Sheets','Mark Sheets','Attendance Sheets','Office File Organization','Exporting to PDF','Office Keyboard Shortcuts','Spreadsheet Mistakes','Document Quality','Office Productivity Workflow','Word Project','Excel Project','PowerPoint Project'],
'web'=>['How a Web Page Loads','HTML Structure','Headings and Paragraphs','Links and Navigation','Images and Alt Text','Lists','Tables','Forms','Semantic HTML','HTML Attributes','CSS Selectors','Colors and Backgrounds','CSS Typography','The Box Model','Margins and Padding','Borders and Shadows','Display and Positioning','Flexbox Basics','Flexbox Alignment','CSS Grid','Responsive Layouts','Media Queries','Mobile-First Design','Buttons and UI States','Navigation Bars','Cards and Sections','Styled Forms','CSS Variables','Reusable Styles','Web Accessibility','Browser Developer Tools','JavaScript in the Browser','Variables and Values','Conditions','Loops','Functions','Arrays','Objects','DOM Selection','DOM Events','Form Interaction','Client-Side Validation','Fetch and APIs','JSON','Error Handling','Local Storage','Debugging JavaScript','Interactive Component','Responsive Landing Page','Portfolio Page','Web Project'],
'programming'=>['Programming Fundamentals','Algorithmic Thinking','Variables','Data Types','Operators','Conditions','Loops','Functions','Parameters and Returns','Arrays','Associative Arrays','Strings','Dates and Time','Input Validation','Error Handling','Debugging','Reusable Code','File Handling','JSON','HTTP Basics','APIs and Requests','Authentication Concepts','Database Fundamentals','SQL Tables','SELECT Queries','WHERE Conditions','ORDER BY and LIMIT','INSERT Queries','UPDATE Queries','DELETE Queries','SQL Joins','Indexes','Prepared Statements','CRUD Applications','Sessions and Cookies','Security Basics','Password Handling','Form Processing','Server Validation','Git Basics','Commits','Branches','Merging Changes','GitHub Repositories','Pull Requests','Environment Configuration','Logging','Testing','Project Structure','Deployment','Programming Project'],
'design'=>['Design Fundamentals','Visual Hierarchy','Contrast and Balance','Color Theory','Color Palettes','Typography','Font Pairing','Spacing and Alignment','Grid Systems','Composition','Visual Consistency','Brand Fundamentals','Social Post Design','Banner Design','Thumbnail Design','Poster Design','Presentation Cover','Image Selection','Cropping and Framing','Background Removal','Shapes','Icons and Symbols','Simple Illustrations','Canva Workspace','Reusable Templates','Mobile Design','Readable Design','Call-to-Action Design','Redesign Exercise','Design Mistakes','Social Media Dimensions','YouTube Thumbnails','Instagram Posts','Business Flyers','Event Posters','Logo Concepts','Brand Colors','Image Export','Web Image Optimization','Accessible Design','Design Feedback','Design Systems','Asset Organization','Client-Ready Files','Revision Workflow','Branding Project','Thumbnail Project','Poster Project','Social Campaign','Design Portfolio'],
'ai'=>['Generative AI Basics','Large Language Models','Prompt Fundamentals','Writing Clear Instructions','Adding Context','Role Prompting','Few-Shot Examples','Structured Outputs','Prompt Templates','Summarization','Information Extraction','Classification','Brainstorming','AI-Assisted Writing','Research Assistance','Study Assistance','Coding Assistance','Data Analysis','Image Generation','Multimodal AI','Evaluating AI Answers','AI Hallucinations','Fact Checking','Prompt Refinement','Comparing Model Responses','AI Privacy','Sensitive Information','Responsible AI','AI Workflow Design','Reusable Prompts','AI Productivity','AI for Learning','AI for Marketing','AI for Coding','AI for Customer Support','AI Content Planning','AI Limitations','Human Review','AI Quality Criteria','Prompt Debugging','AI Experiments','AI Checklists','Documenting AI Workflows','AI Project Planning','AI Project Evaluation','Prompt Library','AI Mini Project','AI Productivity Project','AI Research Project','Responsible AI Project'],
'marketing'=>['Digital Marketing Basics','Search Intent','Keyword Research','Long-Tail Keywords','Content Planning','Search-Friendly Titles','Meta Descriptions','Heading Structure','Internal Linking','External References','Image SEO','URL Structure','Technical SEO','Mobile SEO','Page Speed','Structured Data','Search Console','Analytics','Content Quality','Helpful Content','Duplicate Content','Thin Content','Content Refreshes','Local SEO','Business Listings','Social Media Content','Social Media Calendars','Email Marketing','Call-to-Action Copy','Landing Pages','Conversion Basics','A/B Testing','Marketing Funnels','Audience Research','Competitor Research','Content Briefs','Blog Structure','Product Pages','Marketing Metrics','Traffic vs Conversions','Lead Generation','Brand Consistency','Campaign Planning','Reporting','SEO Checklist','Content Audit','Marketing Project','SEO Content Project','Social Campaign','Digital Marketing Capstone'],
'career'=>['Freelancing Basics','Choosing a Service','Finding a Niche','Building a Skill Profile','Portfolio Basics','Case Studies','Professional Bio','Service Packages','Project Scope','Client Discovery','Proposals','Client Communication','Requirements Gathering','Pricing','Estimating Work','Deadlines and Milestones','Task Management','Revision Policies','File Delivery','Professional Invoices','Payment Safety','Record Keeping','Client Feedback','Difficult Requirements','Repeat Clients','Personal Brand','LinkedIn Basics','Resume Basics','Job Profile','Interview Preparation','Professional Email','Time Management','Remote Work','Productivity Systems','Learning Plans','Skill Gap Analysis','Building Credibility','Testimonials','Publishing Work','Networking','Finding Opportunities','Freelance Marketplaces','Scam Awareness','Negotiation','Project Closure','Career Review','Freelance Project','Portfolio Project','Career Action Plan','Professional Growth Capstone'],
'advanced'=>['Operating System Concepts','Linux Basics','Terminal Navigation','Files and Permissions','Processes and Services','Package Management','Shell Commands','Environment Variables','Networking Fundamentals','IP Addresses','DNS','HTTP and HTTPS','Ports and Protocols','Routing','Firewalls','Cloud Computing','Virtual Machines','Containers','Storage','Backups','Monitoring','Logs','Authentication','Authorization','Encryption','Password Security','Multi-Factor Authentication','Phishing Defense','Web Security','SQL Injection Concepts','XSS Concepts','CSRF Concepts','Secure Coding','Version Control Workflows','Branches and Releases','CI and Deployment','APIs and Integrations','JSON and Webhooks','Caching','Performance','Scaling','Database Performance','Troubleshooting','Incident Response','Technical Documentation','Architecture Diagrams','Cloud Cost Awareness','Security Checklist','Deployment Project','Monitoring Project','Technology Capstone']
];
function bucket(string $s):array{$s=strtolower($s);if(str_contains($s,'computer')||str_contains($s,'windows')||str_contains($s,'basic'))return$GLOBALS['topics']['computer'];if(str_contains($s,'office')||str_contains($s,'excel')||str_contains($s,'word')||str_contains($s,'powerpoint'))return$GLOBALS['topics']['office'];if(str_contains($s,'html')||str_contains($s,'web')||str_contains($s,'css')||str_contains($s,'javascript'))return$GLOBALS['topics']['web'];if(str_contains($s,'php')||str_contains($s,'python')||str_contains($s,'program')||str_contains($s,'mysql')||str_contains($s,'database'))return$GLOBALS['topics']['programming'];if(str_contains($s,'design')||str_contains($s,'canva')||str_contains($s,'graphic'))return$GLOBALS['topics']['design'];if(str_contains($s,'ai')||str_contains($s,'artificial'))return$GLOBALS['topics']['ai'];if(str_contains($s,'seo')||str_contains($s,'marketing')||str_contains($s,'content'))return$GLOBALS['topics']['marketing'];if(str_contains($s,'freelanc')||str_contains($s,'career')||str_contains($s,'job'))return$GLOBALS['topics']['career'];return$GLOBALS['topics']['advanced'];}
if($_SERVER['REQUEST_METHOD']==='POST'){try{
 $hasCh=(bool)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='learning_lessons' AND column_name='chapter_id'")->fetchColumn();
 $sql=$hasCh?"SELECT l.id,l.sort_order,c.title course_title,COALESCE(lc.name,'') category_name FROM learning_lessons l JOIN learning_chapters ch ON ch.id=l.chapter_id JOIN learning_courses c ON c.id=ch.course_id LEFT JOIN learning_categories lc ON lc.id=c.category_id WHERE l.enabled=1 ORDER BY l.id":"SELECT l.id,l.sort_order,c.title course_title,COALESCE(lc.name,'') category_name FROM learning_lessons l JOIN learning_courses c ON c.id=l.course_id LEFT JOIN learning_categories lc ON lc.id=c.category_id WHERE l.enabled=1 ORDER BY l.id";
 $rows=$db->query($sql)->fetchAll(PDO::FETCH_ASSOC);$u=$db->prepare('UPDATE learning_lessons SET title=? WHERE id=?');
 foreach($rows as $r){$n=max(1,(int)$r['sort_order']);$list=bucket((string)$r['category_name'].' '.(string)$r['course_title']);$topic=$list[($n-1)%count($list)];$u->execute([$topic,(int)$r['id']]);$updated++;}
}catch(Throwable$e){$error=$e->getMessage();}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Retitle Lessons | SmartToolz</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/learning-hub/assets/css/app.css" rel="stylesheet"></head><body><main class="container py-5"><div class="mx-auto" style="max-width:820px"><div class="lh-card p-4 p-md-5"><span class="badge text-bg-primary mb-2">Learning Hub Admin</span><h1 class="h3 fw-bold">Give lessons meaningful titles</h1><p class="text-secondary">Updates titles only; existing lesson slugs and links are preserved.</p><?php if($updated):?><div class="alert alert-success"><?=number_format($updated)?> lesson titles updated.</div><?php endif;if($error):?><div class="alert alert-danger"><?=lh_h($error)?></div><?php endif;?><form method="post"><button class="btn btn-primary btn-lg">Retitle All Lessons</button></form><a class="btn btn-link px-0 mt-3" href="/learning-hub/courses.php">Open Courses →</a></div></div></main></body></html>
