<?php
declare(strict_types=1);
require_once $_SERVER['DOCUMENT_ROOT'].'/creator-ai/auth/config.php';
$pdo=db(); if(!$pdo instanceof PDO){http_response_code(500);exit('Database connection failed.');}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$pdo->exec("CREATE TABLE IF NOT EXISTS smarttoolz_analytics_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,event_type VARCHAR(40) NOT NULL,tool_slug VARCHAR(120) NOT NULL DEFAULT '',page_path VARCHAR(1000) NOT NULL DEFAULT '',target VARCHAR(500) NOT NULL DEFAULT '',event_value VARCHAR(500) NOT NULL DEFAULT '',metadata JSON NULL,visitor_id CHAR(32) NOT NULL DEFAULT '',session_id CHAR(32) NOT NULL DEFAULT '',user_id BIGINT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_event_type(event_type),INDEX idx_tool(tool_slug),INDEX idx_created(created_at),INDEX idx_visitor(visitor_id),INDEX idx_session(session_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$days=max(1,min(365,(int)($_GET['days']??30))); $where="WHERE created_at>=DATE_SUB(NOW(),INTERVAL {$days} DAY)";
$tot=(int)$pdo->query("SELECT COUNT(*) FROM smarttoolz_analytics_events {$where}")->fetchColumn();
$uses=$pdo->query("SELECT event_type,COUNT(*) total FROM smarttoolz_analytics_events {$where} GROUP BY event_type ORDER BY total DESC")->fetchAll(PDO::FETCH_ASSOC);
$tools=$pdo->query("SELECT COALESCE(NULLIF(tool_slug,''),'site') tool_slug,SUM(event_type='tool_open') opens,SUM(event_type='tool_use') uses,SUM(event_type='download') downloads,COUNT(*) total FROM smarttoolz_analytics_events {$where} GROUP BY tool_slug ORDER BY total DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$recent=$pdo->query("SELECT created_at,event_type,tool_slug,target,event_value,visitor_id,page_path FROM smarttoolz_analytics_events {$where} ORDER BY created_at DESC LIMIT 250")->fetchAll(PDO::FETCH_ASSOC);
$downloads=(int)$pdo->query("SELECT COUNT(*) FROM smarttoolz_analytics_events {$where} AND event_type='download'")->fetchColumn();
$toolUses=(int)$pdo->query("SELECT COUNT(*) FROM smarttoolz_analytics_events {$where} AND event_type='tool_use'")->fetchColumn();
$views=(int)$pdo->query("SELECT COUNT(*) FROM smarttoolz_analytics_events {$where} AND event_type='page_view'")->fetchColumn();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SmartToolz Event Analytics</title><meta name="robots" content="noindex,nofollow"><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#172033;font-family:Inter,system-ui,Arial,sans-serif}.wrap{width:min(1400px,calc(100% - 24px));margin:25px auto 60px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.top h1{margin:0;font-size:28px}.top p{margin:4px 0;color:#7b8493;font-size:12px}.links{display:flex;gap:7px;flex-wrap:wrap}.btn{padding:9px 12px;border:1px solid #e1e5ec;background:#fff;border-radius:9px;text-decoration:none;color:#4b5668;font-size:11px;font-weight:800}.btn.active,.btn.primary{background:#635bff;color:#fff;border-color:#635bff}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.stat,.card{background:#fff;border:1px solid #e2e6ed;border-radius:15px;padding:14px}.stat small{color:#8b94a3;font-size:10px}.stat strong{display:block;margin-top:5px;font-size:24px;color:#635bff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.card h2{margin:0 0 12px;font-size:14px}.bar{margin:8px 0}.barhead{display:flex;justify-content:space-between;font-size:10px;font-weight:800}.track{height:7px;background:#edf0f4;border-radius:10px;overflow:hidden;margin-top:4px}.fill{height:100%;background:#635bff}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:800px}th,td{text-align:left;padding:8px;border-bottom:1px solid #edf0f4;font-size:9px}th{font-size:8px;color:#929baa;text-transform:uppercase}td.path{overflow-wrap:anywhere;color:#635bff;font-weight:700}.pill{display:inline-block;padding:4px 7px;border-radius:99px;background:#f0efff;color:#594dd7;font-weight:800}.empty{text-align:center;padding:25px;color:#929baa;font-size:10px}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}@media(max-width:430px){.stats{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><div class="top"><div><h1>⚡ SmartToolz Event Analytics</h1><p>Live interaction telemetry plus historical event data stored in the SmartToolz database.</p></div><div class="links"><a class="btn" href="/analytics/">Analytics</a><a class="btn" href="/analytics/advanced.php">Advanced</a><?php foreach([1=>'24H',7=>'7D',30=>'30D',90=>'90D',365=>'1Y'] as $d=>$l):?><a class="btn <?=$days===$d?'active':''?>" href="?days=<?=$d?>"><?=$l?></a><?php endforeach;?></div></div><section class="stats"><div class="stat"><small>Tracked Events</small><strong><?=number_format($tot)?></strong></div><div class="stat"><small>Page Views</small><strong><?=number_format($views)?></strong></div><div class="stat"><small>Tool Uses</small><strong><?=number_format($toolUses)?></strong></div><div class="stat"><small>Downloads</small><strong><?=number_format($downloads)?></strong></div></section><div class="grid"><section class="card"><h2>🛠️ Tool performance</h2><?php if(!$tools):?><div class="empty">No event data yet.</div><?php else:$m=max(1,max(array_map(fn($r)=>(int)$r['total'],$tools)));foreach($tools as $r):?><div class="bar"><div class="barhead"><span><?=e($r['tool_slug'])?></span><span><?=number_format((int)$r['total'])?></span></div><div class="track"><div class="fill" style="width:<?=((int)$r['total']/$m*100)?>%"></div></div><div style="font-size:9px;color:#7d8796;margin-top:3px">Opens <?=number_format((int)$r['opens'])?> · Uses <?=number_format((int)$r['uses'])?> · Downloads <?=number_format((int)$r['downloads'])?></div></div><?php endforeach;endif;?></section><section class="card"><h2>📊 Event mix</h2><?php $m=max(1,max(array_map(fn($r)=>(int)$r['total'],$uses?:[['total'=>1]])));foreach($uses as $r):?><div class="bar"><div class="barhead"><span><?=e($r['event_type'])?></span><span><?=number_format((int)$r['total'])?></span></div><div class="track"><div class="fill" style="width:<?=((int)$r['total']/$m*100)?>%"></div></div></div><?php endforeach;if(!$uses):?><div class="empty">No event data yet.</div><?php endif;?></section></div><section class="card" style="margin-top:12px"><h2>🧾 Recent events</h2><div class="tablewrap"><table><thead><tr><th>Time</th><th>Event</th><th>Tool</th><th>Target</th><th>Value</th><th>Page</th><th>Visitor</th></tr></thead><tbody><?php if(!$recent):?><tr><td colspan="7" class="empty">No events yet.</td></tr><?php else:foreach($recent as $r):?><tr><td><?=e($r['created_at'])?></td><td><span class="pill"><?=e($r['event_type'])?></span></td><td><?=e($r['tool_slug']?:'site')?></td><td><?=e($r['target'])?></td><td><?=e($r['event_value'])?></td><td class="path"><?=e($r['page_path'])?></td><td><?=e(substr((string)$r['visitor_id'],0,12))?></td></tr><?php endforeach;endif;?></tbody></table></div></section></main></body></html>
