<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
?><!doctype html><html lang="en"><head>
<?php require_once dirname(__DIR__) . '/head.php'; ?>



<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Percentage Calculator — SmartToolz</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#172033;font-family:Inter,system-ui,Arial,sans-serif}.page{width:min(1200px,calc(100% - 28px));margin:32px auto 70px}.hero,.tool,.tools{background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 14px 40px rgba(20,30,70,.05)}.hero{padding:28px;margin-bottom:18px}.hero h1{font-size:clamp(30px,5vw,44px);margin:0 0 8px}.muted{color:#707b8e;line-height:1.6}.layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:20px;align-items:start}.tool{padding:25px}.tools{position:sticky;top:88px;max-height:calc(100vh - 108px);overflow:auto;padding:16px}.tools h3{margin:2px 8px 12px}.tools a{display:block;padding:9px 10px;margin:3px 0;border-radius:9px;text-decoration:none;color:#536075;font-size:13px;font-weight:700}.tools a:hover,.tools a.active{background:#f0efff;color:#635bff}.input{width:100%;padding:13px;border:1px solid #dfe4ec;border-radius:11px;font:inherit}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:10px 0}.btn{margin-top:14px;border:0;border-radius:11px;padding:12px 18px;background:#635bff;color:#fff;font-weight:800;cursor:pointer}.out{margin-top:15px;padding:16px;border:1px solid #e5e9f0;border-radius:12px;background:#f7f8fb;min-height:50px}@media(max-width:800px){.layout{grid-template-columns:1fr}.tools{position:static;max-height:330px}.row{grid-template-columns:1fr}.hero,.tool{padding:21px}}</style></head><body>
<?php require_once dirname(__DIR__) . '/header.php'; ?>






<main class="page"><section class="hero"><h1>Percentage Calculator</h1><p class="muted">Calculate percentages, percentage increases and decreases quickly in your browser.</p></section><div class="layout"><section class="tool"><h2>Percentage Calculator</h2><h3>What is X% of Y?</h3><div class="row"><input class="input" id="p1" type="number" placeholder="Percentage %"><input class="input" id="n1" type="number" placeholder="Number"></div><button class="btn" onclick="calc1()">Calculate</button><div class="out" id="o1"></div><h3>What percentage is X of Y?</h3><div class="row"><input class="input" id="x2" type="number" placeholder="Part"><input class="input" id="y2" type="number" placeholder="Whole"></div><button class="btn" onclick="calc2()">Calculate</button><div class="out" id="o2"></div><h3>Percentage change</h3><div class="row"><input class="input" id="old" type="number" placeholder="Original value"><input class="input" id="new" type="number" placeholder="New value"></div><button class="btn" onclick="calc3()">Calculate</button><div class="out" id="o3"></div></section><aside class="tools"><h3>🛠️ All Tools</h3><?php $items=['image-compressor.php'=>'🖼️ Image Compressor','image-resizer.php'=>'📐 Image Resizer','jpg-to-png.php'=>'↩️ JPG to PNG','png-to-jpg.php'=>'↩️ PNG to JPG','word-counter.php'=>'📝 Word Counter','case-converter.php'=>'🔤 Case Converter','qr-generator.php'=>'🔐 QR Code Generator','password-generator.php'=>'🔑 Password Generator','json-formatter.php'=>'{} JSON Formatter','url-encoder.php'=>'🔗 URL Encoder','pdf-to-jpg.php'=>'📄 PDF to JPG','duplicate-line-remover.php'=>'🖌️ Duplicate Line Remover','image-cropper.php'=>'✂️ Image Cropper','image-rotator.php'=>'🔄 Image Rotator','gif-maker.php'=>'🎞️ GIF Maker','gif-to-jpg.php'=>'🖼️ GIF to JPG','jpg-to-webp.php'=>'🖼️ JPG to WebP','png-to-webp.php'=>'🖼️ PNG to WebP','pdf-to-png.php'=>'📄 PDF to PNG','pdf-merger.php'=>'📑 PDF Merger','pdf-splitter.php'=>'📄 PDF Splitter','pdf-compressor.php'=>'📦 PDF Compressor','age-calculator.php'=>'🎂 Age Calculator','percentage-calculator.php'=>'% Percentage Calculator','unit-converter.php'=>'📏 Unit Converter','stopwatch-timer.php'=>'⏱️ Stopwatch Timer','bmi-calculator.php'=>'⚖️ BMI Calculator'];foreach($items as $f=>$n):?><a class="<?=basename($_SERVER['SCRIPT_NAME'])===$f?'active':''?>" href="/tools/<?=htmlspecialchars($f,ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars($n)?></a><?php endforeach;?><a href="/tool.php">View All Tools →</a></aside></div></main>
<script>const v=id=>Number(document.getElementById(id).value);function calc1(){const p=v('p1'),n=v('n1');document.getElementById('o1').textContent=Number.isFinite(p)&&Number.isFinite(n)?(p*n/100).toFixed(2):'Enter valid values.'}function calc2(){const x=v('x2'),y=v('y2');document.getElementById('o2').textContent=y!==0?(x/y*100).toFixed(2)+'%':'Whole value cannot be zero.'}function calc3(){const a=v('old'),b=v('new');document.getElementById('o3').textContent=a!==0?((b-a)/Math.abs(a)*100).toFixed(2)+'%':'Original value cannot be zero.'}</script>



<?php require_once dirname(__DIR__) . '/footer.php'; ?>
</body></html>