<?php
declare(strict_types=1);if(session_status()!==PHP_SESSION_ACTIVE)session_start();?><!doctype html><html lang="en"><head>
<?php require_once dirname(__DIR__) . '/head.php'; ?>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Unit Converter — SmartToolz</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#172033;font-family:Inter,system-ui,Arial,sans-serif}.page{width:min(1200px,calc(100% - 28px));margin:32px auto 70px}.hero,.tool,.tools{background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 14px 40px rgba(20,30,70,.05)}.hero{padding:28px;margin-bottom:18px}.hero h1{font-size:clamp(30px,5vw,44px);margin:0 0 8px}.muted{color:#707b8e;line-height:1.6}.layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:20px}.tool{padding:25px}.tools{position:sticky;top:88px;max-height:calc(100vh - 108px);overflow:auto;padding:16px}.tools h3{margin:2px 8px 12px}.tools a{display:block;padding:9px 10px;margin:3px 0;border-radius:9px;text-decoration:none;color:#536075;font-size:13px;font-weight:700}.tools a:hover,.tools a.active{background:#f0efff;color:#635bff}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.input,select{width:100%;padding:13px;border:1px solid #dfe4ec;border-radius:11px;font:inherit}.btn{margin-top:14px;border:0;border-radius:11px;padding:12px 18px;background:#635bff;color:#fff;font-weight:800;cursor:pointer}.out{margin-top:15px;padding:16px;border:1px solid #e5e9f0;border-radius:12px;background:#f7f8fb}@media(max-width:800px){.layout{grid-template-columns:1fr}.tools{position:static;max-height:330px}.row{grid-template-columns:1fr}.hero,.tool{padding:21px}}</style></head><body>
<?php require_once dirname(__DIR__) . '/header.php'; ?>



<main class="page"><section class="hero"><h1>Unit Converter</h1><p class="muted">Convert common length, weight and temperature units instantly.</p></section><div class="layout"><section class="tool"><h2>Unit Converter</h2><div class="row"><input class="input" id="value" type="number" step="any" placeholder="Value"><select id="type"><option value="length">Length</option><option value="weight">Weight</option><option value="temperature">Temperature</option></select></div><div class="row"><select id="from"></select><select id="to"></select></div><button class="btn" id="convert">Convert</button><div class="out" id="out"></div></section><aside class="tools"><h3>🛠️ All Tools</h3><?php $items=['image-compressor.php'=>'🖼️ Image Compressor','image-resizer.php'=>'📐 Image Resizer','jpg-to-png.php'=>'↩️ JPG to PNG','png-to-jpg.php'=>'↩️ PNG to JPG','word-counter.php'=>'📝 Word Counter','case-converter.php'=>'🔤 Case Converter','qr-generator.php'=>'🔐 QR Code Generator','password-generator.php'=>'🔑 Password Generator','json-formatter.php'=>'{} JSON Formatter','url-encoder.php'=>'🔗 URL Encoder','pdf-to-jpg.php'=>'📄 PDF to JPG','duplicate-line-remover.php'=>'🖌️ Duplicate Line Remover','image-cropper.php'=>'✂️ Image Cropper','image-rotator.php'=>'🔄 Image Rotator','gif-maker.php'=>'🎞️ GIF Maker','gif-to-jpg.php'=>'🖼️ GIF to JPG','jpg-to-webp.php'=>'🖼️ JPG to WebP','png-to-webp.php'=>'🖼️ PNG to WebP','pdf-to-png.php'=>'📄 PDF to PNG','pdf-merger.php'=>'📑 PDF Merger','pdf-splitter.php'=>'📄 PDF Splitter','pdf-compressor.php'=>'📦 PDF Compressor','age-calculator.php'=>'🎂 Age Calculator','percentage-calculator.php'=>'% Percentage Calculator','unit-converter.php'=>'📏 Unit Converter','stopwatch-timer.php'=>'⏱️ Stopwatch Timer'];foreach($items as $f=>$n):?><a class="<?=basename($_SERVER['SCRIPT_NAME'])===$f?'active':''?>" href="/tools/<?=htmlspecialchars($f,ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars($n)?></a><?php endforeach;?><a href="/tool.php">View All Tools →</a></aside></div></main>
<script>const sets={length:{meter:1,km:1000,cm:.01,mm:.001,mile:1609.344,foot:.3048,inch:.0254},weight:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.0283495231},temperature:{c:'c',f:'f',k:'k'}};const t=document.getElementById('type'),a=document.getElementById('from'),b=document.getElementById('to');function fill(){const s=sets[t.value];a.innerHTML='';b.innerHTML='';Object.keys(s).forEach(x=>{a.add(new Option(x,x));b.add(new Option(x,x))})}t.onchange=fill;fill();document.getElementById('convert').onclick=()=>{let v=+document.getElementById('value').value;const typ=t.value,from=a.value,to=b.value;if(!Number.isFinite(v)){out.textContent='Enter a valid value.';return}let r;if(typ==='temperature'){let c=from==='c'?v:from==='f'?(v-32)*5/9:v-273.15;r=to==='c'?c:to==='f'?c*9/5+32:c+273.15}else r=v*sets[typ][from]/sets[typ][to];out.textContent=r.toLocaleString(undefined,{maximumFractionDigits:8})+' '+to}</script>
<?php require_once dirname(__DIR__) . '/footer.php'; ?>
</body></html>