<?php
declare(strict_types=1);
require_once __DIR__.'/common/bootstrap.php';
learning_require_login();
$courses=learning_courses_with_progress(learning_user_id());
$u=learning_current_user();
function hroot($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Learning Hub — SmartToolz</title><style>
body{margin:0;background:#080a10;color:#fff;font-family:Inter,system-ui}.wrap{max-width:1200px;margin:auto;padding:30px 18px 70px}.hero{padding:30px;border:1px solid #fff1;border-radius:18px;background:radial-gradient(circle at 80% 0,#8b5cf625,transparent 35%),#10151e}.hero h1{font-size:32px;margin:8px 0}.hero p{color:#8c96a8;font-size:10px;line-height:1.7;max-width:680px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-top:18px}.card{padding:17px;border:1px solid #fff1;border-radius:13px;background:#10151e}.icon{font-size:21px}.title{font-size:10px;font-weight:900;margin-top:11px}.meta{font-size:7px;color:#727d90;margin-top:5px}.bar{height:5px;background:#242b38;border-radius:8px;margin-top:9px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#8b5cf6,#22d3ee)}a{text-decoration:none;color:inherit}.top{display:flex;justify-content:space-between;margin-bottom:16px;font-size:8px}.top a{color:#a78bfa}@media(max-width:900px){.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:430px){.grid{grid-template-columns:1fr}.hero h1{font-size:25px}}
</style></head><body><div class=wrap><div class=top><span><?=hroot($u['name']??'Creator')?></span><a href="/creator-ai/logout">Logout</a></div><section class=hero><div style="font-size:8px;color:#a78bfa;font-weight:900;letter-spacing:1.5px">SMARTTOOLZ LEARNING HUB</div><h1>Learn every programming language.</h1><p>Courses, tutorials, Try It Yourself, practice, quizzes, mock tests, projects, progress, notes, bookmarks and certificates — one account, one learning system.</p></section><div class=grid><?php foreach($courses as $c):?><a class=card href="/creator-ai/learning/<?=h($c['slug'])?>/"><div class=icon><?=h($c['icon'])?></div><div class=title><?=h($c['title'])?></div><div class=meta><?=h($c['level'])?> · <?=$c['lessons']?> lessons · <?=$c['percent']?>%</div><div class=bar><i style="width:<?=$c['percent']?>%"></i></div></a><?php endforeach;?></div></div></body></html>