<?php
declare(strict_types=1);
require_once __DIR__ . '/lib/settings.php';
$siteName = smarttoolz_setting_string('site_name', 'SmartToolz');
$siteTagline = smarttoolz_setting_string('site_tagline', 'Free, fast and simple online tools.');
$script = basename((string)($_SERVER['SCRIPT_NAME'] ?? ''));
$isHome = in_array($script, ['index.php','home.php'], true);
$isAllTools = $script === 'tool.php';
$isToolPage = !$isHome && !$isAllTools && str_contains((string)($_SERVER['SCRIPT_NAME'] ?? ''), '/tools/');
$slug = basename($script, '.php');
$toolTitle = ucwords(str_replace(['-','_'], ' ', strtolower($slug ?: 'Online Tool')));
$toolReportUrl = '/report-tool.php?tool=' . rawurlencode($slug) . '&name=' . rawurlencode($toolTitle) . '&url=' . rawurlencode('/tools/' . $slug . '.php');
?>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,500,0,0&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
<header class="site-header"><nav class="navbar">
<a class="logo" href="/" aria-label="SmartToolz home"><span class="logo-icon"><span class="material-symbols-rounded">build</span></span><span><?=htmlspecialchars($siteName,ENT_QUOTES,'UTF-8')?></span></a>
<div class="nav-links"><a href="/"><span class="material-symbols-rounded">home</span> Home</a><a href="/tool.php"><span class="material-symbols-rounded">apps</span> All Tools</a></div>
</nav></header>
<?php if ($isToolPage): ?>
<section class="tool-seo-intro"><div><span class="tool-free-badge">FREE ONLINE TOOL</span><h2>Free Online <?=htmlspecialchars($toolTitle,ENT_QUOTES,'UTF-8')?></h2><p><?=htmlspecialchars($siteName,ENT_QUOTES,'UTF-8')?> <?=htmlspecialchars($toolTitle,ENT_QUOTES,'UTF-8')?> helps you complete this task quickly and easily. <?=htmlspecialchars($siteTagline,ENT_QUOTES,'UTF-8')?></p></div><div class="how-use"><h3><span class="material-symbols-rounded">menu_book</span> How to Use</h3><ol><li>Enter, upload or select your data.</li><li>Choose your options and click the main action button.</li><li>Review the result and download or copy it.</li></ol></div></section>
<div class="tool-support-actions"><a class="tool-support-card report" href="<?=htmlspecialchars($toolReportUrl,ENT_QUOTES,'UTF-8')?>"><span class="support-icon"><span class="material-symbols-rounded">bug_report</span></span><span><strong>Report a Problem</strong><small>Tool not working, wrong result, error or upload issue</small></span><span class="material-symbols-rounded arrow">arrow_forward</span></a><a class="tool-support-card request" href="/request-tool.php"><span class="support-icon"><span class="material-symbols-rounded">lightbulb</span></span><span><strong>Request a New Tool</strong><small>Tell us what you want SmartToolz to build next</small></span><span class="material-symbols-rounded arrow">arrow_forward</span></a></div>
<?php endif; ?>
<style>
.material-symbols-rounded{font-size:1.25em;line-height:1;vertical-align:middle;font-variation-settings:'FILL' 0,'wght' 600,'GRAD' 0,'opsz' 24}.site-header{position:sticky;top:0;z-index:1000;background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border-bottom:1px solid #e7eaf1}.navbar{width:calc(100% - 20px);box-sizing:border-box;min-height:72px;margin:auto;padding:0 14px;display:flex;align-items:center;justify-content:space-between;gap:22px}.logo{display:flex;align-items:center;gap:10px;color:#172033;font-size:21px;font-weight:850;text-decoration:none;white-space:nowrap}.logo-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;color:#fff;background:linear-gradient(135deg,#635bff,#916cff);box-shadow:0 8px 20px rgba(99,91,255,.2)}.logo-icon .material-symbols-rounded{font-size:22px}.nav-links{display:flex;align-items:center;gap:7px}.nav-links>a{display:inline-flex;align-items:center;gap:5px;padding:9px 10px;color:#596477;font-size:12px;font-weight:750;text-decoration:none;border-radius:10px}.nav-links>a:hover{color:#635bff;background:#f4f2ff}.nav-links>a .material-symbols-rounded{font-size:18px}.tool-seo-intro{width:100%;box-sizing:border-box;margin:24px 0 0;padding:24px 26px;display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,1fr);gap:22px;background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 10px 35px rgba(20,30,70,.045)}.tool-free-badge{display:inline-flex;padding:6px 10px;border-radius:999px;background:#eeedff;color:#635bff;font-size:10px;font-weight:900}.tool-seo-intro h2{margin:9px 0 7px;font-size:26px;line-height:1.15}.tool-seo-intro p{margin:0;color:#707b8e;font-size:13px;line-height:1.7}.how-use{padding:18px;background:#f7f8fc;border:1px solid #e8eaf1;border-radius:15px}.how-use h3{display:flex;align-items:center;gap:6px;margin:0 0 8px;font-size:16px}.how-use h3 .material-symbols-rounded{color:#635bff}.how-use ol{margin:0;padding-left:20px;color:#596477;font-size:12px;line-height:1.8}.tool-support-actions{width:100%;display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0 4px}.tool-support-card{display:flex;align-items:center;gap:11px;padding:14px 15px;border:1px solid #e3e7ef;border-radius:16px;background:#fff;color:#172033;text-decoration:none;box-shadow:0 8px 26px rgba(20,30,70,.035)}.tool-support-card strong{display:block;font-size:12px}.tool-support-card small{display:block;color:#707b8e;font-size:10px;margin-top:3px}.support-icon{width:38px;height:38px;display:grid;place-items:center;flex:0 0 38px;border-radius:11px;background:#f0efff;color:#635bff}.arrow{margin-left:auto;color:#8a93a2}@media(max-width:680px){.tool-seo-intro{grid-template-columns:1fr}.tool-support-actions{grid-template-columns:1fr}}
</style>
