<?php
declare(strict_types=1);
require_once __DIR__ . '/lib/feedback.php';
[$defaultName,$defaultEmail]=smarttoolz_feedback_user_context();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
$name=trim((string)($_POST['name']??''));$email=trim((string)($_POST['email']??''));$toolName=trim((string)($_POST['tool_name']??''));$description=trim((string)($_POST['description']??''));$useCase=trim((string)($_POST['use_case']??''));
if(trim((string)($_POST['website']??''))!=='')$error='Something went wrong. Please try again.';elseif($toolName===''||mb_strlen($toolName)<2)$error='Please enter the tool you want us to build.';elseif($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Please enter a valid email address.';elseif($description===''||mb_strlen($description)<8)$error='Please tell us what the tool should do.';else try{$pdo=smarttoolz_db();$pdo->prepare('INSERT INTO tool_requests(user_id,name,email,tool_name,description,use_case,source) VALUES(NULL,?,?,?,?,?,?)')->execute([$name!==''?$name:null,$email!==''?$email:null,$toolName,$description,$useCase!==''?$useCase:null,'website']);$id=(int)$pdo->lastInsertId();$body="New SmartToolz tool request\n\nRequest #{$id}\nRequested tool: {$toolName}\nName: ".($name?:'Not provided')."\nEmail: ".($email?:'Not provided')."\n\nWhat it should do:\n{$description}\n\nWhy they need it:\n".($useCase?:'Not provided')."\n";$sent=smarttoolz_feedback_mail('[SmartToolz] New tool request — '.$toolName,$body,$email?:null);$message=$sent?'Great! Your tool idea is saved and the SmartToolz team has been emailed.':'Great! Your tool idea is saved. Email notification could not be sent right now.';$_POST=[];}catch(Throwable $e){error_log('SmartToolz tool request: '.$e->getMessage());$error='We could not save the request right now. Please try again.';}}
?>
<?php require_once __DIR__.'/header.php'; ?>
<style>body{margin:0;background:#f6f8fc;color:#172033;font-family:Inter,system-ui,Arial,sans-serif}.page{width:min(850px,calc(100% - 24px));margin:35px auto 60px}.card{background:#fff;border:1px solid #e5e9f0;border-radius:20px;padding:26px;box-shadow:0 14px 40px rgba(20,30,70,.05)}h1{margin:0 0 8px;font-size:clamp(30px,5vw,44px)}p{color:#707b8e;line-height:1.65}.field{display:grid;gap:7px;margin:15px 0}.field label{font-size:12px;font-weight:800}.field input,.field textarea{width:100%;box-sizing:border-box;border:1px solid #dfe3eb;border-radius:11px;padding:12px;font:inherit}.field textarea{min-height:130px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.actions{display:flex;gap:9px;flex-wrap:wrap}.btn{display:inline-flex;padding:11px 16px;border:0;border-radius:10px;background:#635bff;color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.btn.alt{background:#edf0f5;color:#344055}.notice{padding:12px;border-radius:10px;margin-bottom:14px;font-size:13px}.ok{background:#ecfbf3;color:#127449}.err{background:#fff0f0;color:#b4232d}.hp{position:absolute;left:-9999px}@media(max-width:650px){.row{grid-template-columns:1fr}}</style>
<main class="page"><section class="card"><h1>What should we build next?</h1><p>Tell us the tool you want SmartToolz to add.</p><?php if($message):?><div class="notice ok">✅ <?=smarttoolz_h($message)?></div><?php endif;?><?php if($error):?><div class="notice err">⚠️ <?=smarttoolz_h($error)?></div><?php endif;?><form method="post"><div class="hp"><input name="website" tabindex="-1" autocomplete="off"></div><div class="row"><div class="field"><label>Tool name *</label><input name="tool_name" required maxlength="180"></div><div class="field"><label>Email</label><input name="email" type="email" maxlength="190"></div></div><div class="field"><label>What should the tool do? *</label><textarea name="description" required maxlength="6000"></textarea></div><div class="field"><label>How would you use it?</label><textarea name="use_case" maxlength="4000"></textarea></div><div class="field"><label>Your name</label><input name="name" maxlength="120"></div><div class="actions"><button class="btn" type="submit">Submit Tool Idea</button><a class="btn alt" href="/">Browse Tools</a></div></form></section></main>
<?php require_once __DIR__.'/footer.php'; ?>