<?php
declare(strict_types=1);

// Dependency-free fallback engine. All public tools should normally resolve to /tools/*.php.
$slug = preg_replace('/[^a-z0-9-]/', '', strtolower((string)($_GET['tool'] ?? ''))) ?: 'tool';
$names = [
 'age-calculator'=>'Age Calculator','percentage-calculator'=>'Percentage Calculator','bmi-calculator'=>'BMI Calculator','unit-converter'=>'Unit Converter',
 'word-counter'=>'Word Counter','case-converter'=>'Case Converter','remove-duplicate-lines'=>'Remove Duplicate Lines','remove-extra-spaces'=>'Remove Extra Spaces',
 'sort-lines'=>'Sort Lines','reverse-text'=>'Reverse Text','text-to-slug'=>'Text to Slug','base64-encoder'=>'Base64 Encoder','base64-decoder'=>'Base64 Decoder',
 'url-encoder'=>'URL Encoder','url-decoder'=>'URL Decoder','html-encoder'=>'HTML Encoder','html-decoder'=>'HTML Decoder','uuid-generator'=>'UUID Generator',
 'random-number-generator'=>'Random Number Generator','lorem-ipsum-generator'=>'Lorem Ipsum Generator','timestamp-converter'=>'Timestamp Converter','unix-timestamp'=>'Unix Timestamp'
];
$title = $names[$slug] ?? ucwords(str_replace('-', ' ', $slug));
require_once __DIR__ . '/header.php';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title, ENT_QUOTES, 'UTF-8')?> — SmartToolz</title><meta name="robots" content="index,follow"><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fc;color:#172033;font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{width:min(980px,calc(100% - 28px));margin:38px auto 70px}.hero,.tool{background:#fff;border:1px solid #e5e9f0;border-radius:22px;box-shadow:0 15px 45px #1d27400d}.hero{padding:30px;margin-bottom:18px}.tag{color:#635bff;font-size:11px;font-weight:900;letter-spacing:1px}.hero h1{font-size:clamp(30px,5vw,48px);letter-spacing:-2px;margin:7px 0}.hero p{color:#707b8e}.tool{padding:25px}.input,textarea,select{width:100%;padding:12px;border:1px solid #dfe4ec;border-radius:11px;margin:6px 0 12px;font:inherit}textarea{min-height:190px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.btn{border:0;border-radius:11px;padding:12px 17px;background:#635bff;color:#fff;font-weight:800;cursor:pointer}.btn.alt{background:#edf0f5;color:#273147}.out{margin-top:14px;padding:15px;border:1px solid #e5e9f0;border-radius:12px;background:#f7f8fb;white-space:pre-wrap;word-break:break-word}.center{text-align:center}@media(max-width:650px){.row{grid-template-columns:1fr}.hero,.tool{padding:21px}}</style></head><body><main class="wrap"><section class="hero"><div class="tag">SMARTTOOLZ TOOL</div><h1><?=htmlspecialchars($title, ENT_QUOTES, 'UTF-8')?></h1><p>Simple, fast and responsive. This fallback uses your browser's built-in capabilities and does not load third-party services.</p></section><section class="tool" id="app"></section></main><?php require_once __DIR__ . '/footer.php'; ?><script>
(function(){'use strict';const S=<?=json_encode($slug)?>,A=document.getElementById('app'),$=s=>A.querySelector(s);
const textTools={
 'word-counter':()=>{A.innerHTML='<h2>Word Counter</h2><textarea id="i" placeholder="Enter text..."></textarea><div class="out" id="o"></div>';$('#i').oninput=()=>{const s=$('#i').value;$('#o').textContent=`Words: ${s.trim()?s.trim().split(/\s+/).length:0}\nCharacters: ${s.length}\nCharacters (no spaces): ${s.replace(/\s/g,'').length}\nLines: ${s?s.split(/\r?\n/).length:0}`}},
 'case-converter':()=>simple(s=>s.toUpperCase()),'remove-duplicate-lines':()=>simple(s=>[...new Set(s.split(/\r?\n/))].join('\n')),
 'remove-extra-spaces':()=>simple(s=>s.replace(/[ \t]+/g,' ').replace(/^ +| +$/gm,'')),'sort-lines':()=>simple(s=>s.split(/\r?\n/).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'})).join('\n')),
 'reverse-text':()=>simple(s=>[...s].reverse().join('')),'text-to-slug':()=>simple(s=>s.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-')),
 'base64-encoder':()=>simple(s=>btoa(unescape(encodeURIComponent(s)))),'base64-decoder':()=>simple(s=>decodeURIComponent(escape(atob(s)))),'url-encoder':()=>simple(s=>encodeURIComponent(s)),'url-decoder':()=>simple(s=>decodeURIComponent(s)),
 'html-encoder':()=>simple(s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))),'html-decoder':()=>simple(s=>{const t=document.createElement('textarea');t.innerHTML=s;return t.value}),
 'uuid-generator':()=>{A.innerHTML='<h2>UUID Generator</h2><button class="btn" id="go">Generate</button><div class="out" id="o"></div>';$('#go').onclick=()=>$('#o').textContent=crypto.randomUUID()},
 'random-number-generator':()=>{A.innerHTML='<h2>Random Number Generator</h2><div class="row"><input id="a" class="input" type="number" value="1"><input id="b" class="input" type="number" value="100"></div><button class="btn" id="go">Generate</button><div class="out" id="o"></div>';$('#go').onclick=()=>$('#o').textContent=Math.floor(Math.random()*(+$('#b').value-+$('#a').value+1)) + +$('#a').value},
 'unix-timestamp':()=>{A.innerHTML='<h2>Unix Timestamp</h2><button class="btn" id="go">Get Timestamp</button><div class="out" id="o"></div>';$('#go').onclick=()=>$('#o').textContent=Math.floor(Date.now()/1000)},
 'timestamp-converter':()=>{A.innerHTML='<h2>Timestamp Converter</h2><input id="v" class="input" type="number" placeholder="Unix timestamp"><button class="btn" id="go">Convert</button><div class="out" id="o"></div>';$('#go').onclick=()=>$('#o').textContent=new Date(+$('#v').value*1000).toString()},
 'age-calculator':()=>{A.innerHTML='<h2>Age Calculator</h2><input id="d" class="input" type="date"><button class="btn" id="go">Calculate</button><div class="out" id="o"></div>';$('#go').onclick=()=>{const d=$('#d').value;if(!d)return;const b=new Date(d),n=new Date();let age=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))age--;$('#o').textContent=age+' years'}},
 'percentage-calculator':()=>{A.innerHTML='<h2>Percentage Calculator</h2><div class="row"><input id="a" class="input" type="number" placeholder="Percentage"><input id="b" class="input" type="number" placeholder="Number"></div><button class="btn" id="go">Calculate</button><div class="out" id="o"></div>';$('#go').onclick=()=>$('#o').textContent=((+$('#a').value*+$('#b').value)/100).toFixed(2)},
 'bmi-calculator':()=>{A.innerHTML='<h2>BMI Calculator</h2><div class="row"><input id="w" class="input" type="number" placeholder="Weight kg"><input id="h" class="input" type="number" placeholder="Height cm"></div><button class="btn" id="go">Calculate</button><div class="out" id="o"></div>';$('#go').onclick=()=>{const h=+$('#h').value/100;$('#o').textContent=(+$('#w').value/(h*h)).toFixed(2)}},
 'unit-converter':()=>{A.innerHTML='<h2>Unit Converter</h2><input id="v" class="input" type="number" value="1"><div class="row"><select id="f"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="lb">Pounds</option></select><select id="t"><option value="m">Meters</option><option value="km">Kilometers</option><option value="ft">Feet</option><option value="mi">Miles</option><option value="kg">Kilograms</option><option value="lb">Pounds</option></select></div><button class="btn" id="go">Convert</button><div class="out" id="o"></div>';$('#go').onclick=()=>{const z={m:1,km:1000,ft:.3048,mi:1609.344,kg:1,lb:.453592};$('#o').textContent=((+$('#v').value*z[$('#f').value])/z[$('#t').value]).toFixed(6)+' '+$('#t').value}},
 'lorem-ipsum-generator':()=>{A.innerHTML='<h2>Lorem Ipsum Generator</h2><input id="n" class="input" type="number" value="3" min="1" max="20"><button class="btn" id="go">Generate</button><textarea id="o"></textarea>';$('#go').onclick=()=>$('#o').value=Array.from({length:+$('#n').value},()=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.').join('\n\n')}
};
function simple(fn){A.innerHTML='<h2><?=htmlspecialchars($title,ENT_QUOTES,'UTF-8')?></h2><textarea id="i" placeholder="Enter text..."></textarea><button class="btn" id="go">Process</button><button class="btn alt" id="cp">Copy</button><div class="out" id="o"></div>';$('#go').onclick=()=>{try{$('#o').textContent=fn($('#i').value)}catch(e){$('#o').textContent='Invalid input: '+e.message}};$('#cp').onclick=()=>navigator.clipboard?.writeText($('#o').textContent)}
if(textTools[S]) textTools[S](); else A.innerHTML='<div class="out">This tool has its own implementation. The fallback engine does not load external libraries.</div>';
})();</script></body></html>
