<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free Unix Timestamp Converter Online','description'=>'Convert Unix timestamps to readable dates and dates to Unix timestamps instantly in your browser with SmartToolz.','url'=>'https://smarttoolz.in/tools/timestamp-converter/'];
smarttoolz_tool_page_start($tool);
?>
<main class="ts-page"><section class="tool-head"><span class="eyebrow">TIMESTAMP CONVERTER</span><h1>Unix Timestamp Converter</h1><p>Convert Unix timestamps to dates and dates to Unix timestamps instantly.</p></section><section class="ts-card"><div class="mode"><button class="tab active" data-mode="toDate">Timestamp → Date</button><button class="tab" data-mode="toTimestamp">Date → Timestamp</button></div><div id="toDateBox"><label>Unix timestamp<input id="timestamp" inputmode="numeric" placeholder="e.g. 1757203200"></label><button id="convertDate" class="primary">Convert to Date</button></div><div id="toTimestampBox" hidden><label>Date and time<input id="date" type="datetime-local"></label><button id="convertTs" class="primary">Convert to Timestamp</button></div><div class="result"><span>Result</span><p id="result">Your result will appear here.</p><button id="copy">Copy Result</button></div></section><section class="info-grid"><article><h2>What is a Unix timestamp?</h2><p>A Unix timestamp represents a point in time as the number of seconds since January 1, 1970 UTC.</p></article><article><h2>Quick and private</h2><p>All conversion happens in your browser. No date or timestamp needs to be uploaded.</p></article></section></main>
<style>.ts-page{width:min(820px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.ts-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.mode{display:flex;gap:7px;padding:5px;margin-bottom:20px;background:#f4f5f9;border-radius:12px}.tab{flex:1;border:0;border-radius:9px;padding:11px;background:transparent;color:#667085;font-size:10px;font-weight:900;cursor:pointer}.tab.active{background:#fff;color:#5541ff;box-shadow:0 2px 8px rgba(16,24,40,.08)}.ts-card label{display:grid;gap:7px;color:#344054;font-size:11px;font-weight:800}.ts-card input{box-sizing:border-box;width:100%;height:47px;padding:0 12px;border:1px solid #dfe3eb;border-radius:11px;background:#fcfdff;color:#172033;font-size:13px;outline:0}.ts-card input:focus{border-color:#8d80ff}.primary{width:100%;height:47px;margin-top:12px;border:0;border-radius:11px;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff;font-size:11px;font-weight:900;cursor:pointer}.result{margin-top:15px;padding:17px;border:1px solid #e7eaf0;border-radius:14px;background:#fafbff}.result span{font-size:10px;color:#69738e;font-weight:800}.result p{margin:9px 0 14px;color:#263052;font-size:17px;line-height:1.5;word-break:break-word}.result button{padding:9px 12px;border:1px solid #dfe3eb;border-radius:9px;background:#111936;color:#fff;font-size:9px;font-weight:900;cursor:pointer}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 9px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:600px){.ts-page{width:calc(100% - 20px)}.ts-card{padding:16px}.mode{flex-direction:column}.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{let mode='toDate';const result=document.getElementById('result'),dateBox=document.getElementById('toDateBox'),tsBox=document.getElementById('toTimestampBox');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));dateBox.hidden=mode!=='toDate';tsBox.hidden=mode!=='toTimestamp';result.textContent='Your result will appear here.'});document.getElementById('convertDate').onclick=()=>{const n=Number(document.getElementById('timestamp').value.trim());if(!Number.isFinite(n)){result.textContent='Please enter a valid timestamp.';return}const d=new Date(n*1000);result.textContent=Number.isNaN(d.getTime())?'Invalid timestamp.':d.toISOString()};document.getElementById('convertTs').onclick=()=>{const v=document.getElementById('date').value;if(!v){result.textContent='Please choose a date and time.';return}result.textContent=Math.floor(new Date(v).getTime()/1000).toString()};document.getElementById('copy').onclick=async()=>{if(result.textContent.includes('Your result'))return;await navigator.clipboard.writeText(result.textContent);document.getElementById('copy').textContent='Copied';setTimeout(()=>document.getElementById('copy').textContent='Copy Result',900)}})();</script>
<?php smarttoolz_tool_page_end(); ?>
