<?php declare(strict_types=1);
function anC(PDO $db,string $sql,array $p=[]):int{try{$q=$db->prepare($sql);$q->execute($p);return(int)$q->fetchColumn();}catch(Throwable){return 0;}}
function anR(PDO $db,string $sql,array $p=[]):array{try{$q=$db->prepare($sql);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){return[];}}
$live=anC($db,"SELECT COUNT(*) FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)");
$pv24=anC($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$uv24=anC($db,"SELECT COUNT(DISTINCT visitor_id) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$pv7=anC($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)");
$pv30=anC($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
$dl30=anC($db,"SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
$events30=anC($db,"SELECT COUNT(*) FROM analytics_events WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
$pages=anR($db,"SELECT page_path label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY page_path ORDER BY total DESC LIMIT 12");
$countries=anR($db,"SELECT COALESCE(NULLIF(country,''),'Unknown') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY country ORDER BY total DESC LIMIT 10");
$devices=anR($db,"SELECT COALESCE(NULLIF(device,''),'Unknown') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY device ORDER BY total DESC LIMIT 8");
$browsers=anR($db,"SELECT COALESCE(NULLIF(browser,''),'Unknown') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY browser ORDER BY total DESC LIMIT 8");
$refs=anR($db,"SELECT COALESCE(NULLIF(referrer,''),'Direct / None') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY referrer ORDER BY total DESC LIMIT 10");
$tools=anR($db,"SELECT tool_slug label,COUNT(*) total FROM tool_usage WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY tool_slug ORDER BY total DESC LIMIT 12");
$hour=[];for($i=23;$i>=0;$i--){$s=date('Y-m-d H:00:00',strtotime("-$i hours"));$e=date('Y-m-d H:00:00',strtotime("-".($i-1)." hours"));$hour[]=[$s,anC($db,'SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=? AND viewed_at<?',[$s,$e])];}$maxH=max(1,...array_map(fn($x)=>(int)$x[1],$hour));
function anBars(array $rows):void{$mx=max(1,(int)($rows[0]['total']??1));if(!$rows){echo '<div class="av4-empty">No data.</div>';return;}echo '<div class="av4-bars">';foreach($rows as $r){$p=min(100,(int)round((int)$r['total']/$mx*100));echo '<div class="av4-bar-row"><span>'.av4h($r['label']).'</span><div class="av4-track"><i style="width:'.$p.'%"></i></div><b>'.number_format((int)$r['total']).'</b></div>';}echo '</div>';}
?>
<div class="av4-page">
<div class="av4-stat-grid"><div class="av4-stat green"><b><?=number_format($live)?></b><span>Live now · 2 min</span></div><div class="av4-stat blue"><b><?=number_format($uv24)?></b><span>Unique visitors · 24h</span></div><div class="av4-stat purple"><b><?=number_format($pv24)?></b><span>Page views · 24h</span></div><div class="av4-stat orange"><b><?=number_format($pv7)?></b><span>Page views · 7d</span></div><div class="av4-stat"><b><?=number_format($pv30)?></b><span>Page views · 30d</span></div><div class="av4-stat"><b><?=number_format($dl30)?></b><span>Downloads · 30d</span></div><div class="av4-stat"><b><?=number_format($events30)?></b><span>Events · 30d</span></div></div>
<div class="av4-card"><div class="av4-head"><div><h2>📊 24-hour Traffic</h2><p>Hourly pageview volume from the analytics table.</p></div><div class="av4-chip green">LIVE DATA</div></div><div class="av4-chart"><?php foreach($hour as $x):?><div class="av4-chart-bar" style="height:<?=max(3,(int)round(($x[1]/$maxH)*100))?>%" title="<?=av4h($x[0])?> · <?=number_format($x[1])?> views"><span><?=number_format($x[1])?></span></div><?php endforeach;?></div></div>
<div class="av4-grid-2"><section class="av4-card"><div class="av4-head"><div><h2>Top Pages</h2><p>30-day ranking</p></div></div><?php anBars($pages);?></section><section class="av4-card"><div class="av4-head"><div><h2>Traffic Sources</h2><p>Referrer distribution</p></div></div><?php anBars($refs);?></section></div>
<div class="av4-grid-3"><section class="av4-card"><div class="av4-head"><div><h2>🌍 Countries</h2><p>Audience by country</p></div></div><?php anBars($countries);?></section><section class="av4-card"><div class="av4-head"><div><h2>💻 Devices</h2><p>Audience mix</p></div></div><?php anBars($devices);?></section><section class="av4-card"><div class="av4-head"><div><h2>🌐 Browsers</h2><p>Audience mix</p></div></div><?php anBars($browsers);?></section></div>
<div class="av4-grid-2"><section class="av4-card"><div class="av4-head"><div><h2>🛠️ Tool Usage</h2><p>Last 30 days</p></div></div><?php anBars($tools);?></section><section class="av4-card"><div class="av4-head"><div><h2>Reports</h2><p>Deep-dive views</p></div></div><div class="av4-links"><a class="primary" href="/analytics/advanced.php">Advanced Analytics ↗</a><a href="/analytics/">Full Analytics ↗</a><a href="/analytics/live.php">Realtime API ↗</a><a href="/analytics/resolve-geo.php">Geo Resolver ↗</a><a href="?tab=downloads">Downloads ↗</a></div><div class="av4-note"><b>Live:</b> <?=number_format($live)?> visitors active right now.</div></section></div>
</div>
