<?php
declare(strict_types=1);
function aa4c(PDO $db,string $sql,array $p=[]):int{try{$q=$db->prepare($sql);$q->execute($p);return(int)$q->fetchColumn();}catch(Throwable){return 0;}}
function aa4r(PDO $db,string $sql,array $p=[]):array{try{$q=$db->prepare($sql);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){return[];}}
$live=aa4c($db,"SELECT COUNT(*) FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)");
$pv24=aa4c($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$uv24=aa4c($db,"SELECT COUNT(DISTINCT visitor_id) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$pv30=aa4c($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
$dl30=aa4c($db,"SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
$pages=aa4r($db,"SELECT page_path label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY page_path ORDER BY total DESC LIMIT 12");
$countries=aa4r($db,"SELECT COALESCE(NULLIF(country,''),'Unknown') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY country ORDER BY total DESC LIMIT 10");
$devices=aa4r($db,"SELECT COALESCE(NULLIF(device,''),'Other') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY device ORDER BY total DESC LIMIT 8");
$browsers=aa4r($db,"SELECT COALESCE(NULLIF(browser,''),'Other') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY browser ORDER BY total DESC LIMIT 8");
$refs=aa4r($db,"SELECT COALESCE(NULLIF(referrer,''),'Direct / None') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY referrer ORDER BY total DESC LIMIT 10");
$tools=aa4r($db,"SELECT tool_slug label,COUNT(*) total FROM tool_usage WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY tool_slug ORDER BY total DESC LIMIT 10");
function aa4bars(array $rows):void{$mx=max(1,(int)($rows[0]['total']??1));echo '<div class="aa-bars">';foreach($rows as $r){$p=min(100,(int)round(((int)$r['total']/$mx)*100));echo '<div class="aa-row"><span>'.av4h($r['label']).'</span><div class="aa-track"><i style="width:'.$p.'%"></i></div><b>'.number_format((int)$r['total']).'</b></div>';};if(!$rows)echo '<div class="aa-empty">No data.</div>';echo '</div>';}
?>
<style>
.aa{display:grid;gap:12px}.aa-kpi{display:grid;grid-template-columns:repeat(6,1fr);gap:9px}.aa-card{background:#fff;border:1px solid #e6eaf1;border-radius:14px;padding:13px;box-shadow:0 8px 24px rgba(30,40,70,.035)}.aa-label{font-size:8px;color:#7c8797;font-weight:900}.aa-value{font-size:21px;font-weight:950;margin-top:4px}.aa-sub{font-size:8px;color:#8a94a4;margin-top:2px}.aa-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:12px}.aa-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.aa-head{margin-bottom:10px}.aa-head h2{margin:0;font-size:13px}.aa-head p{margin:3px 0 0;color:#8792a3;font-size:8px}.aa-bars{display:grid;gap:7px}.aa-row{display:grid;grid-template-columns:105px 1fr 37px;gap:7px;align-items:center}.aa-row span{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.aa-track{height:7px;background:#eef1f5;border-radius:999px;overflow:hidden}.aa-track i{display:block;height:100%;background:linear-gradient(90deg,#635bff,#978dff);border-radius:999px}.aa-row b{text-align:right;font-size:9px}.aa-live{padding:10px 12px;border:1px solid #e4efe9;border-radius:10px;background:#f5fcf8;color:#14905c;font-size:9px;font-weight:900}.aa-actions{display:flex;gap:7px;flex-wrap:wrap}.aa-actions a{padding:8px 10px;border-radius:9px;background:#f1f3f7;border:1px solid #e5e9f0;font-size:9px;font-weight:900;color:#4d5970}.aa-actions a.primary{background:#635bff;border-color:#635bff;color:#fff}.aa-empty{font-size:9px;color:#8a94a4;padding:15px 0}@media(max-width:1100px){.aa-kpi{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.aa-grid,.aa-grid3{grid-template-columns:1fr}.aa-kpi{grid-template-columns:repeat(2,1fr)}}
</style>
<div class="aa">
<div class="aa-kpi"><?php foreach([['Live Now',$live,'2 minute window'],['Views 24h',$pv24,'page views'],['Visitors 24h',$uv24,'unique'],['Views 30d',$pv30,'page views'],['Downloads 30d',$dl30,'tracked'],['Live Endpoint','1 sec','refresh'] ] as $x):?><div class="aa-card"><div class="aa-label"><?=av4h($x[0])?></div><div class="aa-value"><?=av4h($x[1])?></div><div class="aa-sub"><?=av4h($x[2])?></div></div><?php endforeach;?></div>
<div class="aa-grid"><section class="aa-card"><div class="aa-head"><h2>Top Pages</h2><p>30 day pageview ranking</p></div><?php aa4bars($pages);?></section><section class="aa-card"><div class="aa-head"><h2>Traffic Sources</h2><p>Referrer mix</p></div><?php aa4bars($refs);?></section></div>
<div class="aa-grid3"><section class="aa-card"><div class="aa-head"><h2>Countries</h2><p>Audience by country</p></div><?php aa4bars($countries);?></section><section class="aa-card"><div class="aa-head"><h2>Devices</h2><p>Device mix</p></div><?php aa4bars($devices);?></section><section class="aa-card"><div class="aa-head"><h2>Browsers</h2><p>Browser mix</p></div><?php aa4bars($browsers);?></section></div>
<div class="aa-grid"><section class="aa-card"><div class="aa-head"><h2>Tools</h2><p>Tool usage, last 30 days</p></div><?php aa4bars($tools);?></section><section class="aa-card"><div class="aa-head"><h2>Reports</h2><p>Open detailed views</p></div><div class="aa-actions"><a class="primary" href="/analytics/">Full Analytics ↗</a><a href="/analytics/advanced.php">Advanced ↗</a><a href="/analytics/live.php">Realtime API ↗</a><a href="/analytics/resolve-geo.php">Geo Resolver ↗</a><a href="?tab=downloads">Downloads ↗</a></div><div style="margin-top:10px" class="aa-live">● LIVE · <?=number_format($live)?> visitors currently active</div></section></div>
</div>
