<?php declare(strict_types=1);
function dC(PDO $db,string $sql):int{try{return(int)$db->query($sql)->fetchColumn();}catch(Throwable){return 0;}}
function dR(PDO $db,string $sql):array{try{return$db->query($sql)->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){return[];}}
$live=dC($db,"SELECT COUNT(*) FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)");
$users=dC($db,'SELECT COUNT(*) FROM creator_users');$views=dC($db,'SELECT COUNT(*) FROM analytics_pageviews');$todayViews=dC($db,'SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=CURDATE()');$todayVis=dC($db,'SELECT COUNT(DISTINCT visitor_id) FROM analytics_pageviews WHERE viewed_at>=CURDATE()');$downloads=dC($db,'SELECT COUNT(*) FROM smarttoolz_download_activity');$todayDl=dC($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=CURDATE()');$toolsUsed=dC($db,'SELECT COUNT(*) FROM tool_usage');$events=dC($db,'SELECT COUNT(*) FROM analytics_events');$ads=dC($db,'SELECT COUNT(*) FROM ads_settings WHERE enabled=1');
$pages=dR($db,"SELECT page_path label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY page_path ORDER BY total DESC LIMIT 8");$tools=dR($db,"SELECT tool_slug label,COUNT(*) total FROM tool_usage WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY tool_slug ORDER BY total DESC LIMIT 8");$countries=dR($db,"SELECT COALESCE(NULLIF(country,''),'Unknown') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY country ORDER BY total DESC LIMIT 8");$devices=dR($db,"SELECT COALESCE(NULLIF(device,''),'Other') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY device ORDER BY total DESC LIMIT 6");$browsers=dR($db,"SELECT COALESCE(NULLIF(browser,''),'Other') label,COUNT(*) total FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY browser ORDER BY total DESC LIMIT 6");
$liveRows=dR($db,"SELECT visitor_id,page_path,country,city,device,browser,last_seen FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE) ORDER BY last_seen DESC LIMIT 30");
function dBars(array $rows):void{$mx=max(1,(int)($rows[0]['total']??1));foreach($rows as $r){$p=min(100,(int)round((int)$r['total']/$mx*100));echo '<div class="av4-bar-row"><span>'.av4h($r['label']).'</span><div class="av4-track"><i style="width:'.$p.'%"></i></div><b>'.number_format((int)$r['total']).'</b></div>';}}
?>
<div class="av4-page">
<div class="av4-stat-grid"><div class="av4-stat green"><b><?=number_format($live)?></b><span>Live visitors now</span></div><div class="av4-stat blue"><b><?=number_format($todayVis)?></b><span>Visitors today</span></div><div class="av4-stat purple"><b><?=number_format($todayViews)?></b><span>Page views today</span></div><div class="av4-stat orange"><b><?=number_format($todayDl)?></b><span>Downloads today</span></div><div class="av4-stat"><b><?=number_format($users)?></b><span>Registered users</span></div><div class="av4-stat"><b><?=number_format($toolsUsed)?></b><span>Total tool uses</span></div><div class="av4-stat"><b><?=number_format($events)?></b><span>Events all time</span></div><div class="av4-stat"><b><?=number_format($ads)?></b><span>Active ads</span></div></div>
<div class="av4-grid-2"><section class="av4-card"><div class="av4-head"><div><h2>🟢 Live Visitors</h2><p>Fresh activity from the last 2 minutes.</p></div><span class="av4-chip green"><?=number_format($live)?> LIVE</span></div><div class="av4-live-list"><?php foreach($liveRows as $r):?><div class="av4-live-item"><span class="av4-live-dot"></span><div><b><?=av4h($r['page_path'])?></b><small><?=av4h(implode(' · ',array_filter([$r['country']??'Unknown',$r['city']??'',$r['device']??'',$r['browser']??''])))?></small></div><em>now</em></div><?php endforeach;if(!$liveRows):?><div class="av4-empty">No live visitors right now.</div><?php endif;?></div></section><section class="av4-card"><div class="av4-head"><div><h2>⚡ Quick Actions</h2><p>Common admin tasks.</p></div></div><div class="av4-links"><a class="primary" href="?tab=analytics">Analytics</a><a href="?tab=downloads">Downloads</a><a href="?tab=users">Users</a><a href="?tab=ads">Ads</a><a href="?tab=settings">Settings</a><a href="?tab=database">DB Explorer</a><a href="/analytics/advanced.php">Advanced Reports ↗</a></div><div class="av4-note"><b>All-time:</b> <?=number_format($views)?> page views · <?=number_format($downloads)?> downloads.</div></section></div>
<div class="av4-grid-3"><section class="av4-card"><div class="av4-head"><div><h2>Top Pages</h2><p>Last 30 days</p></div></div><div class="av4-bars"><?php dBars($pages);?></div></section><section class="av4-card"><div class="av4-head"><div><h2>Top Tools</h2><p>Last 30 days</p></div></div><div class="av4-bars"><?php dBars($tools);?></div></section><section class="av4-card"><div class="av4-head"><div><h2>Countries</h2><p>Last 30 days</p></div></div><div class="av4-bars"><?php dBars($countries);?></div></section></div>
<div class="av4-grid-2"><section class="av4-card"><div class="av4-head"><div><h2>Devices</h2><p>Audience mix</p></div></div><div class="av4-bars"><?php dBars($devices);?></div></section><section class="av4-card"><div class="av4-head"><div><h2>Browsers</h2><p>Audience mix</p></div></div><div class="av4-bars"><?php dBars($browsers);?></div></section></div></div>
