<?php
declare(strict_types=1);

function avdCount(PDO $db,string $sql,array $p=[]):int{try{$q=$db->prepare($sql);$q->execute($p);return(int)$q->fetchColumn();}catch(Throwable){return 0;}}
function avdRows(PDO $db,string $sql,array $p=[]):array{try{$q=$db->prepare($sql);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){return[];}}

$exists=false;
try{$q=$db->prepare("SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='smarttoolz_download_activity' LIMIT 1");$q->execute();$exists=(bool)$q->fetchColumn();}catch(Throwable){}

$total=$today=$guest=$logged=$tools=$week=$month=0;$rows=[];$toolBreakdown=[];
if($exists){
$total=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity');
$today=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=CURDATE()');
$week=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)');
$month=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)');
$guest=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE user_id IS NULL');
$logged=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE user_id IS NOT NULL');
$tools=avdCount($db,'SELECT COUNT(DISTINCT tool_slug) FROM smarttoolz_download_activity');
$rows=avdRows($db,'SELECT id,user_id,guest_id,tool_slug,page_url,ip_address,user_agent,downloaded_at FROM smarttoolz_download_activity ORDER BY id DESC LIMIT 500');
$toolBreakdown=avdRows($db,'SELECT tool_slug,COUNT(*) total FROM smarttoolz_download_activity GROUP BY tool_slug ORDER BY total DESC LIMIT 20');
}
?>
<style>
.dl-wrap{display:grid;gap:12px}.dl-kpis{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:9px}.dl-kpi{background:#fff;border:1px solid #e6eaf1;border-radius:13px;padding:12px}.dl-kpi b{display:block;font-size:20px}.dl-kpi span{font-size:9px;color:#7b8697}.dl-grid{display:grid;grid-template-columns:1.4fr .8fr;gap:12px}.dl-panel{background:#fff;border:1px solid #e6eaf1;border-radius:14px;padding:14px}.dl-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px}.dl-head h2{margin:0;font-size:14px}.dl-head p{margin:3px 0 0;color:#8792a3;font-size:9px}.dl-note{padding:10px;border-radius:9px;background:#fafbfe;border:1px solid #edf0f4;font-size:10px;color:#667184}.dl-bar{display:grid;grid-template-columns:110px 1fr 38px;gap:8px;align-items:center;margin:8px 0}.dl-bar span{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dl-track{height:7px;background:#eef1f5;border-radius:999px;overflow:hidden}.dl-fill{height:100%;background:linear-gradient(90deg,#635bff,#9388ff);border-radius:999px}.dl-num{text-align:right;font-size:9px;font-weight:900;color:#556174}.dl-table{overflow:auto;border:1px solid #e7ebf1;border-radius:10px}.dl-table table{width:100%;border-collapse:collapse;min-width:1050px;font-size:9px}.dl-table th,.dl-table td{padding:9px 8px;text-align:left;border-bottom:1px solid #edf0f4;vertical-align:top}.dl-table th{background:#fafbfe;color:#687487;font-size:8px;text-transform:uppercase;position:sticky;top:0}.dl-table tr:last-child td{border-bottom:0}.dl-tag{display:inline-flex;padding:4px 6px;border-radius:999px;background:#f0f2f7;color:#5f6b7e;font-weight:900}.dl-tag.g{background:#fff5df;color:#ae6c00}.dl-tag.u{background:#eeedff;color:#635bff}.dl-url{max-width:240px;color:#635bff;word-break:break-all}.dl-ua{max-width:300px;color:#768196;word-break:break-word}.dl-search{display:flex;gap:7px;margin-bottom:9px}.dl-search input{flex:1;border:1px solid #dfe4ec;border-radius:9px;padding:8px 10px;font-size:10px;outline:none}.dl-empty{text-align:center;padding:24px;color:#8490a1;font-size:10px}@media(max-width:1100px){.dl-kpis{grid-template-columns:repeat(4,1fr)}.dl-grid{grid-template-columns:1fr}}@media(max-width:650px){.dl-kpis{grid-template-columns:repeat(2,1fr)}}
</style>
<div class="dl-wrap">
<?php if(!$exists): ?><div class="dl-panel"><div class="dl-head"><div><h2>📥 Download Tracking</h2><p>The download activity table is not available yet.</p></div><span class="dl-tag g">MISSING</span></div><div class="dl-note">The expected table is <b>smarttoolz_download_activity</b>. Open the legacy tracking page once to install it automatically: <a href="/smart-toolz/admin/tracking.php" style="color:#635bff;font-weight:900">Initialize Download Tracking</a>.</div></div><?php else: ?>
<div class="dl-kpis"><div class="dl-kpi"><b><?=number_format($total)?></b><span>Total Downloads</span></div><div class="dl-kpi"><b><?=number_format($today)?></b><span>Today</span></div><div class="dl-kpi"><b><?=number_format($week)?></b><span>7 Days</span></div><div class="dl-kpi"><b><?=number_format($month)?></b><span>30 Days</span></div><div class="dl-kpi"><b><?=number_format($guest)?></b><span>Guest</span></div><div class="dl-kpi"><b><?=number_format($logged)?></b><span>Logged-in</span></div><div class="dl-kpi"><b><?=number_format($tools)?></b><span>Tools</span></div></div>
<div class="dl-grid"><section class="dl-panel"><div class="dl-head"><div><h2>Download Activity</h2><p>Latest 500 records · complete tracking details</p></div><span class="dl-tag u">LIVE TABLE</span></div><div class="dl-search"><input id="dlSearch" type="search" placeholder="Search user, guest, tool, page, IP, browser…"></div><div class="dl-table"><table id="dlTable"><thead><tr><th>ID</th><th>User / Guest</th><th>Tool</th><th>Page URL</th><th>IP</th><th>User Agent</th><th>Date / Time</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=av4h($r['id'])?></td><td><?php if(!empty($r['user_id'])): ?><span class="dl-tag u">User #<?=av4h($r['user_id'])?></span><?php elseif(!empty($r['guest_id'])): ?><span class="dl-tag g">Guest <?=av4h(substr((string)$r['guest_id'],0,18))?>…</span><?php else: ?>Unknown<?php endif; ?></td><td><?=av4h($r['tool_slug'])?></td><td class="dl-url"><?=av4h($r['page_url'])?></td><td><?=av4h($r['ip_address'])?></td><td class="dl-ua"><?=av4h($r['user_agent'])?></td><td><?=av4h($r['downloaded_at'])?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="7" class="dl-empty">No downloads recorded yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="dl-panel"><div class="dl-head"><div><h2>Downloads by Tool</h2><p>All-time tool ranking</p></div></div><?php $mx=max(1,(int)($toolBreakdown[0]['total']??1)); foreach($toolBreakdown as $r): ?><div class="dl-bar"><span><?=av4h($r['tool_slug'])?></span><div class="dl-track"><div class="dl-fill" style="width:<?=min(100,(int)round(((int)$r['total']/$mx)*100))?>%"></div></div><div class="dl-num"><?=number_format((int)$r['total'])?></div></div><?php endforeach; if(!$toolBreakdown): ?><div class="dl-empty">No tool download data.</div><?php endif; ?></section></div>
<?php endif; ?>
</div>
<script>(function(){const q=document.getElementById('dlSearch');const t=document.getElementById('dlTable');if(q&&t){q.addEventListener('input',()=>{const s=q.value.toLowerCase();t.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(s)?'':'none')})}})();</script>
