<?php declare(strict_types=1);
function uc4(PDO $db,string $sql):int{try{return(int)$db->query($sql)->fetchColumn();}catch(Throwable){return 0;}}
$users=[];
try{
 $users=$db->query("SELECT u.id,u.name,u.email,u.role,u.credits,u.daily_credits,u.plan,u.created_at,
 COALESCE(ev.event_count,0) event_count,COALESCE(ev.last_event,'') last_event,
 COALESCE(dl.download_count,0) download_count
 FROM creator_users u
 LEFT JOIN (SELECT user_id,COUNT(*) event_count,MAX(created_at) last_event FROM smarttoolz_analytics_events WHERE user_id IS NOT NULL GROUP BY user_id) ev ON ev.user_id=u.id
 LEFT JOIN (SELECT user_id,COUNT(*) download_count FROM smarttoolz_download_activity WHERE user_id IS NOT NULL GROUP BY user_id) dl ON dl.user_id=u.id
 INNER JOIN (SELECT LOWER(TRIM(email)) email_key,MAX(id) max_id FROM creator_users GROUP BY LOWER(TRIM(email))) uniq ON uniq.max_id=u.id
 ORDER BY u.id DESC LIMIT 500")->fetchAll(PDO::FETCH_ASSOC);
}catch(Throwable){
 try{$users=$db->query('SELECT id,name,email,role,credits,daily_credits,plan,created_at,0 event_count,\'\' last_event,0 download_count FROM creator_users ORDER BY id DESC LIMIT 500')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){}
}
$total=uc4($db,'SELECT COUNT(DISTINCT LOWER(TRIM(email))) FROM creator_users');
$admins=uc4($db,"SELECT COUNT(*) FROM (SELECT LOWER(TRIM(email)) e FROM creator_users WHERE role IN ('admin','superadmin') GROUP BY LOWER(TRIM(email))) x");
$credits=uc4($db,'SELECT COALESCE(SUM(credits),0) FROM creator_users');
$active=uc4($db,"SELECT COUNT(DISTINCT user_id) FROM smarttoolz_analytics_events WHERE user_id IS NOT NULL AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");
?>
<style>
.u4-wrap{display:grid;gap:12px}.u4-hero{background:linear-gradient(135deg,#111827,#24204b);color:#fff;border-radius:16px;padding:18px}.u4-hero h2{margin:0;font-size:18px}.u4-hero p{margin:5px 0 0;color:#c8c9d8;font-size:10px}.u4-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.u4-stat{background:#fff;border:1px solid #e6eaf1;border-radius:13px;padding:12px}.u4-stat b{display:block;font-size:20px}.u4-stat span{font-size:9px;color:#7b8697}.u4-card{background:#fff;border:1px solid #e6eaf1;border-radius:14px;padding:14px}.u4-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.u4-head h3{margin:0;font-size:14px}.u4-head p{margin:3px 0;color:#8792a3;font-size:9px}.u4-search{border:1px solid #dfe4ec;border-radius:9px;padding:8px 10px;font-size:10px;min-width:260px;outline:none}.u4-table{overflow:auto;border:1px solid #e7ebf1;border-radius:10px}.u4-table table{width:100%;border-collapse:collapse;min-width:1180px;font-size:9px}.u4-table th,.u4-table td{padding:9px 8px;text-align:left;border-bottom:1px solid #edf0f4;vertical-align:top}.u4-table th{background:#fafbfe;color:#687487;font-size:8px;text-transform:uppercase;position:sticky;top:0}.u4-table tr:last-child td{border-bottom:0}.u4-id{font-weight:900;color:#635bff}.u4-tag{display:inline-flex;padding:4px 6px;border-radius:999px;background:#f0f2f7;color:#5f6b7e;font-weight:900}.u4-tag.p{background:#eeedff;color:#635bff}.u4-activity{font-weight:900}.u4-muted{color:#8a94a4}.u4-btn{display:inline-block;text-decoration:none;border:0;border-radius:8px;padding:7px 9px;background:#111827;color:#fff;font-size:9px;font-weight:900}.u4-mini{display:flex;gap:5px;flex-wrap:wrap}.u4-mini select,.u4-mini input{border:1px solid #dfe4ec;border-radius:7px;padding:6px;font-size:9px}.u4-note{margin-top:9px;padding:9px;background:#fafbfe;border:1px solid #edf0f4;border-radius:9px;color:#697487;font-size:9px}@media(max-width:800px){.u4-stats{grid-template-columns:repeat(2,1fr)}.u4-head{align-items:stretch;flex-direction:column}.u4-search{min-width:0;width:100%;box-sizing:border-box}}
</style>
<div class="u4-wrap">
<div class="u4-hero"><h2>👤 USER INTELLIGENCE</h2><p>One account identity. One profile. Returning activity stays attached to the same user instead of creating duplicate rows.</p></div>
<div class="u4-stats"><div class="u4-stat"><b><?=number_format($total)?></b><span>Unique accounts</span></div><div class="u4-stat"><b><?=number_format($active)?></b><span>Active in 30 days</span></div><div class="u4-stat"><b><?=number_format($admins)?></b><span>Admin identities</span></div><div class="u4-stat"><b><?=number_format($credits)?></b><span>Credits held</span></div></div>
<div class="u4-card"><div class="u4-head"><div><h3>👥 Unified User Profiles</h3><p>Each email identity appears once; activity is aggregated from the event and download history.</p></div><input id="u4Search" class="u4-search" placeholder="Search name, email, ID, role…"></div>
<div class="u4-table"><table id="u4Table"><thead><tr><th>ID</th><th>User</th><th>Email</th><th>Role</th><th>Events</th><th>Downloads</th><th>Last Activity</th><th>Credits</th><th>Daily</th><th>Plan</th><th>Created</th><th>Manage</th></tr></thead><tbody>
<?php foreach($users as $r): ?><tr><td class="u4-id">#<?=av4h($r['id'])?></td><td><b><?=av4h($r['name'])?></b></td><td><?=av4h($r['email'])?></td><td><span class="u4-tag <?=in_array((string)$r['role'],['admin','superadmin'],true)?'p':''?>"><?=av4h($r['role'])?></span></td><td class="u4-activity"><?=number_format((int)$r['event_count'])?></td><td class="u4-activity"><?=number_format((int)$r['download_count'])?></td><td><?=av4h($r['last_event']?:'No tracked activity')?></td><td><?=number_format((int)$r['credits'])?></td><td><?=number_format((int)$r['daily_credits'])?></td><td><?=av4h($r['plan']??'—')?></td><td><?=av4h($r['created_at']??'')?></td><td><div class="u4-mini"><a class="u4-btn" href="/smart-toolz/admin/?tab=user-events&user_id=<?=av4h($r['id'])?>">🔎 Investigate</a><details><summary class="u4-btn">Edit</summary><form class="u4-mini" method="post" action="/smart-toolz/admin/admin-actions.php"><input type="hidden" name="action" value="user_role"><input type="hidden" name="back" value="users"><input type="hidden" name="csrf" value="<?=av4h(adminCsrf())?>"><input type="hidden" name="id" value="<?=av4h($r['id'])?>"><select name="role"><option value="user" <?=$r['role']==='user'?'selected':''?>>user</option><option value="admin" <?=$r['role']==='admin'?'selected':''?>>admin</option><option value="superadmin" <?=$r['role']==='superadmin'?'selected':''?>>superadmin</option></select><button class="u4-btn">Role</button></form><form class="u4-mini" method="post" action="/smart-toolz/admin/admin-actions.php"><input type="hidden" name="action" value="user_credits"><input type="hidden" name="back" value="users"><input type="hidden" name="csrf" value="<?=av4h(adminCsrf())?>"><input type="hidden" name="id" value="<?=av4h($r['id'])?>"><input name="credits" type="number" min="0" value="<?=av4h($r['credits'])?>"><input name="daily_credits" type="number" min="0" value="<?=av4h($r['daily_credits'])?>"><button class="u4-btn">Save</button></form></details></div></td></tr><?php endforeach; if(!$users): ?><tr><td colspan="12" class="u4-muted">No users found.</td></tr><?php endif; ?></tbody></table></div>
<div class="u4-note">JARVIS identity rule: registered users are grouped by normalized email for this view, while every event remains stored separately in the underlying history for investigation.</div></div></div>
<script>(function(){const i=document.getElementById('u4Search'),t=document.getElementById('u4Table');if(i&&t)i.oninput=()=>{const s=i.value.toLowerCase();t.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(s)?'':'none')};})();</script>