<?php declare(strict_types=1);
$selected=preg_replace('/[^a-f0-9]/i','',(string)($_GET['visitor']??''));
$users=[];$events=[];$selectedUser=null;$totalUsers=0;
try{
  $totalUsers=(int)$db->query("SELECT COUNT(*) FROM smarttoolz_analytics_users")->fetchColumn();
  $q=$db->query("SELECT u.*,COALESCE((SELECT COUNT(DISTINCT e.session_id) FROM smarttoolz_analytics_events e WHERE e.visitor_id=u.visitor_id AND e.session_id<>''),0) real_sessions FROM smarttoolz_analytics_users u ORDER BY u.last_seen DESC LIMIT 200");
  $users=$q->fetchAll(PDO::FETCH_ASSOC);
  if($selected!==''){
    $s=$db->prepare("SELECT * FROM smarttoolz_analytics_users WHERE visitor_id=? LIMIT 1");$s->execute([$selected]);$selectedUser=$s->fetch(PDO::FETCH_ASSOC);
    if($selectedUser){$s=$db->prepare("SELECT id,event_type,tool_slug,page_path,target,event_value,metadata,session_id,created_at FROM smarttoolz_analytics_events WHERE visitor_id=? ORDER BY id DESC LIMIT 1000");$s->execute([$selected]);$events=$s->fetchAll(PDO::FETCH_ASSOC);}
  }
}catch(Throwable $e){}
function ue(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function eventSentence(array $e):string{$t=(string)$e['event_type'];$target=trim((string)$e['target']);$tool=trim((string)$e['tool_slug']);$subject=$target!==''?$target:($tool!==''?$tool:(string)$e['page_path']);$map=['page_view'=>'opened a page','tool_open'=>'opened a tool','tool_use'=>'used a tool control','download'=>'downloaded a result/file','click'=>'clicked','input'=>'entered data into','change'=>'changed','submit'=>'submitted','scroll'=>'scrolled','focus'=>'focused','heartbeat'=>'is still active'];return 'Visitor '.strtoupper(substr((string)$e['session_id'],0,6)).' '.$map[$t]??$t.' '.$subject;}
?>
<style>
.ue{display:grid;gap:14px}.uehero{background:linear-gradient(135deg,#0f172a,#312e81);color:#fff;border-radius:22px;padding:22px}.uehero .tag{font-size:10px;letter-spacing:2px;opacity:.65}.uehero h2{margin:7px 0;font-size:25px}.uehero p{margin:0;color:#cbd5e1;font-size:13px;line-height:1.6;max-width:800px}.uebar{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.ueinput{flex:1;min-width:230px;padding:11px 13px;border:1px solid #dfe3ea;border-radius:11px}.uebtn{border:0;border-radius:11px;padding:11px 14px;font-weight:800;cursor:pointer;background:#111827;color:#fff}.uestats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.uestat,.uecard{background:#fff;border:1px solid rgba(127,127,127,.16);border-radius:16px;padding:14px}.uestat b{display:block;font-size:22px}.uestat span{font-size:10px;opacity:.55}.uegrid{display:grid;grid-template-columns:.85fr 1.5fr;gap:12px}.uelist{max-height:650px;overflow:auto;display:grid;gap:7px;margin-top:10px}.ueuser{display:block;text-decoration:none;color:inherit;border:1px solid #edf0f4;border-radius:12px;padding:11px;background:#fafbfc}.ueuser.active{border-color:#756df2;background:#f5f3ff}.ueuser strong{font-size:11px}.ueuser small{display:block;font-size:9px;opacity:.55;margin-top:4px}.uebadge{float:right;font-size:9px;background:#ecebff;padding:4px 7px;border-radius:20px}.uetimeline{max-height:650px;overflow:auto;margin-top:12px;padding-left:7px}.ueevent{position:relative;padding:9px 10px 9px 19px;border-left:2px solid #e5e7eb}.ueevent:before{content:'';position:absolute;left:-5px;top:13px;width:8px;height:8px;border-radius:50%;background:#756df2}.ueevent b{font-size:11px}.ueevent small{display:block;font-size:9px;opacity:.5;margin-top:3px}.uemeta{font-size:9px;opacity:.6;margin-top:4px;word-break:break-word}.emptyue{text-align:center;padding:35px;opacity:.5;font-size:11px}.back{font-size:11px;text-decoration:none}
@media(max-width:900px){.uegrid{grid-template-columns:1fr}.uestats{grid-template-columns:repeat(2,1fr)}}
</style>
<div class="ue">
<section class="uehero"><div class="tag">SMARTTOOLZ · USER EVENTS</div><h2>🕵️ One visitor. One permanent history.</h2><p>Har anonymous visitor ID ke andar uski lifetime event timeline rahegi. Visitor dobara aaye to naya profile nahi — wahi identity aur wahi history continue hogi, jab tak uska browser identity cookie retain karta hai.</p></section>
<form class="uebar" method="get"><input type="hidden" name="tab" value="user-events"><input class="ueinput" name="visitor" value="<?=ue($selected)?>" placeholder="Paste Visitor ID to investigate…"><button class="uebtn">🔎 Investigate</button><?php if($selected):?><a class="back" href="?tab=user-events">← All visitors</a><?php endif;?></form>
<section class="uestats"><div class="uestat"><b><?=number_format($totalUsers)?></b><span>Persistent visitor profiles</span></div><div class="uestat"><b><?=number_format(count($events))?></b><span>Loaded events<?= $selected?' · selected visitor':''?></span></div><div class="uestat"><b><?=number_format((int)($selectedUser['real_sessions']??0))?></b><span>Sessions<?= $selected?' · selected':''?></span></div><div class="uestat"><b><?=ue($selectedUser['last_tool']??'—')?></b><span>Last tool</span></div></section>
<div class="uegrid"><section class="uecard"><b>👤 VISITOR DIRECTORY</b><div class="uelist"><?php if(!$users):?><div class="emptyue">No visitor history yet.</div><?php else:foreach($users as $u):?><a class="ueuser <?=hash_equals($selected,(string)$u['visitor_id'])?'active':''?>" href="?tab=user-events&visitor=<?=ue($u['visitor_id'])?>"><span class="uebadge"><?=number_format((int)$u['event_count'])?> events</span><strong>ST-<?=ue(strtoupper(substr($u['visitor_id'],0,8)))?></strong><small>First: <?=ue($u['first_seen'])?> · Last: <?=ue($u['last_seen'])?></small><small><?=ue($u['device']?:'Unknown')?> · <?=ue($u['browser']?:'Unknown')?> · <?=ue($u['country']?:'Unknown')?></small></a><?php endforeach;endif;?></div></section>
<section class="uecard"><b>🧠 INVESTIGATION TIMELINE</b><?php if(!$selectedUser):?><div class="emptyue">Select a visitor from the directory to inspect their complete event history.</div><?php else:?><div style="margin-top:8px;font-size:12px"><strong>ST-<?=ue(strtoupper(substr($selectedUser['visitor_id'],0,8)))?></strong> · first seen <?=ue($selectedUser['first_seen'])?> · last seen <?=ue($selectedUser['last_seen'])?></div><div class="uetimeline"><?php if(!$events):?><div class="emptyue">No events recorded.</div><?php else:foreach($events as $e):?><div class="ueevent"><b><?=ue(eventSentence($e))?></b><small><?=ue($e['created_at'])?> · <?=ue($e['event_type'])?> · session <?=ue(substr((string)$e['session_id'],0,8))?></small><?php if($e['page_path']||$e['event_value']):?><div class="uemeta"><?=ue($e['page_path'])?><?= $e['event_value']?' · '.ue($e['event_value']):''?></div><?php endif;?></div><?php endforeach;endif;?></div><?php endif;?></section></div>
</div>
