<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
require_once __DIR__.'/saas/bootstrap.php';
$uid=saas_require_login();$db=saas_db();
$u=$db->prepare('SELECT name,email,avatar,credits,plan FROM creator_users WHERE id=? OR user_id=? LIMIT 1');$u->execute([$uid,$uid]);$user=$u->fetch(PDO::FETCH_ASSOC) ?: ['name'=>'User','email'=>'','credits'=>0,'plan'=>'free'];
$w=saas_wallet($uid);$plans=$db->query('SELECT * FROM saas_plans WHERE active=1 ORDER BY price_inr')->fetchAll(PDO::FETCH_ASSOC);
$ref=$db->prepare('SELECT code,commission_inr FROM saas_referrals WHERE referrer_id=? ORDER BY id DESC LIMIT 1');$ref->execute([$uid]);$r=$ref->fetch(PDO::FETCH_ASSOC);if(!$r){$code='ST'.strtoupper(substr(hash('sha256',(string)$uid),0,8));$db->prepare('INSERT INTO saas_referrals(referrer_id,referred_id,code,commission_inr) VALUES(?,?,?,0)')->execute([$uid,$uid,$code]);$r=['code'=>$code,'commission_inr'=>0];}
require_once __DIR__.'/header.php';
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My SmartToolz Account</title><style>body{margin:0;background:#f7f9fd;color:#172033;font-family:Inter,system-ui,Arial,sans-serif}.wrap{width:min(1100px,calc(100% - 28px));margin:35px auto 70px}.hero,.card{background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 14px 40px rgba(20,30,70,.05)}.hero{padding:30px}.hero h1{margin:0 0 6px;font-size:34px}.muted{color:#707b8e}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:16px}.card{padding:22px}.num{font-size:29px;font-weight:900;margin:7px 0}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:16px}.plan{padding:22px;border:1px solid #e5e9f0;border-radius:18px;background:#fff}.plan.pro{border-color:#8b82ff;box-shadow:0 12px 30px #635bff18}.plan h3{margin:0}.price{font-size:27px;font-weight:900;margin:12px 0}.btn{display:inline-block;border:0;border-radius:11px;background:#635bff;color:#fff;padding:11px 15px;font-weight:800;text-decoration:none}.btn.alt{background:#eef0f5;color:#273147}.ref{display:flex;gap:8px}.ref input{flex:1;padding:12px;border:1px solid #dfe4ec;border-radius:10px}.note{font-size:12px;color:#707b8e;line-height:1.6}@media(max-width:800px){.grid,.plans{grid-template-columns:1fr}.hero{padding:23px}}
</style></head><body><main class="wrap"><section class="hero"><h1>Welcome, <?=htmlspecialchars((string)$user['name'],ENT_QUOTES,'UTF-8')?> 👋</h1><p class="muted">Your SmartToolz account, credits, plan and referral earnings.</p></section><div class="grid"><div class="card"><div class="muted">Current plan</div><div class="num"><?=htmlspecialchars(ucfirst((string)$user['plan']))?></div></div><div class="card"><div class="muted">Tool / AI credits</div><div class="num"><?=number_format((int)$user['credits'])?></div></div><div class="card"><div class="muted">Referral earnings</div><div class="num">₹<?=number_format((float)$r['commission_inr'],2)?></div></div></div><section class="card" style="margin-top:16px"><h2>Earn with SmartToolz</h2><p class="muted">Invite users. When an invited user purchases a paid plan, your referral commission is recorded in your wallet.</p><div class="ref"><input id="ref" readonly value="https://smarttoolz.in/smart-toolz/?ref=<?=urlencode($r['code'])?>"><button class="btn" onclick="navigator.clipboard.writeText(document.getElementById('ref').value)">Copy Link</button></div><p class="note">Referral commission: 20% of eligible paid plan purchases. Payouts are subject to verification and the configured payout method.</p></section><h2 style="margin:34px 0 8px">Choose a plan</h2><p class="muted">Free stays available. Pro and Creator remove ads and provide higher limits.</p><div class="plans"><?php foreach($plans as $p): ?><div class="plan <?=$p['slug']==='pro'?'pro':''?>"><h3><?=htmlspecialchars($p['name'])?></h3><div class="price">₹<?=number_format((float)$p['price_inr'],0)?> <small class="muted">/month</small></div><p class="muted"><?=number_format((int)$p['monthly_credits'])?> credits/month</p><?php if($p['slug']===$user['plan']): ?><span class="btn alt">Current plan</span><?php elseif((float)$p['price_inr']>0): ?><a class="btn" href="/smart-toolz/saas/upgrade.php?plan=<?=urlencode($p['slug'])?>">Upgrade</a><?php else: ?><span class="btn alt">Free</span><?php endif; ?></div><?php endforeach;?></div><p class="note" style="margin-top:18px">Payments are processed only after the site owner configures the payment gateway keys. No secret payment key is exposed to the browser.</p></main><?php require_once __DIR__.'/footer.php'; ?></body></html>
