<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
$isLoggedIn=!empty($_SESSION['user_id']);
$displayName=(string)($_SESSION['user_name']??'');
$displayAvatar=(string)($_SESSION['user_avatar']??'');
$initial=strtoupper(substr(trim($displayName?:'U'),0,1));
$headerCredits=null;
if($isLoggedIn){try{require_once $_SERVER['DOCUMENT_ROOT'].'/smart-toolz/saas/bootstrap.php';$hs=saas_db()->prepare('SELECT credits FROM creator_users WHERE id=? LIMIT 1');$hs->execute([(int)$_SESSION['user_id']]);if($hr=$hs->fetch(PDO::FETCH_ASSOC))$headerCredits=(int)$hr['credits'];}catch(Throwable $e){$headerCredits=null;}}
$slug=basename($_SERVER['SCRIPT_NAME']??'tool.php','.php');
$toolTitle=preg_replace('/[-_]+/',' ',strtolower($slug));$toolTitle=ucwords($toolTitle?:'Online Tool');
?><header class="site-header"><nav class="navbar"><a class="logo" href="/smart-toolz/"><span class="logo-icon">🛠️</span><span>SmartToolz</span></a><button class="menu-button" type="button" aria-label="Menu" aria-expanded="false">☰</button><div class="nav-links"><a href="/smart-toolz/">Home</a><a href="/smart-toolz/tool.php">All Tools</a><?php if($isLoggedIn): ?><a href="/smart-toolz/account.php" class="nav-dashboard">My Account</a><a href="/creator-ai/">AI Dashboard</a><span class="credit-pill" title="1 generation = 1 credit">⚡ <b id="headerCredits"><?= $headerCredits===null?'—':number_format($headerCredits) ?></b> credits</span><a class="nav-user" href="/smart-toolz/account.php"><?php if($displayAvatar!==''): ?><img src="<?=htmlspecialchars($displayAvatar,ENT_QUOTES,'UTF-8')?>" alt=""><?php else: ?><span><?=htmlspecialchars($initial,ENT_QUOTES,'UTF-8')?></span><?php endif; ?><strong><?=htmlspecialchars($displayName?:'Account',ENT_QUOTES,'UTF-8')?></strong></a><a href="/creator-ai/auth/logout.php">Logout</a><?php else: ?><a class="login-btn" href="/creator-ai/auth/google-login.php">Login with Google</a><?php endif; ?></div></nav></header>
<?php if($slug!=='index' && $slug!=='account' && $slug!=='tool'): ?><section class="tool-seo-intro"><div><span class="tool-free-badge">FREE ONLINE TOOL</span><h2>Free Online <?=htmlspecialchars($toolTitle,ENT_QUOTES,'UTF-8')?></h2><p>SmartToolz <?=htmlspecialchars($toolTitle,ENT_QUOTES,'UTF-8')?> helps you complete this task quickly and easily. Use the tool online without unnecessary setup.</p></div><div class="how-use"><h3>How to Use</h3><ol><li>Enter, upload or select your data.</li><li>Choose your options and click the main action button.</li><li>Review the result and download or copy it.</li></ol><small>⚡ 1 generation/use = 1 credit for logged-in users.</small></div></section><?php endif; ?>
<style>.site-header{position:sticky;top:0;z-index:1000;background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border-bottom:1px solid #e7eaf1}.navbar{width:min(1400px,calc(100% - 28px));min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:22px;position:relative}.logo{display:flex;align-items:center;gap:10px;color:#172033;font-size:21px;font-weight:850;text-decoration:none;white-space:nowrap}.logo-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;color:#fff;background:linear-gradient(135deg,#635bff,#916cff)}.nav-links{display:flex;align-items:center;gap:14px}.nav-links a{color:#596477;font-size:13px;font-weight:700;text-decoration:none}.nav-links a:hover{color:#635bff}.nav-dashboard{color:#635bff!important}.login-btn{padding:10px 15px;border-radius:11px;color:#fff!important;background:#635bff}.credit-pill{display:inline-flex;align-items:center;gap:5px;padding:8px 11px;border:1px solid #ddd9ff;border-radius:999px;background:#f5f3ff;color:#635bff;font-size:12px;font-weight:800;white-space:nowrap}.nav-user{display:flex;align-items:center;gap:7px!important}.nav-user img,.nav-user>span{width:30px;height:30px;border-radius:50%;object-fit:cover}.nav-user>span{display:grid;place-items:center;background:#635bff;color:#fff;font-size:12px}.menu-button{display:none;border:0;background:transparent;font-size:27px;cursor:pointer}.tool-seo-intro{width:min(1400px,calc(100% - 30px));margin:24px auto 0;padding:24px 26px;display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,1fr);gap:22px;background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 10px 35px rgba(20,30,70,.045)}.tool-free-badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#eeedff;color:#635bff;font-size:11px;font-weight:900;letter-spacing:.4px}.tool-seo-intro h2{margin:9px 0 7px;font-size:26px;line-height:1.15}.tool-seo-intro p{margin:0;color:#707b8e;font-size:13px;line-height:1.7}.how-use{padding:18px;background:#f7f8fc;border:1px solid #e8eaf1;border-radius:15px}.how-use h3{margin:0 0 8px;font-size:16px}.how-use ol{margin:0 0 10px;padding-left:20px;color:#596477;font-size:12px;line-height:1.8}.how-use small{color:#635bff;font-weight:800}@media(max-width:900px){.nav-links{gap:9px}.tool-seo-intro{grid-template-columns:1fr}}@media(max-width:820px){.menu-button{display:block}.nav-links{display:none;position:absolute;top:64px;left:0;right:0;padding:12px;flex-direction:column;align-items:stretch;background:#fff;border:1px solid #e7eaf1;border-top:0;border-radius:0 0 16px 16px;box-shadow:0 18px 35px #141c321a}.nav-links.open{display:flex}.nav-links a,.credit-pill{padding:10px}.nav-user{justify-content:flex-start}.tool-seo-intro{width:calc(100% - 20px);padding:20px}} </style>
<script>(()=>{const b=document.querySelector('.menu-button'),n=document.querySelector('.nav-links');if(b&&n)b.onclick=()=>{const o=n.classList.toggle('open');b.setAttribute('aria-expanded',o?'true':'false')};const r=new URLSearchParams(location.search).get('ref');if(r&&/^[A-Za-z0-9_-]{4,40}$/.test(r)){document.cookie='smarttoolz_ref='+encodeURIComponent(r)+';path=/;max-age=2592000;Secure;SameSite=Lax';}<?php if($isLoggedIn): ?>fetch('/smart-toolz/saas/claim-ref.php',{credentials:'same-origin'}).catch(()=>{});const creditState={busy:false,bypass:false};const generationPattern=/^(generate|create|process|calculate|convert|compress|merge|split|make|encode|decode|resize|crop|rotate|remove|format|optimize)/i;async function smartToolzSpendCredit(button){if(creditState.busy||creditState.bypass)return true;creditState.busy=true;const old=button.textContent;button.dataset.creditBusy='1';button.textContent='Checking credits…';try{const body=new URLSearchParams({tool:(location.pathname.split('/').pop()||'tool').replace(/\.php$/,'')});const res=await fetch('/smart-toolz/saas/credits.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},credentials:'same-origin',body});if(res.status===401){location.href='/creator-ai/auth/google-login.php';return false}const data=await res.json();if(!data.ok){alert(data.message||'No credits remaining. Upgrade your plan to continue.');location.href='/smart-toolz/account.php';return false}const c=document.getElementById('headerCredits');if(c&&typeof data.credits!=='undefined')c.textContent=Number(data.credits).toLocaleString();button.textContent='Starting…';creditState.bypass=true;button.click();creditState.bypass=false;return false}catch(e){alert('Could not verify your credits. Please try again.');return false}finally{creditState.busy=false;button.dataset.creditBusy='';if(document.body.contains(button)&&button.textContent!=='Starting…')button.textContent=old}}document.addEventListener('click',e=>{const btn=e.target.closest?.('button');if(!btn||creditState.bypass||btn.dataset.creditBusy==='1')return;const label=(btn.textContent||'').trim();if(generationPattern.test(label)){e.preventDefault();e.stopImmediatePropagation();smartToolzSpendCredit(btn)}},true);<?php endif; ?>})();</script>
