<?php
declare(strict_types=1);
ini_set('display_errors','0');
error_reporting(0);
$tracker = $_SERVER['DOCUMENT_ROOT'].'/analytics/tracker.php';
if (is_file($tracker)) require_once $tracker;
function faviconIcoAd(string $key): void {
    try {
        if (function_exists('db')) {
            $pdo=db(); $stmt=$pdo->prepare('SELECT enabled, ad_code FROM ads_settings WHERE ad_key=? LIMIT 1');
            $stmt->execute([$key]); $row=$stmt->fetch(PDO::FETCH_ASSOC);
            if ($row && (int)$row['enabled']===1 && trim((string)($row['ad_code']??''))!=='') echo $row['ad_code'];
        }
    } catch(Throwable $e) {}
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Favicon ICO Generator Online | SmartToolz</title>
<meta name="description" content="Create a real favicon.ico file from an image, emoji or text. Generate multiple icon sizes and download one ready-to-use ICO file in your browser.">
<meta name="robots" content="index,follow">
<style>
*{box-sizing:border-box;margin:0;padding:0}body{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;background:#f6f8fc;color:#172033;line-height:1.5}a{text-decoration:none;color:inherit}button,input,select,textarea{font:inherit}
.site-header{position:sticky;top:0;z-index:1000;background:rgba(255,255,255,.96);backdrop-filter:blur(14px);border-bottom:1px solid #e5e9f0}.navbar{width:calc(100% - 20px);max-width:none;min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between;padding:0 10px}.logo{display:flex;align-items:center;gap:10px;font-size:21px;font-weight:800}.logo-icon{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;color:#fff;background:linear-gradient(135deg,#635bff,#916cff)}.nav-links{display:flex;gap:28px}.nav-links a{color:#596477;font-size:14px;font-weight:600}
.page-layout{width:100%;max-width:none;margin:0;padding:24px 24px 60px;display:block}.tool-content{width:100%;min-width:0}.ad-slot{width:100%;min-height:10px;margin:0 auto 20px;padding:5px;display:flex;align-items:center;justify-content:center;text-align:center;overflow:hidden}.desktop-ad{display:flex}.mobile-ad{display:none}
.tool-header{width:100%;margin-bottom:18px;padding:28px 25px;background:#fff;border:1px solid #e5e9f0;border-radius:20px;text-align:left;box-shadow:0 8px 30px rgba(30,35,80,.035)}.header-inner{display:flex;align-items:center;gap:18px}.tool-icon{width:70px;height:70px;flex:0 0 70px;display:grid;place-items:center;border-radius:17px;background:linear-gradient(135deg,#7b3fe4,#8d5cf5);color:#fff;font-size:34px;box-shadow:0 10px 22px rgba(99,91,255,.18)}.tool-title{flex:1}.tool-title h1{font-size:clamp(28px,4vw,40px);line-height:1.08;letter-spacing:-1.5px}.tool-title h1 span{color:#635bff}.tool-title p{max-width:900px;margin:9px 0 0;color:#707b8e;font-size:14px}.header-badges{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.pill{padding:7px 11px;border-radius:50px;background:#eef0f5;color:#635bff;font-size:11px;font-weight:800}.pill.green{background:#e5faef;color:#13a25b}
.generator-card{width:100%;padding:20px;background:#fff;border:1px solid #e5e9f0;border-radius:20px;box-shadow:0 15px 45px rgba(30,35,80,.055)}.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:0;margin-bottom:18px;background:#eef0f5;border-radius:11px;padding:3px}.tab{height:44px;border:0;background:transparent;color:#4d5768;border-radius:9px;cursor:pointer;font-weight:800;font-size:13px}.tab.active{background:#fff;color:#635bff;box-shadow:0 2px 8px rgba(30,35,80,.08)}
.main-grid{display:grid;grid-template-columns:minmax(300px,380px) minmax(0,1fr);gap:22px;align-items:start}.preview-panel{padding:16px;background:#fafbff;border:1px solid #e5e9f0;border-radius:17px}.preview-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:11px}.preview-heading strong{font-size:15px}.preview-heading span{font-size:10px;color:#8a93a5}.checker{width:100%;aspect-ratio:1;border-radius:15px;border:1px solid #dfe3eb;background-color:#fff;background-image:linear-gradient(45deg,#eef0f5 25%,transparent 25%),linear-gradient(-45deg,#eef0f5 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#eef0f5 75%),linear-gradient(-45deg,transparent 75%,#eef0f5 75%);background-size:28px 28px;background-position:0 0,0 14px,14px -14px,-14px 0;display:grid;place-items:center;overflow:hidden}.checker canvas{width:92%;height:92%;image-rendering:auto}.upload-row{margin-top:12px}.file-label{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;min-height:44px;padding:10px 14px;border:1px dashed #cbd1dd;border-radius:10px;background:#fff;color:#4d5768;font-size:12px;font-weight:800;cursor:pointer}.file-label:hover{border-color:#635bff;color:#635bff;background:#f8f7ff}.file-label input{display:none}.file-name{margin-top:7px;text-align:center;color:#8a93a5;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.controls-panel{padding:0}.source-card,.sizes,.code-card{padding:15px;background:#fafbff;border:1px solid #e5e9f0;border-radius:14px;margin-bottom:12px}.source-card>label,.field>label,.sizes-title,.code-card label{display:block;margin-bottom:7px;color:#707b8e;font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.55px}.source-options{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.source-option{position:relative}.source-option input{position:absolute;opacity:0;pointer-events:none}.source-option span{display:flex;align-items:center;justify-content:center;gap:6px;height:42px;padding:7px;border:1px solid #dfe3eb;border-radius:9px;background:#fff;color:#4d5768;font-size:11px;font-weight:800;cursor:pointer}.source-option input:checked+span{border-color:#635bff;background:#eeedff;color:#635bff;box-shadow:0 0 0 2px rgba(99,91,255,.08)}.source-input{margin-top:10px}.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:11px}.field{padding:13px;background:#fafbff;border:1px solid #e5e9f0;border-radius:13px}.field.full{grid-column:1/-1}.field input[type=text],.field input[type=color],.field select{width:100%;height:40px;padding:7px 10px;border:1px solid #d7dbea;border-radius:9px;background:#fff;color:#172033;outline:none}.field input[type=color]{padding:3px;cursor:pointer}.field input[type=text]:focus,.field select:focus{border-color:#8d87ff;box-shadow:0 0 0 3px rgba(99,91,255,.1)}.range-row{display:flex;align-items:center;gap:10px}.range-row input{width:100%;accent-color:#635bff}.range-value{min-width:43px;text-align:center;padding:6px 7px;border-radius:8px;background:#eef0f5;color:#635bff;font-size:10px;font-weight:800}.hidden{display:none!important}
.size-list{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.size-actions{display:flex;gap:6px;margin-bottom:9px}.mini{border:0;background:transparent;color:#635bff;font-size:10px;font-weight:800;cursor:pointer}.size-check{display:flex;align-items:center;justify-content:center;gap:5px;min-height:37px;padding:7px;border:1px solid #dfe3eb;border-radius:8px;background:#fff;color:#4d5768;font-size:10px;font-weight:750;cursor:pointer}.size-check:has(input:checked){border-color:#c9c5ff;background:#f4f3ff;color:#635bff}.size-check input{accent-color:#635bff;width:13px;height:13px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:13px}.btn{min-height:45px;padding:10px 17px;border:0;border-radius:10px;cursor:pointer;font-size:12px;font-weight:850}.primary{flex:1;background:linear-gradient(135deg,#635bff,#7c6cf2);color:#fff;box-shadow:0 8px 18px rgba(99,91,255,.18)}.secondary{background:#eef0f5;color:#3f4858}.status{min-height:17px;margin-top:8px;text-align:center;color:#707b8e;font-size:10px}.code-card{margin-top:0}.code-row{display:flex;gap:8px}.code-card textarea{width:100%;min-height:62px;padding:9px;border:1px solid #d7dbea;border-radius:8px;background:#fff;color:#3f4858;font:10px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;resize:vertical}.copy{height:38px;padding:0 12px;border:0;border-radius:8px;background:#eef0f5;color:#4d5768;font-size:10px;font-weight:850;cursor:pointer;white-space:nowrap}
.info{width:100%;margin-top:18px;padding:22px;background:#fff;border:1px solid #e5e9f0;border-radius:17px}.info h2{font-size:20px;margin-bottom:7px}.info h3{font-size:15px;margin:16px 0 6px}.info p,.info li{color:#707b8e;font-size:12px;line-height:1.7}.info ul{padding-left:19px}.feature-row{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:13px}.feature{padding:12px;background:#fafbff;border:1px solid #e5e9f0;border-radius:11px}.feature strong{display:block;font-size:11px}.feature span{display:block;margin-top:3px;color:#8a93a5;font-size:10px}footer{padding:32px 20px;background:#151827;color:#fff;text-align:center}footer p{margin-top:5px;color:#aeb5c5;font-size:11px}
@media(max-width:1000px){.main-grid{grid-template-columns:300px 1fr}.size-list{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.header-inner{align-items:flex-start}.header-badges{display:none}.main-grid{grid-template-columns:1fr}.preview-panel{max-width:420px;margin:auto;width:100%}.feature-row{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.navbar{min-height:64px}.nav-links{display:none}.page-layout{padding:15px 10px 40px}.desktop-ad{display:none}.mobile-ad{display:flex}.tool-header{padding:20px 16px}.header-inner{gap:12px}.tool-icon{width:54px;height:54px;flex-basis:54px;font-size:26px;border-radius:13px}.tool-title h1{font-size:27px}.tool-title p{font-size:11px}.generator-card{padding:12px}.tab{font-size:11px;height:40px}.fields{grid-template-columns:1fr}.field.full{grid-column:auto}.source-options{grid-template-columns:1fr}.size-list{grid-template-columns:repeat(2,1fr)}.actions{flex-direction:column}.primary,.secondary{width:100%}.code-row{flex-direction:column}.copy{width:100%}}
</style>
</head>
<body>
<?php require_once dirname(__DIR__).'/header.php'; ?>
<div class="page-layout"><main class="tool-content">
<div class="desktop-ad ad-slot"><?php faviconIcoAd('top_desktop'); ?></div><div class="mobile-ad ad-slot"><?php faviconIcoAd('top_mobile'); ?></div>
<section class="tool-header"><div class="header-inner"><div class="tool-icon">🧩</div><div class="tool-title"><h1>Favicon <span>ICO Generator</span></h1><p>Create a real favicon.ico file from an image, emoji or text. Pack multiple icon sizes into one ready-to-use ICO file.</p></div><div class="header-badges"><span class="pill green">Free</span><span class="pill">Fast</span><span class="pill">Multi-Size ICO</span><span class="pill">No Upload</span></div></div></section>
<section class="generator-card"><div class="tabs"><button class="tab active" data-source="image" type="button">🖼️ From Image</button><button class="tab" data-source="emoji" type="button">😊 From Emoji</button><button class="tab" data-source="text" type="button">T From Text</button></div>
<div class="main-grid"><div class="preview-panel"><div class="preview-heading"><strong>Preview</strong><span id="previewSize">256 × 256</span></div><div class="checker"><canvas id="preview" width="256" height="256"></canvas></div><div class="upload-row" id="uploadRow"><label class="file-label">📁 Choose Image<input id="file" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/svg+xml"></label><div class="file-name" id="fileName">PNG, JPG, JPEG, WEBP, GIF or SVG · max 5 MB</div></div></div>
<div class="controls-panel"><div class="source-card"><label>ICO SOURCE</label><div class="source-options"><label class="source-option"><input type="radio" name="source" value="image" checked><span>🖼️ Image</span></label><label class="source-option"><input type="radio" name="source" value="emoji"><span>😊 Emoji</span></label><label class="source-option"><input type="radio" name="source" value="text"><span>T Text</span></label></div><div class="source-input hidden" id="emojiInput"><div class="field"><label>Emoji</label><input id="emoji" type="text" value="🚀" maxlength="8"></div></div><div class="source-input hidden" id="textInput"><div class="field"><label>Text / Letter</label><input id="text" type="text" value="S" maxlength="3"></div></div></div>
<div class="fields"><div class="field"><label>Background Color</label><input id="bg" type="color" value="#FFFFFF"></div><div class="field"><label>Text / Icon Color</label><input id="fg" type="color" value="#1537D4"></div><div class="field"><label>Corner Radius</label><div class="range-row"><input id="radius" type="range" min="0" max="50" value="10"><span class="range-value" id="radiusVal">10%</span></div></div><div class="field"><label>Padding</label><div class="range-row"><input id="padding" type="range" min="0" max="40" value="10"><span class="range-value" id="paddingVal">10%</span></div></div><div class="field full"><label>Image Fit</label><select id="fit"><option value="contain">Contain (Recommended)</option><option value="cover">Cover</option></select></div></div>
<div class="sizes"><div class="sizes-title">ICO Sizes</div><div class="size-actions"><button class="mini" id="selectAll" type="button">Select all</button><button class="mini" id="clearAll" type="button">Clear all</button></div><div class="size-list"><label class="size-check"><input class="size" type="checkbox" value="16" checked>16×16</label><label class="size-check"><input class="size" type="checkbox" value="24" checked>24×24</label><label class="size-check"><input class="size" type="checkbox" value="32" checked>32×32</label><label class="size-check"><input class="size" type="checkbox" value="48" checked>48×48</label><label class="size-check"><input class="size" type="checkbox" value="64" checked>64×64</label><label class="size-check"><input class="size" type="checkbox" value="96" checked>96×96</label><label class="size-check"><input class="size" type="checkbox" value="128" checked>128×128</label><label class="size-check"><input class="size" type="checkbox" value="256" checked>256×256</label></div></div>
<div class="actions"><button class="btn primary" id="generate" type="button">⚡ Generate favicon.ico</button><button class="btn secondary" id="reset" type="button">Reset</button></div><div class="status" id="status">Ready to generate your ICO file.</div></div></div>
<div class="code-card"><label>HTML</label><div class="code-row"><textarea id="snippet" readonly>&lt;link rel="icon" href="/favicon.ico" type="image/x-icon"&gt;</textarea><button class="copy" id="copySnippet" type="button">Copy Code</button></div></div>
</section>
<section class="info"><h2>Favicon ICO Generator</h2><p>Generate a standard <strong>favicon.ico</strong> containing multiple icon resolutions in one file. Everything is processed in your browser, so your source image does not need to be uploaded to a server.</p><h3>What you can create</h3><ul><li>ICO files from PNG, JPG, JPEG, WEBP, GIF or SVG images.</li><li>Emoji-based and text/letter favicons with live background, color, radius and padding controls.</li><li>One multi-size favicon.ico ready to place in your website root.</li></ul><div class="feature-row"><div class="feature"><strong>Multi-size ICO</strong><span>16px to 256px</span></div><div class="feature"><strong>Live Preview</strong><span>Changes update instantly</span></div><div class="feature"><strong>Private</strong><span>Browser-side processing</span></div><div class="feature"><strong>One Click</strong><span>Download favicon.ico</span></div></div><h3>How to use</h3><p>Choose an image, emoji or text, adjust the design, select the ICO sizes you need, then click <strong>Generate favicon.ico</strong>. Add the downloaded file to your site's root and use the provided HTML link tag.</p></section>
</main></div><footer><strong>SmartToolz</strong><p>Free online tools for developers, creators and everyday tasks.</p></footer>
<script>
(()=>{
const $=id=>document.getElementById(id); let image=null,source='image',icoBlob=null;
function hexToRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]}
function drawCanvas(size){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');const bg=$('bg').value,fg=$('fg').value,p=+ $('padding').value/100,r=+ $('radius').value/100;x.clearRect(0,0,size,size);const rr=size*r/2;x.save();x.beginPath();x.moveTo(rr,0);x.arcTo(size,0,size,size,rr);x.arcTo(size,size,0,size,rr);x.arcTo(0,size,0,0,rr);x.arcTo(0,0,size,0,rr);x.closePath();x.clip();x.fillStyle=bg;x.fillRect(0,0,size,size);const inset=size*p;const w=size-inset*2;
if(source==='image'&&image){const iw=image.naturalWidth||image.width,ih=image.naturalHeight||image.height;const contain=$('fit').value==='contain';let dw=w,dh=w;if(contain){const s=Math.min(w/iw,w/ih);dw=iw*s;dh=ih*s}else{const s=Math.max(w/iw,w/ih);dw=iw*s;dh=ih*s}x.drawImage(image,(size-dw)/2,(size-dh)/2,dw,dh)}else{x.fillStyle=fg;x.textAlign='center';x.textBaseline='middle';const val=source==='emoji'?($('emoji').value||'😊'):($('text').value||'S');x.font=(source==='emoji'?Math.round(w*.78):Math.round(w*.62))+'px Arial, sans-serif';x.fillText(val,size/2,size/2+size*.025)}x.restore();return c}
function refresh(){const c=drawCanvas(256);$('preview').getContext('2d').clearRect(0,0,256,256);$('preview').getContext('2d').drawImage(c,0,0);$('radiusVal').textContent=$('radius').value+'%';$('paddingVal').textContent=$('padding').value+'%'}
function setSource(s){source=s;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.source===s));$('uploadRow').classList.toggle('hidden',s!=='image');$('emojiInput').classList.toggle('hidden',s!=='emoji');$('textInput').classList.toggle('hidden',s!=='text');refresh()}
function blobFromCanvas(c){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNG failed')),'image/png'))}
async function makeIco(){const sizes=[...document.querySelectorAll('.size:checked')].map(x=>+x.value);if(!sizes.length)throw new Error('Select at least one size.');const pngs=[];for(const s of sizes)pngs.push(await blobFromCanvas(drawCanvas(s)));const bufs=await Promise.all(pngs.map(b=>b.arrayBuffer()));const header=6+16*sizes.length;let total=header+bufs.reduce((n,b)=>n+b.byteLength,0);const out=new Uint8Array(total),dv=new DataView(out.buffer);dv.setUint16(0,0,true);dv.setUint16(2,1,true);dv.setUint16(4,sizes.length,true);let off=header;bufs.forEach((b,i)=>{const s=sizes[i];const w=s===256?0:s;let p=6+i*16;out[p]=w;out[p+1]=w;out[p+2]=0;out[p+3]=0;dv.setUint16(p+4,1,true);dv.setUint16(p+6,32,true);dv.setUint32(p+8,b.byteLength,true);dv.setUint32(p+12,off,true);out.set(new Uint8Array(b),off);off+=b.byteLength});return new Blob([out],{type:'image/x-icon'})}
$('file').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){$('fileName').textContent='File is larger than 5 MB.';e.target.value='';return}const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{image=im;URL.revokeObjectURL(u);$('fileName').textContent=f.name;setSource('image')};im.onerror=()=>{URL.revokeObjectURL(u);$('fileName').textContent='Unable to read this image.'};im.src=u});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setSource(b.dataset.source)));document.querySelectorAll('input[name=source]').forEach(r=>r.addEventListener('change',()=>setSource(r.value)));['emoji','text','bg','fg','radius','padding','fit'].forEach(id=>$(id).addEventListener('input',refresh));$('fit').addEventListener('change',refresh);
$('generate').addEventListener('click',async()=>{const btn=$('generate');btn.disabled=true;$('status').textContent='Generating favicon.ico...';try{icoBlob=await makeIco();const a=document.createElement('a');a.href=URL.createObjectURL(icoBlob);a.download='favicon.ico';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('status').textContent='favicon.ico generated and downloaded successfully.'}catch(e){$('status').textContent=e.message||'Could not generate favicon.ico.'}btn.disabled=false});
$('reset').addEventListener('click',()=>{image=null;$('file').value='';$('fileName').textContent='PNG, JPG, JPEG, WEBP, GIF or SVG · max 5 MB';$('bg').value='#FFFFFF';$('fg').value='#1537D4';$('radius').value=10;$('padding').value=10;$('fit').value='contain';$('emoji').value='🚀';$('text').value='S';document.querySelectorAll('.size').forEach(x=>x.checked=true);setSource('image');$('status').textContent='Ready to generate your ICO file.'});
$('selectAll').addEventListener('click',()=>document.querySelectorAll('.size').forEach(x=>x.checked=true));$('clearAll').addEventListener('click',()=>document.querySelectorAll('.size').forEach(x=>x.checked=false));$('copySnippet').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('snippet').value);$('copySnippet').textContent='Copied!';setTimeout(()=>$('copySnippet').textContent='Copy Code',1200)}catch(e){$('snippet').select();document.execCommand('copy')}});refresh();
})();
</script></body></html>