<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free Text Diff Checker Online','description'=>'Compare two text blocks and find added, removed and changed lines instantly in your browser with SmartToolz.','url'=>'https://smarttoolz.in/tools/text-diff/'];
smarttoolz_tool_page_start($tool);
?>
<main class="diff-page"><section class="tool-head"><span class="eyebrow">TEXT DIFF CHECKER</span><h1>Compare Two Texts</h1><p>Paste two versions of your text and instantly see what changed.</p></section><section class="diff-card"><div class="inputs"><label>Original text<textarea id="a" placeholder="Paste original text..."></textarea></label><label>New text<textarea id="b" placeholder="Paste new text..."></textarea></label></div><div class="actions"><button id="compare" class="primary">Compare Texts</button><button id="clear">Clear</button></div><div class="summary" id="summary">Enter two texts to compare.</div><div class="result" id="result"></div></section><section class="info-grid"><article><h2>Useful for</h2><p>Reviewing edits, comparing documents, checking content revisions and spotting changes in code or plain text.</p></article><article><h2>Private comparison</h2><p>Your text is compared locally in your browser and does not need to be uploaded to SmartToolz.</p></article></section></main>
<style>.diff-page{width:min(1000px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.diff-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.inputs{display:grid;grid-template-columns:1fr 1fr;gap:14px}.inputs label{display:grid;gap:7px;color:#344054;font-size:11px;font-weight:800}.inputs textarea{box-sizing:border-box;width:100%;min-height:250px;padding:14px;border:1px solid #dfe3eb;border-radius:12px;background:#fcfdff;color:#263052;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;resize:vertical;outline:0}.inputs textarea:focus{border-color:#8d80ff}.actions{display:flex;gap:9px;margin:14px 0}.actions button{padding:10px 16px;border:1px solid #dfe3eb;border-radius:10px;background:#fff;color:#344054;font-size:10px;font-weight:900;cursor:pointer}.actions .primary{border:0;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff}.summary{padding:11px 13px;border-radius:10px;background:#f5f6fa;color:#667085;font-size:10px}.result{margin-top:12px;border:1px solid #e7eaf0;border-radius:12px;overflow:auto}.line{display:grid;grid-template-columns:42px 1fr;min-width:500px;font:12px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace}.line-num{padding:3px 8px;text-align:right;color:#98a2b3;background:#f7f8fa;border-right:1px solid #e7eaf0}.line-text{padding:3px 10px;white-space:pre-wrap;word-break:break-word}.added{background:#effaf3}.removed{background:#fff2f2}.added .line-num{color:#17834b}.removed .line-num{color:#c53b3b}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:700px){.diff-page{width:calc(100% - 20px)}.diff-card{padding:16px}.inputs{grid-template-columns:1fr}.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{const a=document.getElementById('a'),b=document.getElementById('b'),result=document.getElementById('result'),summary=document.getElementById('summary');function compare(){const A=a.value.split('\n'),B=b.value.split('\n');const m=A.length,n=B.length,dp=Array.from({length:m+1},()=>new Array(n+1).fill(0));for(let i=m-1;i>=0;i--)for(let j=n-1;j>=0;j--)dp[i][j]=A[i]===B[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,added=0,removed=0,out=[];while(i<m&&j<n){if(A[i]===B[j]){out.push(['',i+1,A[i]]);i++;j++}else if(dp[i+1][j]>=dp[i][j+1]){out.push(['removed',i+1,'− '+A[i]]);removed++;i++}else{out.push(['added',j+1,'+ '+B[j]]);added++;j++}}while(i<m){out.push(['removed',i+1,'− '+A[i]]);removed++;i++}while(j<n){out.push(['added',j+1,'+ '+B[j]]);added++;j++}result.innerHTML=out.map(x=>`<div class="line ${x[0]}"><span class="line-num">${x[1]}</span><span class="line-text"></span></div>`).join('');result.querySelectorAll('.line-text').forEach((el,k)=>el.textContent=out[k][2]);summary.textContent=`${added} added · ${removed} removed · ${m===n&&added===0&&removed===0?'No changes':'comparison complete'}`};document.getElementById('compare').onclick=compare;document.getElementById('clear').onclick=()=>{a.value='';b.value='';result.innerHTML='';summary.textContent='Enter two texts to compare.'}})();</script>
<?php smarttoolz_tool_page_end(); ?>
