<?php
if (!defined('ABSPATH')) exit;
function smarttoolz_blog_assets(){ $v=wp_get_theme()->get('Version'); wp_enqueue_style('smarttoolz-blog-style',get_stylesheet_uri(),array(),$v); wp_enqueue_style('smarttoolz-blog-brand',get_template_directory_uri().'/brand.css',array('smarttoolz-blog-style'),$v.'.2'); }
add_action('wp_enqueue_scripts','smarttoolz_blog_assets');
function smarttoolz_blog_setup(){ load_theme_textdomain('smarttoolz-blog',get_template_directory().'/languages'); add_theme_support('title-tag'); add_theme_support('post-thumbnails'); add_theme_support('custom-logo',array('height'=>80,'width'=>280,'flex-height'=>true,'flex-width'=>true)); add_theme_support('custom-background',array('default-color'=>'f6f7ff')); add_theme_support('automatic-feed-links'); add_theme_support('responsive-embeds'); add_theme_support('align-wide'); add_theme_support('editor-styles'); add_editor_style('style.css'); add_theme_support('html5',array('search-form','comment-form','comment-list','gallery','caption','style','script')); add_theme_support('post-formats',array('aside','image','quote','video','audio','link')); register_nav_menus(array('primary'=>__('Primary Menu','smarttoolz-blog'),'footer'=>__('Footer Menu','smarttoolz-blog'))); }
add_action('after_setup_theme','smarttoolz_blog_setup');
function smarttoolz_blog_widgets(){ $c=array('before_widget'=>'<section id="%1$s" class="widget %2$s">','after_widget'=>'</section>','before_title'=>'<h3 class="widget-title">','after_title'=>'</h3>'); register_sidebar(array_merge($c,array('name'=>__('Blog Sidebar','smarttoolz-blog'),'id'=>'sidebar-1','description'=>__('Main sidebar for posts, pages and archives.','smarttoolz-blog')))); foreach(array('1'=>'Footer One','2'=>'Footer Two','3'=>'Footer Three') as $id=>$name) register_sidebar(array_merge($c,array('name'=>__($name,'smarttoolz-blog'),'id'=>'footer-'.$id))); }
add_action('widgets_init','smarttoolz_blog_widgets');
function smarttoolz_blog_excerpt_length($l){return 26;} add_filter('excerpt_length','smarttoolz_blog_excerpt_length',999); function smarttoolz_blog_excerpt_more($m){return '…';} add_filter('excerpt_more','smarttoolz_blog_excerpt_more');
function smarttoolz_blog_demo_image($slug){$x=array('technology'=>'https://picsum.photos/seed/smarttoolz-technology/1200/800','design'=>'https://picsum.photos/seed/smarttoolz-design/1200/800','culture'=>'https://picsum.photos/seed/smarttoolz-culture/1200/800','work'=>'https://picsum.photos/seed/smarttoolz-work/1200/800');return $x[$slug]??$x['technology'];}
function smarttoolz_blog_set_featured_image($post_id,$url,$title){ if(has_post_thumbnail($post_id))return; require_once ABSPATH.'wp-admin/includes/file.php'; require_once ABSPATH.'wp-admin/includes/media.php'; require_once ABSPATH.'wp-admin/includes/image.php'; $tmp=download_url($url,20); if(is_wp_error($tmp))return; $file=array('name'=>sanitize_title($title).'.jpg','tmp_name'=>$tmp); $attachment=media_handle_sideload($file,$post_id,$title); if(is_wp_error($attachment)){@unlink($tmp);return;} set_post_thumbnail($post_id,$attachment); }
function smarttoolz_blog_repair_featured_images(){ if(get_option('smarttoolz_blog_featured_images_repaired'))return; $posts=get_posts(array('post_type'=>'post','post_status'=>'publish','numberposts'=>-1)); foreach($posts as $post){ if(has_post_thumbnail($post->ID))continue; $cats=get_the_category($post->ID); $slug=$cats?$cats[0]->slug:'technology'; smarttoolz_blog_set_featured_image($post->ID,smarttoolz_blog_demo_image($slug),$post->post_title); } update_option('smarttoolz_blog_featured_images_repaired',1,false); }
add_action('init','smarttoolz_blog_repair_featured_images',25);
function smarttoolz_blog_seed_demo_content(){ if(get_option('smarttoolz_blog_demo_seeded'))return; $cs=array('Technology','Design','Culture','Work');$ids=array();foreach($cs as $n){$t=term_exists($n,'category');if(!$t)$t=wp_insert_term($n,'category');if(!is_wp_error($t))$ids[$n]=(int)(is_array($t)?$t['term_id']:$t);} foreach(array('WordPress','Productivity','Creativity','Business','Web Design','Habits') as $n)if(!term_exists($n,'post_tag'))wp_insert_term($n,'post_tag'); $ps=array(array('Small tools, big impact','Technology','Practical workflows that help people work smarter without adding complexity.',array('WordPress','Productivity'),'technology'),array('Designing for clarity','Design','Good editorial design gets out of the way and lets the story do the talking.',array('Web Design','Creativity'),'design'),array('Why simple ideas travel further','Culture','A thoughtful look at making complex subjects approachable and memorable.',array('Creativity','Business'),'culture'),array('A better way to build a habit','Work','Small systems, consistent practice and a little room for imperfection.',array('Productivity','Habits'),'work')); foreach($ps as $p){$e=get_page_by_title($p[0],OBJECT,'post');$img=smarttoolz_blog_demo_image($p[4]);$c='<p>'.esc_html($p[2]).'</p><p>This demo article is editable from WordPress Admin. The theme renders posts, categories, tags, images and widgets dynamically.</p>';if(!$e)$id=wp_insert_post(array('post_title'=>$p[0],'post_content'=>$c,'post_status'=>'publish','post_type'=>'post','post_author'=>get_current_user_id()?:1,'post_category'=>isset($ids[$p[1]])?array($ids[$p[1]]):array()));else{$id=$e->ID;} if($id&&!is_wp_error($id)){wp_set_post_tags($id,$p[3]); smarttoolz_blog_set_featured_image($id,$img,$p[0]);}}
 $pages=array('About'=>'<h2>About SmartToolz Journal</h2><p>A clean editorial space for useful ideas, stories and practical knowledge.</p>','Contact'=>'<h2>Contact</h2><p>Add your email, social links or contact form here from WordPress.</p>','Privacy Policy'=>'<h2>Privacy Policy</h2><p>Replace this demo copy with your site privacy policy.</p>');foreach($pages as $t=>$c)if(!get_page_by_title($t,OBJECT,'page'))wp_insert_post(array('post_title'=>$t,'post_content'=>$c,'post_status'=>'publish','post_type'=>'page','post_author'=>get_current_user_id()?:1)); update_option('smarttoolz_blog_demo_seeded',1,false); }
add_action('init','smarttoolz_blog_seed_demo_content',20);
function smarttoolz_blog_seed_menu(){if(has_nav_menu('primary')||get_option('smarttoolz_blog_menu_seeded'))return;$m=wp_get_nav_menu_object('SmartToolz Blog Menu');$mid=$m?$m->term_id:wp_create_nav_menu('SmartToolz Blog Menu');if(is_wp_error($mid))return;$items=array(home_url('/'));foreach(get_categories(array('hide_empty'=>true,'number'=>6)) as $cat)$items[]=get_category_link($cat->term_id);foreach(array('About','Contact') as $t){$p=get_page_by_title($t,OBJECT,'page');if($p)$items[]=get_permalink($p->ID);}foreach($items as $u){$ok=false;foreach(wp_get_nav_menu_items($mid)?:array() as $i)if($i->url===$u)$ok=true;if(!$ok)wp_update_nav_menu_item($mid,0,array('menu-item-title'=>wp_strip_all_tags(urldecode(basename(trim($u,'/'))?:'Home')),'menu-item-url'=>$u,'menu-item-status'=>'publish'));}$loc=get_theme_mod('nav_menu_locations',array());$loc['primary']=(int)$mid;set_theme_mod('nav_menu_locations',$loc);update_option('smarttoolz_blog_menu_seeded',1,false);}
add_action('init','smarttoolz_blog_seed_menu',30);

/* Full WordPress Customizer controls for the Blog theme. Site Identity remains untouched. */
function smarttoolz_blog_customize_register($wp_customize){
 $wp_customize->add_panel('smarttoolz_blog_design',array('title'=>__('SmartToolz Blog Design','smarttoolz-blog'),'priority'=>30,'description'=>__('Control the visual design without editing code.','smarttoolz-blog')));
 $wp_customize->add_section('smarttoolz_blog_colors',array('title'=>__('Colors','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 foreach(array('accent'=>'Accent Color','accent_soft'=>'Accent Soft','ink'=>'Text / Ink','paper'=>'Page Background','surface'=>'Card Background','dark'=>'Dark Sections','line'=>'Borders') as $id=>$label){$wp_customize->add_setting('smarttoolz_'.$id,array('default'=>array('accent'=>'e64b2e','accent_soft'=>'ffe9e2','ink'=>'111318','paper'=>'f7f6f2','surface'=>'ffffff','dark'=>'17191f','line'=>'deded8')[$id],'sanitize_callback'=>'sanitize_hex_color'));$wp_customize->add_control(new WP_Customize_Color_Control($wp_customize,'smarttoolz_'.$id,array('label'=>__($label,'smarttoolz-blog'),'section'=>'smarttoolz_blog_colors')));}
 $wp_customize->add_section('smarttoolz_blog_layout',array('title'=>__('Layout & Header','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 $wp_customize->add_setting('smarttoolz_header_sticky',array('default'=>true,'sanitize_callback'=>'rest_sanitize_boolean'));$wp_customize->add_control('smarttoolz_header_sticky',array('label'=>__('Sticky Header','smarttoolz-blog'),'section'=>'smarttoolz_blog_layout','type'=>'checkbox'));
 $wp_customize->add_setting('smarttoolz_show_search',array('default'=>true,'sanitize_callback'=>'rest_sanitize_boolean'));$wp_customize->add_control('smarttoolz_show_search',array('label'=>__('Show Header Search','smarttoolz-blog'),'section'=>'smarttoolz_blog_layout','type'=>'checkbox'));
 $wp_customize->add_setting('smarttoolz_sidebar_width',array('default'=>300,'sanitize_callback'=>'absint'));$wp_customize->add_control('smarttoolz_sidebar_width',array('label'=>__('Sidebar Width (px)','smarttoolz-blog'),'section'=>'smarttoolz_blog_layout','type'=>'range','input_attrs'=>array('min'=>220,'max'=>420,'step'=>10)));
 $wp_customize->add_setting('smarttoolz_content_gap',array('default'=>70,'sanitize_callback'=>'absint'));$wp_customize->add_control('smarttoolz_content_gap',array('label'=>__('Content / Sidebar Gap (px)','smarttoolz-blog'),'section'=>'smarttoolz_blog_layout','type'=>'range','input_attrs'=>array('min'=>20,'max'=>120,'step'=>5)));
 $wp_customize->add_section('smarttoolz_blog_hero',array('title'=>__('Hero Section','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 foreach(array('hero_label'=>'Hero Label','hero_title'=>'Hero Title','hero_text'=>'Hero Description') as $id=>$label){$wp_customize->add_setting('smarttoolz_'.$id,array('default'=>array('hero_label'=>'SmartToolz Journal','hero_title'=>'Ideas for a smarter digital life.','hero_text'=>'A modern editorial theme for essays, guides, product stories and ideas — powered entirely by WordPress.')[$id],'sanitize_callback'=>'sanitize_textarea_field'));$wp_customize->add_control('smarttoolz_'.$id,array('label'=>__($label,'smarttoolz-blog'),'section'=>'smarttoolz_blog_hero','type'=>'textarea'));}
 $wp_customize->add_setting('smarttoolz_hero_posts',array('default'=>3,'sanitize_callback'=>'absint'));$wp_customize->add_control('smarttoolz_hero_posts',array('label'=>__('Hero Featured Posts','smarttoolz-blog'),'section'=>'smarttoolz_blog_hero','type'=>'number','input_attrs'=>array('min'=>1,'max'=>6)));
 $wp_customize->add_section('smarttoolz_blog_cards',array('title'=>__('Cards & Typography','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 $wp_customize->add_setting('smarttoolz_card_radius',array('default'=>18,'sanitize_callback'=>'absint'));$wp_customize->add_control('smarttoolz_card_radius',array('label'=>__('Card Radius (px)','smarttoolz-blog'),'section'=>'smarttoolz_blog_cards','type'=>'range','input_attrs'=>array('min'=>0,'max'=>40,'step'=>1)));
 $wp_customize->add_setting('smarttoolz_story_image_height',array('default'=>156,'sanitize_callback'=>'absint'));$wp_customize->add_control('smarttoolz_story_image_height',array('label'=>__('Story Image Height (px)','smarttoolz-blog'),'section'=>'smarttoolz_blog_cards','type'=>'range','input_attrs'=>array('min'=>100,'max'=>300,'step'=>5)));
 $wp_customize->add_setting('smarttoolz_body_font',array('default'=>'Inter,ui-sans-serif,system-ui,sans-serif','sanitize_callback'=>'sanitize_text_field'));$wp_customize->add_control('smarttoolz_body_font',array('label'=>__('Body Font Stack','smarttoolz-blog'),'section'=>'smarttoolz_blog_cards','type'=>'text'));
 $wp_customize->add_section('smarttoolz_blog_footer',array('title'=>__('Footer & SmartToolz Branding','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 foreach(array('footer_brand'=>'SmartToolz','footer_text'=>'SmartToolz — useful tools, ideas and digital products.','footer_copyright'=>'© %year% SmartToolz. All rights reserved.') as $id=>$default){$wp_customize->add_setting('smarttoolz_'.$id,array('default'=>$default,'sanitize_callback'=>'sanitize_textarea_field'));$wp_customize->add_control('smarttoolz_'.$id,array('label'=>__($id==='footer_brand'?'Branding Text':($id==='footer_text'?'Footer Description':'Copyright Text'),'smarttoolz-blog'),'section'=>'smarttoolz_blog_footer','type'=>'textarea'));}
 $wp_customize->add_section('smarttoolz_blog_social',array('title'=>__('Social Links','smarttoolz-blog'),'panel'=>'smarttoolz_blog_design'));
 foreach(array('facebook'=>'Facebook','instagram'=>'Instagram','youtube'=>'YouTube','twitter'=>'X / Twitter','linkedin'=>'LinkedIn') as $id=>$label){$wp_customize->add_setting('smarttoolz_social_'.$id,array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control('smarttoolz_social_'.$id,array('label'=>$label.' URL','section'=>'smarttoolz_blog_social','type'=>'url'));}
}
add_action('customize_register','smarttoolz_blog_customize_register');

function smarttoolz_blog_customizer_css(){
 $map=array('accent'=>'#e64b2e','accent_soft'=>'#ffe9e2','ink'=>'#111318','paper'=>'#f7f6f2','surface'=>'#fff','dark'=>'#17191f','line'=>'#deded8');
 foreach($map as $k=>$v){$c=get_theme_mod('smarttoolz_'.$k,$v);if($c)$map[$k]=$c;}
 $sticky=get_theme_mod('smarttoolz_header_sticky',true);$search=get_theme_mod('smarttoolz_show_search',true);$sw=absint(get_theme_mod('smarttoolz_sidebar_width',300));$gap=absint(get_theme_mod('smarttoolz_content_gap',70));$radius=absint(get_theme_mod('smarttoolz_card_radius',18));$ih=absint(get_theme_mod('smarttoolz_story_image_height',156));$font=get_theme_mod('smarttoolz_body_font','Inter,ui-sans-serif,system-ui,sans-serif');
 $css=':root{--accent:'.$map['accent'].';--accent-soft:'.$map['accent_soft'].';--ink:'.$map['ink'].';--paper:'.$map['paper'].';--surface:'.$map['surface'].';--dark:'.$map['dark'].';--line:'.$map['line'].';--sidebar-width:'.$sw.'px;--content-gap:'.$gap.'px;--card-radius:'.$radius.'px;--body-font:'.$font.'}.body{font-family:var(--body-font)}body{font-family:var(--body-font)}.content-with-sidebar,.archive-layout{grid-template-columns:minmax(0,1fr) var(--sidebar-width);gap:var(--content-gap)}.single-grid{grid-template-columns:minmax(0,820px) var(--sidebar-width);gap:var(--content-gap)}.hero-card{border-radius:var(--card-radius)}.story-media{height:'.$ih.'px;border-radius:calc(var(--card-radius) * .7)}';
 if(!$sticky)$css.='.header{position:relative}';
 if(!$search)$css.='.header-search{display:none!important}';
 wp_add_inline_style('smarttoolz-blog-style',$css);
}
add_action('wp_enqueue_scripts','smarttoolz_blog_customizer_css',20);

function smarttoolz_blog_customizer_preview(){ if(is_customize_preview()) smarttoolz_blog_customizer_css(); }
add_action('wp_footer','smarttoolz_blog_customizer_preview');
