<?php get_header(); ?>
<main id="primary" class="site-main">
<?php $featured = new WP_Query(array('posts_per_page'=>3,'post_status'=>'publish','ignore_sticky_posts'=>false)); ?>
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><?php echo esc_html(get_bloginfo('name')); ?></span><h1><?php echo esc_html(get_bloginfo('description') ?: __('Ideas for a smarter digital life.', 'smarttoolz-blog')); ?></h1><p><?php esc_html_e('A modern editorial theme for essays, guides, product stories and ideas — powered entirely by WordPress.', 'smarttoolz-blog'); ?></p><div class="hero-actions"><a class="button button-dark" href="#latest">Explore stories</a><?php $about=get_page_by_title('About',OBJECT,'page'); if($about): ?><a class="text-link" href="<?php echo esc_url(get_permalink($about)); ?>">About →</a><?php endif; ?></div></div>
<div class="hero-stack"><?php if($featured->have_posts()): while($featured->have_posts()):$featured->the_post(); ?><article class="hero-card <?php echo has_post_thumbnail()?'has-image':''; ?>"><?php if(has_post_thumbnail()): ?><a class="hero-card-media" href="<?php the_permalink(); ?>"><?php the_post_thumbnail('large'); ?></a><?php endif; ?><div class="hero-card-copy"><span class="mini-meta"><?php $cats=get_the_category();if($cats) echo esc_html($cats[0]->name); ?> · <?php echo esc_html(get_the_date('M j')); ?></span><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2></div></article><?php endwhile; wp_reset_postdata(); else: ?><article class="hero-card"><div class="hero-card-copy"><span class="mini-meta">Getting started</span><h2><?php esc_html_e('Publish your first story', 'smarttoolz-blog'); ?></h2><p><?php esc_html_e('Create a post in WordPress and it will appear here automatically.', 'smarttoolz-blog'); ?></p></div></article><?php endif; ?></div></div></section>

<div class="container content-with-sidebar" id="latest"><div class="content-column"><section class="stories"><div class="section-heading"><div><span class="eyebrow">The latest</span><h2><?php esc_html_e('Stories worth your time', 'smarttoolz-blog'); ?></h2></div><span class="count"><?php echo esc_html(wp_count_posts()->publish); ?> published</span></div>
<?php $posts=new WP_Query(array('posts_per_page'=>7,'post_status'=>'publish','ignore_sticky_posts'=>true,'paged'=>max(1,get_query_var('paged')))); if($posts->have_posts()):while($posts->have_posts()):$posts->the_post(); ?><article <?php post_class('story-card'); ?>><a class="story-media" href="<?php the_permalink(); ?>"><?php if(has_post_thumbnail()):the_post_thumbnail('medium_large');else: ?><span class="story-placeholder"><span><?php echo esc_html(strtoupper(mb_substr(get_the_title(),0,1))); ?></span></span><?php endif; ?></a><div class="story-body"><div class="story-top"><span class="category-label"><?php the_category(', '); ?></span><time datetime="<?php echo esc_attr(get_the_date('c')); ?>"><?php echo esc_html(get_the_date('M j, Y')); ?></time></div><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),27)); ?></p><div class="story-bottom"><span>By <?php the_author(); ?></span><span><?php echo esc_html(ceil(str_word_count(wp_strip_all_tags(get_the_content()))/200)); ?> min read</span></div></div></article><?php endwhile; ?><div class="pagination-wrap"><?php echo wp_kses_post(paginate_links(array('total'=>$posts->max_num_pages,'current'=>max(1,get_query_var('paged')),'type'=>'list'))); ?></div><?php else: ?><div class="empty-state"><strong>No stories yet.</strong><p>Create your first post from Posts → Add New.</p></div><?php endif; wp_reset_postdata(); ?></section></div><?php get_sidebar(); ?></div>

<section class="topics"><div class="container"><div class="section-heading"><div><span class="eyebrow">Explore</span><h2>Browse by topic</h2></div><span class="count">Categories & tags</span></div><div class="topic-grid"><?php foreach(get_categories(array('hide_empty'=>true,'number'=>8,'orderby'=>'count','order'=>'DESC')) as $cat): ?><a class="topic-card" href="<?php echo esc_url(get_category_link($cat->term_id)); ?>"><span><?php echo esc_html(str_pad((string)$cat->count,2,'0',STR_PAD_LEFT)); ?></span><strong><?php echo esc_html($cat->name); ?></strong><small>Read the latest →</small></a><?php endforeach; ?></div><div class="tag-row"><?php wp_tag_cloud(array('smallest'=>11,'largest'=>16,'unit'=>'px','number'=>24,'orderby'=>'count','order'=>'DESC')); ?></div></div></section>
</main><?php get_footer(); ?>