<?php get_header(); ?>
<?php if(get_theme_mod('smarttoolz_reading_progress',true)): ?><div class="reading-progress" aria-hidden="true"></div><?php endif; ?>
<main class="single-wrap"><div class="container single-grid"><div><article <?php post_class('single-post'); ?>><header class="single-header">
<?php if(get_theme_mod('smarttoolz_show_breadcrumbs',true)): ?><div class="breadcrumbs"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><span>→</span><?php $cats=get_the_category();if($cats): ?><a href="<?php echo esc_url(get_category_link($cats[0]->term_id)); ?>"><?php echo esc_html($cats[0]->name); ?></a><span>→</span><?php endif; ?><span><?php the_title(); ?></span></div><?php endif; ?>
<span class="eyebrow"><?php $cats=get_the_category();if($cats)echo esc_html($cats[0]->name); ?></span><h1 class="single-title"><?php the_title(); ?></h1><div class="single-meta"><span>By <?php the_author(); ?></span><span><?php echo esc_html(get_the_date('F j, Y')); ?></span><span><?php echo esc_html(max(1,ceil(str_word_count(wp_strip_all_tags(get_the_content()))/200))); ?> min read</span></div></header>
<?php if(has_post_thumbnail()): ?><div class="featured"><?php the_post_thumbnail('full',array('loading'=>'eager')); ?></div><?php endif; ?>
<?php if(get_theme_mod('smarttoolz_share_buttons',true)): ?><div class="share-bar"><strong><?php echo esc_html(get_theme_mod('smarttoolz_share_label','Enjoyed this story? Share it.')); ?></strong><div class="share-links"><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo rawurlencode(get_permalink()); ?>">Facebook</a><a target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?url=<?php echo rawurlencode(get_permalink()); ?>&text=<?php echo rawurlencode(get_the_title()); ?>">X</a><a target="_blank" rel="noopener" href="https://www.linkedin.com/sharing/share-offsite/?url=<?php echo rawurlencode(get_permalink()); ?>">LinkedIn</a><a target="_blank" rel="noopener" href="https://wa.me/?text=<?php echo rawurlencode(get_the_title().' '.get_permalink()); ?>">WhatsApp</a></div></div><?php endif; ?>
<div class="entry-content"><?php the_content(); ?></div>
<?php if(get_theme_mod('smarttoolz_helpful_feedback',true)): ?><section class="helpful-box"><strong>Was this story helpful?</strong><p class="helpful-message">Your feedback helps us make SmartToolz better.</p><div class="helpful-actions"><button type="button" class="helpful-choice" data-value="yes">👍 Yes, it helped</button><button type="button" class="helpful-choice" data-value="no">👎 Not quite</button></div></section><?php endif; ?>
<div class="single-tags"><?php the_tags('<strong>Topics:</strong> ', ' ', ''); ?></div>
<?php if(get_theme_mod('smarttoolz_author_box',true)): ?><section class="author-box"><div class="author-avatar"><?php echo get_avatar(get_the_author_meta('ID'),72); ?></div><div><span class="eyebrow">About the author</span><h3><?php the_author(); ?></h3><p><?php echo esc_html(get_the_author_meta('description') ?: 'Sharing useful ideas, practical workflows and digital knowledge.'); ?></p></div></section><?php endif; ?>
<?php if(get_theme_mod('smarttoolz_related_posts',true)):
$related_count=max(2,absint(get_theme_mod('smarttoolz_related_count',3)));$related_ids=wp_get_post_categories(get_the_ID());$related=new WP_Query(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>$related_count,'post__not_in'=>array(get_the_ID()),'category__in'=>$related_ids,'ignore_sticky_posts'=>true));if(!$related->have_posts()){$related=new WP_Query(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>$related_count,'post__not_in'=>array(get_the_ID()),'ignore_sticky_posts'=>true));} ?>
<section class="related-stories"><div class="section-heading"><div><span class="eyebrow">Keep reading</span><h2>Related stories</h2></div></div><div class="related-grid"><?php while($related->have_posts()):$related->the_post(); ?><article class="related-card"><a href="<?php the_permalink(); ?>" class="related-media"><?php if(has_post_thumbnail())the_post_thumbnail('medium_large'); ?></a><div><span class="mini-meta"><?php $rc=get_the_category();if($rc)echo esc_html($rc[0]->name); ?> · <?php echo esc_html(get_the_date('M j')); ?></span><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),16)); ?></p></div></article><?php endwhile; ?></div></section><?php wp_reset_postdata();endif; ?>
<?php if(function_exists('get_previous_post')): ?><nav class="post-nav"><?php $prev=get_previous_post();$next=get_next_post(); if($prev): ?><a href="<?php echo esc_url(get_permalink($prev)); ?>"><small>← Previous</small><?php echo esc_html(get_the_title($prev)); ?></a><?php endif;if($next): ?><a href="<?php echo esc_url(get_permalink($next)); ?>"><small>Next →</small><?php echo esc_html(get_the_title($next)); ?></a><?php endif; ?></nav><?php endif; ?>
<?php if(get_theme_mod('smarttoolz_newsletter_cta',true) && get_theme_mod('smarttoolz_newsletter_url','')): ?><section class="newsletter-cta"><div><span class="eyebrow">SmartToolz Newsletter</span><h2><?php echo esc_html(get_theme_mod('smarttoolz_newsletter_title','Get smarter stories in your inbox')); ?></h2><p><?php echo esc_html(get_theme_mod('smarttoolz_newsletter_text','Useful ideas, tools and fresh reads — delivered without the noise.')); ?></p></div><a class="button button-dark" href="<?php echo esc_url(get_theme_mod('smarttoolz_newsletter_url','')); ?>" target="_blank" rel="noopener"><?php echo esc_html(get_theme_mod('smarttoolz_newsletter_button','Subscribe')); ?></a></section><?php endif; ?>
<?php comments_template(); ?></article></div><aside class="single-sidebar"><?php get_sidebar(); ?></aside></div></main>
<?php if(get_theme_mod('smarttoolz_back_to_top',true)): ?><button class="back-to-top" type="button" aria-label="Back to top">↑</button><?php endif; ?>
<?php get_footer(); ?>