<?php declare(strict_types=1);
function anC(PDO $db,string $sql,array $p=[]):int{try{$q=$db->prepare($sql);$q->execute($p);return(int)$q->fetchColumn();}catch(Throwable){return 0;}}
$live=anC($db,"SELECT COUNT(*) FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)");
$uv=anC($db,"SELECT COUNT(DISTINCT visitor_id) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$views=anC($db,"SELECT COUNT(*) FROM analytics_pageviews WHERE viewed_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$events=anC($db,"SELECT COUNT(*) FROM smarttoolz_analytics_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$uses=anC($db,"SELECT COUNT(*) FROM smarttoolz_analytics_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND event_type='tool_use'");
$downloads=anC($db,"SELECT COUNT(*) FROM smarttoolz_analytics_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR) AND event_type='download'");
$tools=[];try{$q=$db->query("SELECT COALESCE(NULLIF(tool_slug,''),'site') tool,COUNT(*) total FROM smarttoolz_analytics_events WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY tool_slug ORDER BY total DESC LIMIT 10");$tools=$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){}
?>
<style>
.jv{display:grid;gap:16px}.jhero{background:linear-gradient(135deg,#111827,#25204a);color:#fff;border-radius:22px;padding:22px;position:relative;overflow:hidden}.jhero:after{content:'';position:absolute;width:220px;height:220px;border-radius:50%;right:-80px;top:-90px;background:rgba(99,91,255,.22);filter:blur(4px)}.jtag{font-size:10px;letter-spacing:2px;opacity:.65}.jhero h2{margin:7px 0;font-size:25px}.jhero p{margin:0;max-width:720px;color:#cbd5e1;font-size:13px;line-height:1.6}.jactions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px;position:relative;z-index:2}.jbtn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;font-size:11px;cursor:pointer;background:#fff;color:#20243a}.jbtn.on{background:#7c72ff;color:#fff}.jstats{display:grid;grid-template-columns:repeat(6,1fr);gap:9px}.jstat{background:#fff;border:1px solid rgba(127,127,127,.16);border-radius:15px;padding:13px}.jstat b{display:block;font-size:23px}.jstat span{font-size:10px;opacity:.6}.jgrid{display:grid;grid-template-columns:1.35fr .65fr;gap:12px}.jcard{background:#fff;border:1px solid rgba(127,127,127,.16);border-radius:17px;padding:15px}.jhead{display:flex;justify-content:space-between;align-items:center;gap:10px}.jhead h3{margin:0;font-size:14px}.jhead small{opacity:.55}.jfeed{height:430px;overflow:auto;margin-top:10px;display:flex;flex-direction:column;gap:7px}.je{display:flex;gap:10px;padding:10px;border-radius:12px;background:#f7f8fb;border-left:3px solid #635bff}.je b{font-size:11px}.je small{display:block;font-size:9px;opacity:.5;margin-top:3px}.jdot{width:8px;height:8px;border-radius:50%;background:#31c48d;margin-top:4px;flex:none}.jtool{display:grid;gap:10px;margin-top:13px}.jt{display:grid;grid-template-columns:150px 1fr 55px;gap:8px;align-items:center;font-size:10px}.track{height:8px;background:#edf0f5;border-radius:10px;overflow:hidden}.track i{display:block;height:100%;background:#635bff}.jnote{padding:12px;border-radius:12px;background:#f5f3ff;margin-top:12px;font-size:11px;line-height:1.55}.emptyj{padding:25px;text-align:center;opacity:.5;font-size:11px}@media(max-width:1000px){.jstats{grid-template-columns:repeat(3,1fr)}.jgrid{grid-template-columns:1fr}}@media(max-width:600px){.jstats{grid-template-columns:repeat(2,1fr)}.jt{grid-template-columns:110px 1fr 40px}}
</style>
<div class="jv">
<section class="jhero"><div class="jtag">SMARTTOOLZ · JARVIS INTELLIGENCE</div><h2>🧠 Main tumhe numbers nahi, situation bataunga.</h2><p>Live events ko natural language mein convert karke bataunga ki site par abhi kya ho raha hai — visitor kya kar raha hai, kaunsa tool chal raha hai, download hua ya traffic mein unusual movement aayi.</p><div class="jactions"><button class="jbtn" id="jNotify">🔔 Enable instant notifications</button><a class="jbtn" href="/analytics/events.php">Full event history ↗</a></div></section>
<section class="jstats"><div class="jstat"><b id="jsLive"><?=number_format($live)?></b><span>Live visitors</span></div><div class="jstat"><b><?=number_format($uv)?></b><span>Unique · 24h</span></div><div class="jstat"><b><?=number_format($views)?></b><span>Views · 24h</span></div><div class="jstat"><b id="jsEvents"><?=number_format($events)?></b><span>Events · 24h</span></div><div class="jstat"><b><?=number_format($uses)?></b><span>Tool uses · 24h</span></div><div class="jstat"><b><?=number_format($downloads)?></b><span>Downloads · 24h</span></div></section>
<div class="jgrid"><section class="jcard"><div class="jhead"><div><h3>⚡ JARVIS LIVE FEED</h3><small>Every newly received event is translated into plain language.</small></div><span id="jStatus" class="jtag">CONNECTING</span></div><div id="jFeed" class="jfeed"><div class="emptyj">Waiting for the next site event…</div></div></section><section class="jcard"><div class="jhead"><div><h3>🛠️ What is getting attention?</h3><small>30-day interaction volume</small></div></div><div class="jtool"><?php $mx=max(1,...array_map(fn($x)=>(int)$x['total'],$tools));if(!$tools):?><div class="emptyj">No interaction data yet.</div><?php else:foreach($tools as $t):?><div class="jt"><span><?=av4h($t['tool'])?></span><div class="track"><i style="width:<?=round((int)$t['total']/$mx*100)?>%"></i></div><b><?=number_format((int)$t['total'])?></b></div><?php endforeach;endif;?></div><div class="jnote"><b>JARVIS interpretation:</b><br><span id="jInsight">I'm watching the live stream. The next meaningful movement will appear here.</span></div></section></div>
</div>
<script>
(()=>{let last=Number(localStorage.getItem('st_jarvis_last')||0),running=true;const feed=document.getElementById('jFeed'),status=document.getElementById('jStatus'),ins=document.getElementById('jInsight');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function nlp(e){let s=e.text||'A new site event arrived.';if(e.type==='page_view')return '👀 '+s+'. Someone just entered this page.';if(e.type==='tool_open')return '🛠️ '+s+'. The visitor is exploring this tool.';if(e.type==='tool_use')return '⚡ '+s+'. A tool action just happened.';if(e.type==='download')return '📥 '+s+'. A file was requested.';if(e.type==='input'||e.type==='change')return '✍️ '+s+'. The visitor changed something.';if(e.type==='click')return '🖱️ '+s+'. A visitor interaction was detected.';if(e.type==='scroll')return '📜 '+s+'. The visitor is moving through the page.';return '🔎 '+s+'.';}
function notify(e){if(!running||!('Notification'in window)||Notification.permission!=='granted')return;new Notification('SmartToolz · JARVIS',{body:nlp(e),tag:'st-event-'+e.id});}
async function poll(){try{const r=await fetch('/smart-toolz/admin/jarvis-feed.php?after='+last+'&t='+Date.now(),{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!d.ok)return;status.textContent='LIVE';status.style.color='#31c48d';if(d.stats){document.getElementById('jsLive').textContent=Number(d.stats.live||0).toLocaleString();document.getElementById('jsEvents').textContent=Number(d.stats.events_24h||0).toLocaleString();}for(const e of (d.events||[])){if(last&&e.id>last)notify(e);const row=document.createElement('div');row.className='je';row.innerHTML='<span class="jdot"></span><div><b>'+esc(nlp(e))+'</b><small>'+esc(e.time)+' · '+esc(e.visitor||'visitor')+(e.page?' · '+esc(e.page):'')+'</small></div>';feed.prepend(row);ins.textContent=nlp(e);last=Math.max(last,Number(e.id));}while(feed.children.length>80)feed.lastElementChild.remove();if(last)localStorage.setItem('st_jarvis_last',last);}catch(e){status.textContent='RECONNECTING';status.style.color='#d97706'}}
document.getElementById('jNotify').onclick=async()=>{if(!('Notification'in window)){alert('This browser does not support desktop notifications.');return}const p=await Notification.requestPermission();if(p==='granted'){running=true;document.getElementById('jNotify').classList.add('on');document.getElementById('jNotify').textContent='🔔 Notifications ON';}else alert('Notification permission was not granted.');};if('Notification'in window&&Notification.permission==='granted'){document.getElementById('jNotify').classList.add('on');document.getElementById('jNotify').textContent='🔔 Notifications ON'}poll();setInterval(poll,1500);})();
</script>
