<?php
declare(strict_types=1);
function avdCount(PDO $db,string $sql,array $p=[]):int{try{$q=$db->prepare($sql);$q->execute($p);return(int)$q->fetchColumn();}catch(Throwable){return 0;}}
function avdRows(PDO $db,string $sql,array $p=[]):array{try{$q=$db->prepare($sql);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable){return[];}}
$exists=false;$total=$today=$guest=$logged=$tools=$week=$month=0;$users=[];$selected=[];$selectedKey=(string)($_GET['visitor']??'');
try{$q=$db->query("SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='smarttoolz_download_activity' LIMIT 1");$exists=(bool)$q->fetchColumn();}catch(Throwable){}
if($exists){
$total=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity');$today=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=CURDATE()');$week=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)');$month=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE downloaded_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)');$guest=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE user_id IS NULL');$logged=avdCount($db,'SELECT COUNT(*) FROM smarttoolz_download_activity WHERE user_id IS NOT NULL');$tools=avdCount($db,'SELECT COUNT(DISTINCT tool_slug) FROM smarttoolz_download_activity');
$users=avdRows($db,"SELECT COALESCE(CAST(user_id AS CHAR),CONCAT('guest:',guest_id)) visitor_key,MAX(user_id) user_id,MAX(guest_id) guest_id,COUNT(*) downloads,COUNT(DISTINCT tool_slug) tools,MIN(downloaded_at) first_download,MAX(downloaded_at) last_download,MAX(tool_slug) last_tool FROM smarttoolz_download_activity GROUP BY COALESCE(CAST(user_id AS CHAR),CONCAT('guest:',guest_id)) ORDER BY last_download DESC LIMIT 500");
if($selectedKey!==''){$selected=avdRows($db,"SELECT id,user_id,guest_id,tool_slug,page_url,ip_address,user_agent,downloaded_at FROM smarttoolz_download_activity WHERE COALESCE(CAST(user_id AS CHAR),CONCAT('guest:',guest_id))=? ORDER BY id DESC LIMIT 2000",[$selectedKey]);}
}
function hdl(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<style>
.dlx{display:grid;gap:13px}.dlhero{background:linear-gradient(135deg,#0f172a,#312e81);color:#fff;border-radius:20px;padding:20px}.dlhero small{letter-spacing:2px;opacity:.6}.dlhero h2{margin:6px 0;font-size:24px}.dlhero p{margin:0;color:#cbd5e1;font-size:12px;line-height:1.6}.dlcards{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.dlc,.dlpanel{background:#fff;border:1px solid #e6eaf1;border-radius:14px;padding:13px}.dlc b{display:block;font-size:20px}.dlc span{font-size:9px;color:#7b8697}.dlgrid{display:grid;grid-template-columns:.85fr 1.5fr;gap:12px}.dlusers,.dltimeline{max-height:650px;overflow:auto}.dluser{display:block;color:inherit;text-decoration:none;border:1px solid #edf0f4;border-radius:11px;padding:10px;margin-top:7px;background:#fafbfc}.dluser.active{border-color:#756df2;background:#f5f3ff}.dluser strong{font-size:10px}.dluser small{display:block;font-size:8px;color:#7b8697;margin-top:3px}.badge{float:right;padding:3px 6px;border-radius:99px;background:#eeedff;color:#635bff;font-size:8px;font-weight:900}.dlsearch{display:flex;gap:7px;margin:10px 0}.dlsearch input{width:100%;border:1px solid #dfe4ec;border-radius:9px;padding:9px;font-size:10px}.event{border-left:2px solid #756df2;padding:8px 10px;margin-left:5px}.event b{font-size:10px}.event small{display:block;font-size:8px;color:#7b8697;margin-top:3px}.muted{text-align:center;padding:30px;color:#8a94a3;font-size:10px}.tag{display:inline-block;padding:4px 7px;border-radius:99px;background:#eef0f5;font-size:8px;font-weight:900}.tag.u{background:#eeedff;color:#635bff}.tag.g{background:#fff5df;color:#a96800}@media(max-width:1000px){.dlcards{grid-template-columns:repeat(4,1fr)}.dlgrid{grid-template-columns:1fr}}@media(max-width:600px){.dlcards{grid-template-columns:repeat(2,1fr)}}
</style>
<div class="dlx">
<section class="dlhero"><small>SMARTTOOLZ · DOWNLOAD INTELLIGENCE</small><h2>📥 One visitor. One download history.</h2><p>Downloads ab duplicate rows ki bheed nahi hain. Har visitor identity ke andar uske saare downloads grouped hain — guest ho ya logged-in user. Kisi visitor ko open karo aur uski complete download journey dekho.</p></section>
<?php if(!$exists): ?><section class="dlpanel"><div class="muted">Download tracking table missing. <a href="/smart-toolz/admin/tracking.php">Initialize tracking</a></div></section><?php else: ?>
<div class="dlcards"><div class="dlc"><b><?=number_format($total)?></b><span>Total events</span></div><div class="dlc"><b><?=number_format(count($users))?></b><span>Unique downloaders</span></div><div class="dlc"><b><?=number_format($today)?></b><span>Today</span></div><div class="dlc"><b><?=number_format($week)?></b><span>7 Days</span></div><div class="dlc"><b><?=number_format($month)?></b><span>30 Days</span></div><div class="dlc"><b><?=number_format($guest)?></b><span>Guest events</span></div><div class="dlc"><b><?=number_format($logged)?></b><span>Logged-in events</span></div></div>
<div class="dlgrid"><section class="dlpanel"><strong>👤 UNIQUE DOWNLOADERS</strong><div class="dlsearch"><input id="dlSearch" placeholder="Search visitor, tool…"></div><div class="dlusers" id="dlUsers"><?php if(!$users):?><div class="muted">No download history yet.</div><?php else:foreach($users as $u):?><a class="dluser <?=hash_equals($selectedKey,(string)$u['visitor_key'])?'active':''?>" href="?tab=downloads&visitor=<?=urlencode((string)$u['visitor_key'])?>"><span class="badge"><?=number_format((int)$u['downloads'])?> downloads</span><strong><?=!empty($u['user_id'])?'User #'.hdl($u['user_id']):'Guest '.hdl(substr((string)$u['guest_id'],0,12)).'…'?></strong><small><?=number_format((int)$u['tools'])?> tools · First <?=hdl($u['first_download'])?></small><small>Last <?=hdl($u['last_download'])?> · <?=hdl($u['last_tool'])?></small></a><?php endforeach;endif;?></div></section>
<section class="dlpanel"><strong>🧠 DOWNLOAD INVESTIGATION</strong><?php if(!$selectedKey):?><div class="muted">Select one visitor. JARVIS will show every download belonging to that visitor without duplicate user cards.</div><?php else:?><div style="margin-top:10px"><span class="tag <?=!empty($selected[0]['user_id'])?'u':'g'?>"><?=!empty($selected[0]['user_id'])?'Logged-in user':'Guest visitor'?></span> <b><?=number_format(count($selected))?> recorded downloads</b></div><div class="dltimeline"><?php foreach($selected as $r):?><div class="event"><b>📥 <?=hdl($r['tool_slug'])?></b><small><?=hdl($r['downloaded_at'])?> · <?=hdl($r['page_url'])?></small><small><?=hdl($r['ip_address'])?> · <?=hdl($r['user_agent'])?></small></div><?php endforeach;if(!$selected):?><div class="muted">No records found for this visitor.</div><?php endif;?></div><?php endif;?></section></div>
<?php endif; ?></div>
<script>(function(){const q=document.getElementById('dlSearch'),u=document.getElementById('dlUsers');if(q&&u)q.oninput=()=>{const s=q.value.toLowerCase();u.querySelectorAll('.dluser').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(s)?'block':'none')};})();</script>
