<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
$admin = requireAdmin();
$db = adminDb();
function av4h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$tab=(string)($_GET['tab']??'dashboard');$allowed=['dashboard','analytics','downloads','ads','settings','users','database'];if(!in_array($tab,$allowed,true))$tab='dashboard';
$tabFile=__DIR__.'/tabs/'.$tab.'.php';if(!is_file($tabFile))$tabFile=__DIR__.'/tabs/dashboard.php';
$live=0;try{$q=$db->query("SELECT COUNT(*) FROM analytics_live WHERE last_seen>=DATE_SUB(NOW(),INTERVAL 2 MINUTE)");$live=(int)$q->fetchColumn();}catch(Throwable){}
$flash=(string)($_SESSION['admin_flash']??'');unset($_SESSION['admin_flash']);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SmartToolz Admin</title><link rel="stylesheet" href="/smart-toolz/admin/admin.css?v=20260901-v5"><link rel="stylesheet" href="/smart-toolz/admin/admin-tabs.css?v=20260901-v1"></head><body class="av4"><div class="av4-shell"><aside class="av4-side"><div class="av4-brand"><div class="av4-mark">ST</div><div>SmartToolz<span class="av4-sub">Admin Control Center</span></div></div><nav class="av4-nav">
<a class="<?= $tab==='dashboard'?'active':'' ?>" href="?tab=dashboard">🏠 Dashboard</a><a class="<?= $tab==='analytics'?'active':'' ?>" href="?tab=analytics">📈 Analytics</a><a class="<?= $tab==='downloads'?'active':'' ?>" href="?tab=downloads">📥 Downloads</a><a class="<?= $tab==='ads'?'active':'' ?>" href="?tab=ads">📣 Ads Manager</a><a class="<?= $tab==='settings'?'active':'' ?>" href="?tab=settings">⚙️ Settings</a><a class="<?= $tab==='users'?'active':'' ?>" href="?tab=users">👥 Users & Credits</a><div class="av4-sep"></div><a class="<?= $tab==='database'?'active':'' ?>" href="?tab=database">🗄️ DB Explorer</a><a href="/analytics/">🌐 Full Analytics</a><a href="/analytics/advanced.php">🚀 Advanced Analytics</a><a href="/analytics/resolve-geo.php">🌍 Geo Resolver</a><a href="/smart-toolz/">← SmartToolz</a></nav><div class="av4-foot"><strong><?=av4h($admin['name']??'Admin')?></strong><br><?=av4h($admin['email']??'')?><br><span style="color:#16a36a;font-weight:900">● ADMIN ONLINE</span></div></aside><main class="av4-main"><div class="av4-top"><div class="av4-title"><h1><?=av4h(ucfirst($tab))?></h1><p>SmartToolz live control center</p></div><div class="av4-live"><span class="av4-dot"></span><span data-av4-live><?=number_format($live)?></span> live now</div></div><?php if($flash):?><div class="av4-notice"><?=av4h($flash)?></div><?php endif;?><div class="av4-content"><?php require $tabFile; ?></div></main></div><script>(function(){async function live(){try{const r=await fetch('/analytics/live.php?t='+Date.now(),{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const d=await r.json();document.querySelectorAll('[data-av4-live]').forEach(e=>e.textContent=Number(d.count||0).toLocaleString());}catch(e){}}live();setInterval(live,1000)})();</script></body></html>
