(()=>{'use strict';const root=document.getElementById('st-live-dashboard');if(!root)return;const api='/smart-toolz/admin/dashboard-live.php';const q=s=>root.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[m]));const fmt=n=>Number(n||0).toLocaleString();const pct=(n,max)=>Math.max(3,Math.min(100,(Number(n||0)/Math.max(1,max))*100));
function barRows(a){const max=Math.max(1,...a.map(x=>Number(x.total||0)));return a.length?a.map(x=>`<div class="st-bar-line"><div><span>${esc(x.label||'Unknown')}</span><div class="st-track"><div class="st-fill" style="width:${pct(x.total,max)}%"></div></div></div><strong>${fmt(x.total)}</strong></div>`).join(''):'<div class="st-small">No data yet.</div>'}
function card(icon,label,val,cls){return `<div class="st-k ${cls||''}"><div class="ico">${icon}</div><b>${fmt(val)}</b><span>${label}</span></div>`}
function render(d){const c=d.counts||{};q('#stCards').innerHTML=[card('🟢','Live visitors',c.live,'st-green'),card('👥','Visitors today',c.visitors_today,'st-cyan'),card('👁️','Page views today',c.pageviews_today,'st-purple'),card('🛠️','Tool uses today',c.tools_today,'st-orange'),card('📥','Downloads today',c.downloads_today,'st-blue'),card('⚡','Credits in users',c.credits,'st-purple'),card('📢','Active ads',c.ads_enabled,'st-green'),card('🧩','Registered users',c.users,'st-cyan'),card('🎯','Events today',c.events_today,'st-orange'),card('🔐','Admin accounts',c.admins,'st-red'),card('📚','Total tool uses',c.tools_used,'st-blue'),card('📈','Total page views',c.pageviews,'st-purple')].join('');
const traffic=d.traffic||[],mx=Math.max(1,...traffic.map(x=>Number(x.total||0)));q('#stTraffic').innerHTML=traffic.map(x=>`<div class="st-col" title="${esc(x.label)} · ${fmt(x.total)}"><i style="height:${pct(x.total,mx)}%"></i></div>`).join('')||'<div class="st-small">No traffic data yet.</div>';
q('#stPages').innerHTML=barRows(d.pages||[]);q('#stCountries').innerHTML=barRows(d.countries||[]);q('#stDevices').innerHTML=barRows(d.devices||[]);q('#stBrowsers').innerHTML=barRows(d.browsers||[]);
const rows=d.live_rows||[];q('#stLiveCount').textContent=fmt(rows.length);q('#stLiveRows').innerHTML=rows.length?rows.map(r=>`<div class="st-live-row"><span class="st-online">● LIVE</span><span>${esc((r.country_code||'??')+' '+(r.city||''))}</span><span>${esc(r.device||'Unknown')}</span><span>${esc(r.browser||'Unknown')}</span><span>${esc(r.page_path||'-')}</span></div>`).join(''):'<div class="st-small" style="padding:10px">No visitors in the last 2 minutes.</div>';
const recent=(d.recent_tools||[]).concat(d.recent_downloads||[]).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))).slice(0,14);q('#stActivity').innerHTML=recent.length?recent.map(r=>{const title=r.tool_name||r.tool||r.page_path||r.action||'Activity';const who=r.user_id?'User #'+r.user_id:(r.guest_id?'Guest '+String(r.guest_id).slice(0,12):'Visitor');return `<div class="st-activity-row"><div><b>${esc(title)}</b><div class="st-small">${esc(who)}</div></div><span>${esc(r.created_at||'')}</span></div>`}).join(''):'<div class="st-small">No recent activity.</div>';q('#stUpdated').textContent=d.generated_at||'—'}
async function load(){try{const r=await fetch(api+'?_='+Date.now(),{cache:'no-store',credentials:'same-origin'});const d=await r.json();if(d.ok)render(d)}catch(e){const x=q('#stUpdated');if(x)x.textContent='Update failed'}}
load();setInterval(load,1000);q('#stRefresh')?.addEventListener('click',load);})();