<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free HTML Entity Encoder & Decoder Online','description'=>'Encode special characters into HTML entities or decode HTML entities back to readable text instantly with SmartToolz.','url'=>'https://smarttoolz.in/tools/html-entity-encoder/'];
smarttoolz_tool_page_start($tool);
?>
<main class="he-page"><section class="tool-head"><span class="eyebrow">HTML ENTITY TOOL</span><h1>HTML Entity Encoder & Decoder</h1><p>Convert special characters to HTML entities and decode them back instantly.</p></section><section class="he-card"><div class="tabs"><button class="tab active" data-mode="encode">Encode</button><button class="tab" data-mode="decode">Decode</button></div><label>Input<textarea id="input" placeholder="Enter text here..." spellcheck="false"></textarea></label><div class="actions"><button id="run" class="primary">Encode HTML</button><button id="clear">Clear</button></div><label>Output<textarea id="output" readonly placeholder="Result will appear here..."></textarea></label><button id="copy" class="copy">Copy Output</button></section><section class="info-grid"><article><h2>HTML entities</h2><p>Encode characters such as &, &lt;, &gt;, quotes and non-ASCII symbols for safer HTML text.</p></article><article><h2>Private and instant</h2><p>Conversion happens locally in your browser, so your text is not uploaded.</p></article></section></main>
<style>.he-page{width:min(900px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.he-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.tabs{display:flex;gap:7px;padding:5px;margin-bottom:20px;background:#f4f5f9;border-radius:12px}.tab{flex:1;border:0;border-radius:9px;padding:11px;background:transparent;color:#667085;font-size:10px;font-weight:900;cursor:pointer}.tab.active{background:#fff;color:#5541ff;box-shadow:0 2px 8px rgba(16,24,40,.08)}.he-card label{display:grid;gap:7px;margin-bottom:13px;color:#344054;font-size:11px;font-weight:800}.he-card textarea{box-sizing:border-box;width:100%;min-height:190px;padding:14px;border:1px solid #dfe3eb;border-radius:12px;background:#fcfdff;color:#172033;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;resize:vertical;outline:0}.he-card textarea:focus{border-color:#8d80ff}.actions{display:flex;gap:9px;margin-bottom:13px}.actions button,.copy{padding:10px 16px;border:1px solid #dfe3eb;border-radius:10px;background:#fff;color:#344054;font-size:10px;font-weight:900;cursor:pointer}.actions .primary{border:0;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff}.copy{margin-top:9px;background:#111936;color:#fff;border-color:#111936}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:650px){.he-page{width:calc(100% - 20px)}.he-card{padding:16px}.tabs{flex-direction:column}.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{let mode='encode';const input=document.getElementById('input'),output=document.getElementById('output'),run=document.getElementById('run');const encode=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');const decode=s=>{const t=document.createElement('textarea');t.innerHTML=s;return t.value};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));run.textContent=mode==='encode'?'Encode HTML':'Decode HTML';output.value=''});run.onclick=()=>{output.value=mode==='encode'?encode(input.value):decode(input.value)};document.getElementById('clear').onclick=()=>{input.value='';output.value=''};document.getElementById('copy').onclick=async()=>{if(!output.value)return;await navigator.clipboard.writeText(output.value);document.getElementById('copy').textContent='Copied';setTimeout(()=>document.getElementById('copy').textContent='Copy Output',900)}})();</script>
<?php smarttoolz_tool_page_end(); ?>
