<?php
declare(strict_types=1);
require_once __DIR__.'/personality.php';
function brainNormalize(string $t): string { $t=trim($t); $t=preg_replace('/https?:\/\/\S+/iu',' ',$t)??$t; $t=preg_replace('/(.)\1{5,}/u','$1$1$1',$t)??$t; return trim(preg_replace('/\s+/u',' ',$t)??$t); }
function brainTokens(string $t): array { preg_match_all('/[\p{L}\p{N}]{2,}/u',mb_strtolower(brainNormalize($t),'UTF-8'),$m); return array_values(array_unique($m[0]??[])); }
function brainHasAny(string $t,array $w): bool { $t=mb_strtolower($t,'UTF-8'); foreach($w as $x) if(str_contains($t,mb_strtolower($x,'UTF-8'))) return true; return false; }
function brainSimilarity(string $a,string $b): float { $a=mb_strtolower(brainNormalize($a),'UTF-8');$b=mb_strtolower(brainNormalize($b),'UTF-8');if($a===''||$b==='')return 0;similar_text($a,$b,$p);$aa=brainTokens($a);$bb=brainTokens($b);$u=count(array_unique(array_merge($aa,$bb)));$j=$u?count(array_intersect($aa,$bb))/$u:0;return max($j,$p/100); }
function brainDetectLanguage(string $t): string { if(preg_match('/[\x{0900}-\x{097F}]/u',$t))return'hindi';if(brainHasAny($t,['hai','hain','kaise','kya','kyu','kyun','mujhe','aap','tum','accha','achha','bahut','nahi','nahin','batao','bolo','yaar','dost','kar','karo','hoon','raha','rahi']))return'hinglish';return'english'; }
function brainEmotion(string $t): string { $m=['joy'=>['happy','khush','khushi','excited','mast','wow','yay','😍','😊','😂'],'sadness'=>['sad','dukhi','udaas','alone','miss','rona','😭','😢','💔'],'anger'=>['angry','gussa','irritated','hate'],'love'=>['love','pyar','pyaar','cute','jaan','❤️','💕'],'curiosity'=>['why','how','what','kya','kaise','kyu','kyun','batao'],'fun'=>['joke','funny','mazaak','lol','😂']];foreach($m as $e=>$w)if(brainHasAny($t,$w))return$e;return'neutral'; }
function brainIntent(string $t): string { $c=['greeting'=>['hello','hi','hey','hii','hlo','namaste','good morning','good evening','good night'],'gratitude'=>['thanks','thank you','thanku','shukriya','dhanyavad'],'identity'=>['who are you','tum kaun','kaun ho','your name','naam kya','bot ka naam'],'mood'=>['how are you','kaise ho','kya haal','mood'],'help'=>['help','madad','what can you do','commands'],'like'=>['like kar','like karo','like please'],'share'=>['share kar','share karo','share please','forward'],'time'=>['time kya','timer','next reminder'],'repeat'=>['repeat','repeating','same thing','same baat','why are you repeating','phir se wahi','baar baar','bar bar'],'moderation'=>['spam','abuse','report','ban him','remove him','gali'],'compliment'=>['nice','awesome','amazing','good bot','smart bot','best bot'],'question'=>['?','what ','why ','how ','who ','when ','where ','which ','kya ','kyu ','kyun ','kaise ','kab ','kahan ']];$l=mb_strtolower($t,'UTF-8');$best='chat';$score=0;foreach($c as $i=>$ps)foreach($ps as $p){$s=str_contains($l,$p)?1:brainSimilarity($l,$p);if($s>$score&&$s>=.58){$best=$i;$score=$s;}}return$best; }
function brainMemory(string $id,string $name,string $text): array { $k='brain_memory_'.hash('sha256',$id?:$name?:'anon');$m=gj($k,['name'=>$name,'messages'=>[]]);if(!is_array($m))$m=['name'=>$name,'messages'=>[]];$m['name']=$name;$m['messages'][]=mb_substr(brainNormalize($text),0,180,'UTF-8');$m['messages']=array_slice(array_values($m['messages']),-8);sj($k,$m);return$m; }
function brainRecent(): array { $x=gj('brain_recent_chat',[]);return is_array($x)?array_slice($x,-12):[]; }
function brainRememberRecent(string $name,string $text): void { $r=brainRecent();$r[]=['name'=>mb_substr($name,0,60,'UTF-8'),'text'=>mb_substr(brainNormalize($text),0,220,'UTF-8'),'ts'=>time()];sj('brain_recent_chat',array_slice($r,-12)); }
function brainReplyLocal(string $name,string $text,string $lang,string $emotion,string $intent,array $memory): string { $eng=$lang==='english'; $sets=['greeting'=>["Hi {$name}! 😄 Keddy yahin hai.","Oho {$name}, entry ho gayi 😎"],'gratitude'=>['Arre koi baat nahi 😄','Anytime ❤️'],'identity'=>['Main Keddy Bot BTS hoon — is live ka chat companion. 😎','Keddy hoon 😄 chat, masti aur moderation meri duty hai.'],'mood'=>["Main mast hoon 😄 Live ka mood kaisa chal raha hai?","All good, {$name}. Chat zinda rakho 😎"],'help'=>['Hindi, Hinglish ya English mein normal baat karo. Sawaal, masti aur chat sab chalega 😎'],'like'=>['❤️ Like kar do dosto — host ko support dikhao!','Like button ko thoda pyaar do 😄'],'share'=>['🔗 Share kar do dosto, ek friend ko live mein lao!','Ek share idhar bhi banta hai 😎'],'time'=>['⏱️ Social reminder 2-minute cycle par chal raha hai.','Timer active hai 😄'],'repeat'=>['Haan 😅 pichhli reply repeat ho gayi thi. Ab seedhi baat.','Fair point 😄 Repeat mode off.'],'compliment'=>['Aise compliments se Keddy ka ego dangerous ho jayega 😂','Noted 😎 confidence +7%.'],'moderation'=>['Keddy Shield online hai 😎 Spam aur toxic messages rules ke hisaab se handle honge.']];if(isset($sets[$intent]))return$sets[$intent][array_rand($sets[$intent])];if($emotion==='sadness')return"💜 {$name}, mood heavy lag raha hai. Keddy yahin hai.";if($emotion==='anger')return"😅 {$name}, gussa samajh aa raha hai. Bas chat ko toxic mat hone dena.";if($emotion==='love')return'Acha ji 😄 pyaar wali vibe aa rahi hai.';if($emotion==='joy'||$emotion==='fun')return"🔥 Ye hui na energy, {$name}!";if($intent==='question')return$eng?"Good question, {$name}. Main seedhi useful baat rakhunga 😄":"Accha sawaal hai, {$name}. Keddy seedha jawab dega 😄";$a=$eng?["Got you, {$name}. 😄","Fair enough, {$name}.","Haha, interesting 😄"]:["Samajh gaya {$name} 😄","Haan, Keddy sun raha hai.","Achha 😄"];return$a[array_rand($a)]; }
function brainReply(array $x): string { $name=trim((string)($x['authorDetails']['displayName']??''))?:'dost';$id=trim((string)($x['authorDetails']['channelId']??''));$text=brainNormalize((string)($x['snippet']['displayMessage']??''));if($text==='')return'';$lang=brainDetectLanguage($text);$emotion=brainEmotion($text);$intent=brainIntent($text);$m=brainMemory($id,$name,$text);$m['channel_id']=$id;brainRememberRecent($name,$text);$r=brainReplyLocal($name,$text,$lang,$emotion,$intent,$m);foreach(brainRecent() as $row)if(($row['name']??'')==='Keddy'&&brainSimilarity($r,(string)($row['text']??''))>.92){$r=$lang==='english'?"Got you, {$name}. Let's keep it moving 😄":"Samajh gaya {$name}. Chalo aage badhte hain 😄";break;}brainRememberRecent('Keddy',$r);return$r; }
