<?php
declare(strict_types=1);

function keddyDataInit():void{
    static $done=false;if($done)return;$done=true;
    db()->exec("CREATE TABLE IF NOT EXISTS managed_channels(channel_id TEXT PRIMARY KEY,title TEXT NOT NULL DEFAULT '',handle TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',custom_url TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',thumbnail_url TEXT NOT NULL DEFAULT '',uploads_playlist_id TEXT NOT NULL DEFAULT '',subscriber_count INTEGER,view_count INTEGER,video_count INTEGER,hidden_subscriber_count INTEGER,privacy_status TEXT NOT NULL DEFAULT '',made_for_kids INTEGER,topic_categories_json TEXT NOT NULL DEFAULT '[]',branding_json TEXT NOT NULL DEFAULT '{}',content_details_json TEXT NOT NULL DEFAULT '{}',statistics_json TEXT NOT NULL DEFAULT '{}',status_json TEXT NOT NULL DEFAULT '{}',raw_json TEXT NOT NULL DEFAULT '{}',registered_user INTEGER NOT NULL DEFAULT 0,moderation_enabled INTEGER NOT NULL DEFAULT 0,first_seen_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,moderator_since INTEGER)");
    db()->exec("CREATE TABLE IF NOT EXISTS channel_snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,channel_id TEXT NOT NULL,captured_at INTEGER NOT NULL,source TEXT NOT NULL DEFAULT 'api',raw_json TEXT NOT NULL)");
    db()->exec('CREATE INDEX IF NOT EXISTS idx_channel_snapshots_channel_time ON channel_snapshots(channel_id,captured_at DESC)');
    db()->exec("CREATE TABLE IF NOT EXISTS youtube_users(channel_id TEXT PRIMARY KEY,display_name TEXT NOT NULL DEFAULT '',custom_url TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',profile_image_url TEXT NOT NULL DEFAULT '',uploads_playlist_id TEXT NOT NULL DEFAULT '',subscriber_count INTEGER,view_count INTEGER,video_count INTEGER,hidden_subscriber_count INTEGER,made_for_kids INTEGER,branding_json TEXT NOT NULL DEFAULT '{}',content_details_json TEXT NOT NULL DEFAULT '{}',statistics_json TEXT NOT NULL DEFAULT '{}',status_json TEXT NOT NULL DEFAULT '{}',raw_json TEXT NOT NULL DEFAULT '{}',first_seen_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL)");
    db()->exec("CREATE TABLE IF NOT EXISTS youtube_videos(video_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',category_id TEXT NOT NULL DEFAULT '',duration TEXT NOT NULL DEFAULT '',privacy_status TEXT NOT NULL DEFAULT '',license TEXT NOT NULL DEFAULT '',made_for_kids INTEGER,live_broadcast_content TEXT NOT NULL DEFAULT '',tags_json TEXT NOT NULL DEFAULT '[]',statistics_json TEXT NOT NULL DEFAULT '{}',content_details_json TEXT NOT NULL DEFAULT '{}',status_json TEXT NOT NULL DEFAULT '{}',raw_json TEXT NOT NULL DEFAULT '{}',first_seen_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL)");
    db()->exec('CREATE INDEX IF NOT EXISTS idx_youtube_videos_channel_time ON youtube_videos(channel_id,last_seen_at DESC)');
    db()->exec("CREATE TABLE IF NOT EXISTS youtube_chat_messages(message_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL DEFAULT '',live_broadcast_id TEXT NOT NULL DEFAULT '',live_chat_id TEXT NOT NULL DEFAULT '',author_channel_id TEXT NOT NULL DEFAULT '',author_name TEXT NOT NULL DEFAULT '',message_text TEXT NOT NULL DEFAULT '',message_type TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',raw_json TEXT NOT NULL DEFAULT '{}',captured_at INTEGER NOT NULL)");
    db()->exec('CREATE INDEX IF NOT EXISTS idx_chat_author_time ON youtube_chat_messages(author_channel_id,captured_at DESC)');
    db()->exec('CREATE INDEX IF NOT EXISTS idx_chat_channel_time ON youtube_chat_messages(channel_id,captured_at DESC)');
    db()->exec("CREATE TABLE IF NOT EXISTS moderation_events(id INTEGER PRIMARY KEY AUTOINCREMENT,channel_id TEXT NOT NULL DEFAULT '',live_broadcast_id TEXT NOT NULL DEFAULT '',live_chat_id TEXT NOT NULL DEFAULT '',message_id TEXT NOT NULL DEFAULT '',target_channel_id TEXT NOT NULL DEFAULT '',target_name TEXT NOT NULL DEFAULT '',action TEXT NOT NULL DEFAULT '',severity INTEGER NOT NULL DEFAULT 0,reason TEXT NOT NULL DEFAULT '',hit TEXT NOT NULL DEFAULT '',offense INTEGER,created_at INTEGER NOT NULL,raw_json TEXT NOT NULL DEFAULT '{}')");
    db()->exec('CREATE INDEX IF NOT EXISTS idx_mod_channel_time ON moderation_events(channel_id,created_at DESC)');
    db()->exec('CREATE INDEX IF NOT EXISTS idx_mod_target_time ON moderation_events(target_channel_id,created_at DESC)');
    db()->exec("CREATE TABLE IF NOT EXISTS managed_channel_events(id INTEGER PRIMARY KEY AUTOINCREMENT,channel_id TEXT NOT NULL,live_broadcast_id TEXT NOT NULL DEFAULT '',live_chat_id TEXT NOT NULL DEFAULT '',event_type TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL)");
    db()->exec('CREATE INDEX IF NOT EXISTS idx_managed_events_channel_time ON managed_channel_events(channel_id,created_at DESC)');
}
function keddyJson($v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE)?:'{}';}
function keddyIntOrNull($v):?int{return $v===null||$v===''?null:(int)$v;}
function keddyDataCaptureChannelApi(array $item,bool $registered=false,bool $moderation=false,string $source='api'):void{
    keddyDataInit();$id=trim((string)($item['id']??''));if($id==='')return;$sn=$item['snippet']??[];$cd=$item['contentDetails']??[];$st=$item['statistics']??[];$bs=$item['brandingSettings']??[];$status=$item['status']??[];$topic=$item['topicDetails']??[];$now=time();
    $q=db()->prepare("INSERT INTO managed_channels(channel_id,title,handle,description,custom_url,published_at,country,thumbnail_url,uploads_playlist_id,subscriber_count,view_count,video_count,hidden_subscriber_count,privacy_status,made_for_kids,topic_categories_json,branding_json,content_details_json,statistics_json,status_json,raw_json,registered_user,moderation_enabled,first_seen_at,last_seen_at,moderator_since) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(channel_id) DO UPDATE SET title=excluded.title,handle=excluded.handle,description=excluded.description,custom_url=excluded.custom_url,published_at=excluded.published_at,country=excluded.country,thumbnail_url=excluded.thumbnail_url,uploads_playlist_id=excluded.uploads_playlist_id,subscriber_count=excluded.subscriber_count,view_count=excluded.view_count,video_count=excluded.video_count,hidden_subscriber_count=excluded.hidden_subscriber_count,privacy_status=excluded.privacy_status,made_for_kids=excluded.made_for_kids,topic_categories_json=excluded.topic_categories_json,branding_json=excluded.branding_json,content_details_json=excluded.content_details_json,statistics_json=excluded.statistics_json,status_json=excluded.status_json,raw_json=excluded.raw_json,registered_user=CASE WHEN excluded.registered_user=1 THEN 1 ELSE managed_channels.registered_user END,moderation_enabled=CASE WHEN excluded.moderation_enabled=1 THEN 1 ELSE managed_channels.moderation_enabled END,last_seen_at=excluded.last_seen_at,moderator_since=CASE WHEN excluded.moderator_since IS NOT NULL THEN excluded.moderator_since ELSE managed_channels.moderator_since END");
    $q->execute([$id,(string)($sn['title']??''),(string)($sn['customUrl']??''),(string)($sn['description']??''),(string)($sn['customUrl']??''),(string)($sn['publishedAt']??''),(string)($sn['country']??''),(string)($sn['thumbnails']['high']['url']??$sn['thumbnails']['default']['url']??''),(string)($cd['relatedPlaylists']['uploads']??''),keddyIntOrNull($st['subscriberCount']??null),keddyIntOrNull($st['viewCount']??null),keddyIntOrNull($st['videoCount']??null),!empty($st['hiddenSubscriberCount'])?1:0,(string)($status['privacyStatus']??''),array_key_exists('madeForKids',$status)?(!empty($status['madeForKids'])?1:0):null,keddyJson($topic['topicCategories']??[]),keddyJson($bs),keddyJson($cd),keddyJson($st),keddyJson($status),keddyJson($item),$registered?1:0,$moderation?1:0,$now,$now,$moderation?$now:null]);
    db()->prepare('INSERT INTO channel_snapshots(channel_id,captured_at,source,raw_json) VALUES(?,?,?,?)')->execute([$id,$now,$source,keddyJson($item)]);
    $q=db()->prepare("INSERT INTO youtube_users(channel_id,display_name,custom_url,description,published_at,country,profile_image_url,uploads_playlist_id,subscriber_count,view_count,video_count,hidden_subscriber_count,made_for_kids,branding_json,content_details_json,statistics_json,status_json,raw_json,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(channel_id) DO UPDATE SET display_name=excluded.display_name,custom_url=excluded.custom_url,description=excluded.description,published_at=excluded.published_at,country=excluded.country,profile_image_url=excluded.profile_image_url,uploads_playlist_id=excluded.uploads_playlist_id,subscriber_count=excluded.subscriber_count,view_count=excluded.view_count,video_count=excluded.video_count,hidden_subscriber_count=excluded.hidden_subscriber_count,made_for_kids=excluded.made_for_kids,branding_json=excluded.branding_json,content_details_json=excluded.content_details_json,statistics_json=excluded.statistics_json,status_json=excluded.status_json,raw_json=excluded.raw_json,last_seen_at=excluded.last_seen_at");
    $q->execute([$id,(string)($sn['title']??''),(string)($sn['customUrl']??''),(string)($sn['description']??''),(string)($sn['publishedAt']??''),(string)($sn['country']??''),(string)($sn['thumbnails']['high']['url']??$sn['thumbnails']['default']['url']??''),(string)($cd['relatedPlaylists']['uploads']??''),keddyIntOrNull($st['subscriberCount']??null),keddyIntOrNull($st['viewCount']??null),keddyIntOrNull($st['videoCount']??null),!empty($st['hiddenSubscriberCount'])?1:0,array_key_exists('madeForKids',$status)?(!empty($status['madeForKids'])?1:0):null,keddyJson($bs),keddyJson($cd),keddyJson($st),keddyJson($status),keddyJson($item),$now,$now]);
}
function keddyDataCaptureChannelById(string $channelId,string $source='api',bool $registered=false,bool $moderation=false,?string $tokenOverride=null):?array{
    keddyDataInit();$id=trim($channelId);if($id==='')return null;try{$j=$tokenOverride!==null?ytWithToken('channels?part=id,snippet,contentDetails,statistics,brandingSettings,topicDetails,status&id='.rawurlencode($id).'&maxResults=1','GET',null,$tokenOverride):ytBot('channels?part=id,snippet,contentDetails,statistics,brandingSettings,topicDetails,status&id='.rawurlencode($id).'&maxResults=1');$x=$j['items'][0]??null;if(!$x)return null;keddyDataCaptureChannelApi($x,$registered,$moderation,$source);return$x;}catch(Throwable $e){return null;}}
function keddyDataMarkModeratedChannel(string $channelId,string $liveId='',string $chatId='',string $event='moderator_confirmed',array $details=[]):void{ keddyDataInit();$now=time();db()->prepare('UPDATE managed_channels SET moderation_enabled=1,moderator_since=COALESCE(moderator_since,?),last_seen_at=? WHERE channel_id=?')->execute([$now,$now,$channelId]);db()->prepare('INSERT INTO managed_channel_events(channel_id,live_broadcast_id,live_chat_id,event_type,details_json,created_at) VALUES(?,?,?,?,?,?)')->execute([$channelId,$liveId,$chatId,$event,keddyJson($details),$now]); }
function keddyDataCaptureChat(array $x,string $channelId,string $liveId,string $chatId):void{ keddyDataInit();$id=(string)($x['id']??'');if($id==='')return;$a=$x['authorDetails']??[];$s=$x['snippet']??[];db()->prepare('INSERT OR IGNORE INTO youtube_chat_messages(message_id,channel_id,live_broadcast_id,live_chat_id,author_channel_id,author_name,message_text,message_type,published_at,raw_json,captured_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$channelId,$liveId,$chatId,(string)($a['channelId']??''),(string)($a['displayName']??''),(string)($s['displayMessage']??''),(string)($s['type']??''),(string)($s['publishedAt']??''),keddyJson($x),time()]); }
function keddyDataCaptureVideo(array $x):void{ keddyDataInit();$id=trim((string)($x['id']??''));if($id==='')return;$sn=$x['snippet']??[];$cd=$x['contentDetails']??[];$st=$x['statistics']??[];$status=$x['status']??[];$now=time();db()->prepare("INSERT INTO youtube_videos(video_id,channel_id,title,description,published_at,category_id,duration,privacy_status,license,made_for_kids,live_broadcast_content,tags_json,statistics_json,content_details_json,status_json,raw_json,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(video_id) DO UPDATE SET title=excluded.title,description=excluded.description,published_at=excluded.published_at,category_id=excluded.category_id,duration=excluded.duration,privacy_status=excluded.privacy_status,license=excluded.license,made_for_kids=excluded.made_for_kids,live_broadcast_content=excluded.live_broadcast_content,tags_json=excluded.tags_json,statistics_json=excluded.statistics_json,content_details_json=excluded.content_details_json,status_json=excluded.status_json,raw_json=excluded.raw_json,last_seen_at=excluded.last_seen_at")->execute([$id,(string)($sn['channelId']??''),(string)($sn['title']??''),(string)($sn['description']??''),(string)($sn['publishedAt']??''),(string)($sn['categoryId']??''),(string)($cd['duration']??''),(string)($status['privacyStatus']??''),(string)($status['license']??''),array_key_exists('madeForKids',$status)?(!empty($status['madeForKids'])?1:0):null,(string)($sn['liveBroadcastContent']??''),keddyJson($sn['tags']??[]),keddyJson($st),keddyJson($cd),keddyJson($status),keddyJson($x),$now,$now]); }
function keddyDataRecordModeration(string $channelId,array $x,array $decision,string $liveId='',string $chatId=''):void{ keddyDataInit();$a=$x['authorDetails']??[];db()->prepare('INSERT INTO moderation_events(channel_id,live_broadcast_id,live_chat_id,message_id,target_channel_id,target_name,action,severity,reason,hit,offense,created_at,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$channelId,$liveId,$chatId,(string)($x['id']??''),(string)($a['channelId']??''),(string)($a['displayName']??''),(string)($decision['action']??''),(int)($decision['severity']??0),(string)($decision['reason']??''),(string)($decision['hit']??''),array_key_exists('offense',$decision)?(int)$decision['offense']:null,time(),keddyJson($decision)]); }
function keddyDataStats():array{ keddyDataInit();return ['managed_channels'=>(int)db()->query('SELECT COUNT(*) FROM managed_channels')->fetchColumn(),'moderated_channels'=>(int)db()->query('SELECT COUNT(*) FROM managed_channels WHERE moderation_enabled=1')->fetchColumn(),'registered_users'=>(int)db()->query('SELECT COUNT(*) FROM managed_channels WHERE registered_user=1')->fetchColumn(),'youtube_users'=>(int)db()->query('SELECT COUNT(*) FROM youtube_users')->fetchColumn(),'videos'=>(int)db()->query('SELECT COUNT(*) FROM youtube_videos')->fetchColumn(),'chat_messages'=>(int)db()->query('SELECT COUNT(*) FROM youtube_chat_messages')->fetchColumn(),'moderation_events'=>(int)db()->query('SELECT COUNT(*) FROM moderation_events')->fetchColumn()]; }
