<?php
declare(strict_types=1);
session_start();
require __DIR__.'/bot.php';
require_once __DIR__.'/comments-engine.php';

function dcEnsureTables():void{
    $tables=[
        "CREATE TABLE IF NOT EXISTS live_broadcasts(live_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL DEFAULT '',live_chat_id TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',scheduled_start TEXT NOT NULL DEFAULT '',actual_start TEXT NOT NULL DEFAULT '',privacy_status TEXT NOT NULL DEFAULT '',raw_json TEXT NOT NULL DEFAULT '{}',first_seen_at INTEGER NOT NULL DEFAULT 0,last_seen_at INTEGER NOT NULL DEFAULT 0)",
        "CREATE TABLE IF NOT EXISTS youtube_users(channel_id TEXT PRIMARY KEY,display_name TEXT NOT NULL DEFAULT '',custom_url TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',profile_image_url TEXT NOT NULL DEFAULT '',uploads_playlist_id TEXT NOT NULL DEFAULT '',subscriber_count INTEGER,view_count INTEGER,video_count INTEGER,hidden_subscriber_count INTEGER,made_for_kids INTEGER,branding_json TEXT NOT NULL DEFAULT '{}',content_details_json TEXT NOT NULL DEFAULT '{}',statistics_json TEXT NOT NULL DEFAULT '{}',status_json TEXT NOT NULL DEFAULT '{}',raw_json TEXT NOT NULL DEFAULT '{}',first_seen_at INTEGER NOT NULL DEFAULT 0,last_seen_at INTEGER NOT NULL DEFAULT 0)",
        "CREATE TABLE IF NOT EXISTS managed_channel_events(id INTEGER PRIMARY KEY AUTOINCREMENT,channel_id TEXT NOT NULL,live_broadcast_id TEXT NOT NULL DEFAULT '',live_chat_id TEXT NOT NULL DEFAULT '',event_type TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL DEFAULT 0)"
    ];
    foreach($tables as $sql){try{db()->exec($sql);}catch(Throwable $e){}}
}
function dcRows(string $sql):array{try{$q=db()->query($sql);return$q->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){return[];}}
function dcCount(string $sql):int{try{return(int)db()->query($sql)->fetchColumn();}catch(Throwable $e){return 0;}}
function dcH($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function dcTime($v):string{return$v?date('d M Y, h:i A',(int)$v):'—';}
function dcBytes(int $b):string{$u=['B','KB','MB','GB'];$i=0;$n=(float)$b;while($n>=1024&&$i<3){$n/=1024;$i++;}return number_format($n,2).' '.$u[$i];}

try{ keddyDataInit(); keddyUsersInit(); dcEnsureTables();
$dbFile=(string)(cfg()['database']??(__DIR__.'/data/keddy.sqlite'));$dbSize=is_file($dbFile)?(int)filesize($dbFile):0;
$stats=['managed_channels'=>dcCount('SELECT COUNT(*) FROM managed_channels'),'moderated_channels'=>dcCount('SELECT COUNT(*) FROM managed_channels WHERE moderation_enabled=1'),'registered_users'=>dcCount('SELECT COUNT(*) FROM keddy_registered_users WHERE enabled=1'),'youtube_users'=>dcCount('SELECT COUNT(*) FROM youtube_users'),'videos'=>dcCount('SELECT COUNT(*) FROM youtube_videos'),'chat_messages'=>dcCount('SELECT COUNT(*) FROM youtube_chat_messages'),'moderation_events'=>dcCount('SELECT COUNT(*) FROM moderation_events'),'live_broadcasts'=>dcCount('SELECT COUNT(*) FROM live_broadcasts'),'snapshots'=>dcCount('SELECT COUNT(*) FROM channel_snapshots'),'channel_events'=>dcCount('SELECT COUNT(*) FROM managed_channel_events'),'comments_posted'=>dcCount("SELECT COUNT(*) FROM viewer_comment_history WHERE status='posted'"),'comments_failed'=>dcCount("SELECT COUNT(*) FROM viewer_comment_history WHERE status='failed'")];
$channels=dcRows('SELECT * FROM managed_channels ORDER BY last_seen_at DESC LIMIT 200');$users=dcRows('SELECT channel_id,display_name,custom_url,description,published_at,country,subscriber_count,view_count,video_count,last_seen_at FROM youtube_users ORDER BY last_seen_at DESC LIMIT 200');$videos=dcRows('SELECT video_id,channel_id,title,description,published_at,duration,privacy_status,license,live_broadcast_content,last_seen_at FROM youtube_videos ORDER BY last_seen_at DESC LIMIT 200');$chat=dcRows('SELECT message_id,channel_id,author_channel_id,author_name,message_text,published_at,captured_at FROM youtube_chat_messages ORDER BY captured_at DESC LIMIT 200');$mods=dcRows('SELECT channel_id,live_broadcast_id,message_id,target_channel_id,target_name,action,severity,reason,hit,offense,created_at FROM moderation_events ORDER BY created_at DESC LIMIT 200');$lives=dcRows('SELECT live_id,channel_id,title,live_chat_id,published_at,actual_start,last_seen_at FROM live_broadcasts ORDER BY last_seen_at DESC LIMIT 100');$comments=commentHistory(200);
}catch(Throwable $e){http_response_code(500);echo'<!doctype html><meta charset="utf-8"><style>body{font:16px system-ui;background:#080b10;color:#fff;padding:30px}pre{background:#111620;padding:18px;border-radius:12px;white-space:pre-wrap}</style><h1>Keddy Data Center</h1><p>Database dashboard could not initialize.</p><pre>'.dcH($e->getMessage()).'</pre><a href="index.php" style="color:#c4b5fd">← Dashboard</a>';exit;}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Keddy • Data Center</title><style>
*{box-sizing:border-box}body{margin:0;background:#080b10;color:#f4f7fb;font:14px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}main{max-width:1450px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.brand{font-size:28px;font-weight:900}.brand span{color:#a78bfa}.btn{padding:10px 15px;border-radius:10px;background:#202734;color:#fff;text-decoration:none;font-weight:800}.hero,.card{background:#111620;border:1px solid #252d3b;border-radius:18px;padding:18px}.hero{background:linear-gradient(135deg,#121824,#171127);margin-bottom:16px}.hero h1{margin:0 0 6px;font-size:32px}.muted{color:#95a1b4}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:16px}.num{font-size:27px;font-weight:900}.label{font-size:11px;color:#94a0b4;text-transform:uppercase;letter-spacing:.06em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.tableWrap{overflow:auto;max-height:480px}.table{border-collapse:collapse;width:100%;min-width:900px}.table th,.table td{padding:10px;border-bottom:1px solid #252c39;text-align:left;vertical-align:top}.table th{font-size:11px;color:#aeb7c6;position:sticky;top:0;background:#111620;text-transform:uppercase}.mono{font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.clip{max-width:330px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#162b24;color:#86efac;font-size:11px;font-weight:800}.red{background:#402029;color:#fda4af}.yellow{background:#392d13;color:#facc15}.empty{text-align:center;padding:35px;color:#7e899c}.small{font-size:12px;color:#778296}.accent{color:#c4b5fd;text-decoration:none}.storage{display:flex;justify-content:space-between}.retained{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.retained .card{background:#0f141d}@media(max-width:1150px){.stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){main{padding:15px}.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.retained{grid-template-columns:1fr}.hero h1{font-size:26px}}
</style></head><body><main><div class="top"><div class="brand">🤖 Keddy <span>Data Center</span></div><a class="btn" href="index.php">← Dashboard</a></div>
<section class="hero"><h1>Everything Keddy has stored</h1><div class="muted">Managed channels, Keddy users, YouTube users, videos, live broadcasts, chat, moderation, comments aur snapshots.</div><div class="storage" style="margin-top:14px"><span><b>SQLite:</b> <span class="mono"><?=dcH(basename($dbFile))?></span></span><span><b><?=dcH(dcBytes($dbSize))?></b></span></div></section>
<div class="stats"><?php foreach([['managed_channels','Managed channels'],['moderated_channels','Moderated channels'],['registered_users','Keddy users'],['youtube_users','YouTube users'],['videos','Videos'],['chat_messages','Chat messages'],['moderation_events','Mod events'],['live_broadcasts','Live broadcasts'],['snapshots','Snapshots'],['channel_events','Channel events'],['comments_posted','Comments posted'],['comments_failed','Comments failed']] as $s):?><div class="card"><div class="label"><?=dcH($s[1])?></div><div class="num"><?=$stats[$s[0]]?></div></div><?php endforeach;?></div>
<section class="card"><h2>📺 Managed / Moderated Channels (<?=$stats['managed_channels']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Channel</th><th>Handle</th><th>Country</th><th>Subscribers</th><th>Views</th><th>Videos</th><th>Registered</th><th>Moderation</th><th>Last Seen</th></tr></thead><tbody><?php if(!$channels):?><tr><td colspan="9" class="empty">No channel data yet.</td></tr><?php else:foreach($channels as $r):?><tr><td><b><?=dcH($r['title'])?></b><div class="mono"><?=dcH($r['channel_id'])?></div></td><td><?=dcH($r['handle']?:$r['custom_url'])?></td><td><?=dcH($r['country']?:'—')?></td><td><?=dcH($r['subscriber_count']??'—')?></td><td><?=dcH($r['view_count']??'—')?></td><td><?=dcH($r['video_count']??'—')?></td><td><?=!empty($r['registered_user'])?'<span class="pill">YES</span>':'<span class="pill yellow">NO</span>'?></td><td><?=!empty($r['moderation_enabled'])?'<span class="pill">MOD ON</span>':'<span class="pill yellow">OFF</span>'?></td><td><?=dcH(dcTime($r['last_seen_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
<div class="grid"><section class="card"><h2>👤 YouTube Users (<?=$stats['youtube_users']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>User</th><th>Country</th><th>Subscribers</th><th>Views</th><th>Videos</th><th>Last Seen</th></tr></thead><tbody><?php if(!$users):?><tr><td colspan="6" class="empty">No users captured yet.</td></tr><?php else:foreach($users as $r):?><tr><td><b><?=dcH($r['display_name'])?></b><div class="mono"><?=dcH($r['channel_id'])?></div><div class="small clip"><?=dcH($r['description'])?></div></td><td><?=dcH($r['country']?:'—')?></td><td><?=dcH($r['subscriber_count']??'—')?></td><td><?=dcH($r['view_count']??'—')?></td><td><?=dcH($r['video_count']??'—')?></td><td><?=dcH(dcTime($r['last_seen_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section><section class="card"><h2>🎬 Videos (<?=$stats['videos']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Video</th><th>Channel</th><th>Published</th><th>Duration</th><th>Privacy</th><th>Type</th><th>Last Seen</th></tr></thead><tbody><?php if(!$videos):?><tr><td colspan="7" class="empty">No videos captured yet.</td></tr><?php else:foreach($videos as $r):?><tr><td><b class="clip"><?=dcH($r['title'])?></b><div class="small clip"><?=dcH($r['description'])?></div><div class="mono"><?=dcH($r['video_id'])?></div></td><td class="mono"><?=dcH($r['channel_id'])?></td><td><?=dcH($r['published_at']?:'—')?></td><td><?=dcH($r['duration']?:'—')?></td><td><?=dcH($r['privacy_status']?:'—')?></td><td><?=dcH($r['live_broadcast_content']?:'none')?></td><td><?=dcH(dcTime($r['last_seen_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section></div>
<div class="grid"><section class="card"><h2>💬 Live Chat (<?=$stats['chat_messages']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Author</th><th>Message</th><th>Published</th><th>Captured</th></tr></thead><tbody><?php if(!$chat):?><tr><td colspan="4" class="empty">No chat data yet.</td></tr><?php else:foreach($chat as $r):?><tr><td><b><?=dcH($r['author_name'])?></b><div class="mono"><?=dcH($r['author_channel_id'])?></div></td><td><?=dcH($r['message_text'])?></td><td><?=dcH($r['published_at']?:'—')?></td><td><?=dcH(dcTime($r['captured_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section><section class="card"><h2>🛡️ Moderation Events (<?=$stats['moderation_events']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Target</th><th>Action</th><th>Severity</th><th>Reason</th><th>Offense</th><th>When</th></tr></thead><tbody><?php if(!$mods):?><tr><td colspan="6" class="empty">No moderation events yet.</td></tr><?php else:foreach($mods as $r):?><tr><td><b><?=dcH($r['target_name'])?></b><div class="mono"><?=dcH($r['target_channel_id'])?></div></td><td><?=in_array($r['action'],['ban','timeout'],true)?'<span class="pill red">'.dcH(strtoupper($r['action'])).'</span>':'<span class="pill yellow">'.dcH(strtoupper($r['action'])).'</span>'?></td><td><?=dcH($r['severity'])?></td><td><?=dcH($r['reason'])?><div class="small"><?=dcH($r['hit'])?></div></td><td><?=dcH($r['offense']??'—')?></td><td><?=dcH(dcTime($r['created_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section></div>
<div class="grid"><section class="card"><h2>📡 Live Broadcasts (<?=$stats['live_broadcasts']?>)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Live</th><th>Channel</th><th>Chat ID</th><th>Start</th><th>Last Seen</th></tr></thead><tbody><?php if(!$lives):?><tr><td colspan="5" class="empty">No live broadcasts captured.</td></tr><?php else:foreach($lives as $r):?><tr><td><b><?=dcH($r['title'])?></b><div class="mono"><?=dcH($r['live_id'])?></div></td><td class="mono"><?=dcH($r['channel_id'])?></td><td class="mono"><?=dcH($r['live_chat_id'])?></td><td><?=dcH($r['actual_start']?:$r['published_at']?:'—')?></td><td><?=dcH(dcTime($r['last_seen_at']))?></td></tr><?php endforeach;endif;?></tbody></table></div></section><section class="card"><h2>💬 Keddy Comments (<?=$stats['comments_posted']?> posted / <?=$stats['comments_failed']?> failed)</h2><div class="tableWrap"><table class="table"><thead><tr><th>Registered User</th><th>Video</th><th>Comment</th><th>When</th><th>Status</th></tr></thead><tbody><?php if(!$comments):?><tr><td colspan="5" class="empty">No comments yet.</td></tr><?php else:foreach($comments as $r):?><tr><td><b><?=dcH($r['viewer_name'])?></b><div class="mono"><?=dcH($r['viewer_channel_id'])?></div></td><td><a class="accent" target="_blank" rel="noopener" href="<?=dcH($r['video_url'])?>"><?=dcH($r['video_title'])?></a><div class="mono"><?=dcH($r['video_id'])?></div></td><td class="clip"><?=dcH($r['comment_text'])?></td><td><?=dcH(dcTime($r['created_at']))?></td><td><?=$r['status']==='posted'?'<span class="pill">POSTED</span>':'<span class="pill red">FAILED</span>'?></td></tr><?php endforeach;endif;?></tbody></table></div></section></div>
<section class="card" style="margin-top:16px"><h2>💾 Future Expansion Data</h2><div class="retained"><div class="card"><b>Channels</b><div class="muted">Profile, counters, topics, branding, status, raw snapshots.</div></div><div class="card"><b>Users</b><div class="muted">Captured YouTube channel metadata and activity-linked identity.</div></div><div class="card"><b>Videos</b><div class="muted">Metadata, descriptions, tags/statistics, privacy/status.</div></div><div class="card"><b>Live + Chat</b><div class="muted">Broadcast identity, chat messages, authors and timestamps.</div></div><div class="card"><b>Moderation</b><div class="muted">Target, action, severity, reason, offense and event history.</div></div><div class="card"><b>Comments</b><div class="muted">Registered target, video, exact comment text, time and result.</div></div></div></section>
</main></body></html>
