<?php
declare(strict_types=1);
session_start();
require __DIR__.'/bot.php';
if(empty($_SESSION['keddy_heartbeat_token']))$_SESSION['keddy_heartbeat_token']=bin2hex(random_bytes(24));
$heartbeatToken=$_SESSION['keddy_heartbeat_token'];$error='';$notice='';
if(isset($_GET['connected']))$notice='Your YouTube channel is connected. Keddy will speak as Keddy Bot BTS.';
if(isset($_GET['bot_connected']))$notice='Keddy Bot BTS is connected. Future streamer connections can use this same bot identity.';
if(isset($_GET['welcomed'])&&$_GET['welcomed']==='1')$notice='🤖 Keddy Bot BTS joined the live and sent the welcome message.';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{$a=$_POST['action']??'';if($a==='start')startS();elseif($a==='stop')stopS();elseif($a==='next')nextS();elseif($a==='reconnect'){sv('oauth','');sv('oauth_channel_id','');sv('oauth_channel_title','');sv('chat_token','');sv('bot_welcome_live_id','');header('Location: oauth.php');exit;}elseif($a==='save'){
  sv('interval',(string)max(2,(int)$_POST['interval']));sv('duration',(string)max(2,(int)$_POST['duration']));
  $raw=preg_split('/\r\n|\r|\n/',trim((string)$_POST['tasks']));$raw=array_values(array_filter(array_map('trim',$raw)));if($raw)sj('tasks',$raw);
  $notice='Keddy settings saved.';
 }}catch(Throwable$e){$error=$e->getMessage();}}
$connected=!!gv('oauth');$botConnected=!!gv('bot_oauth');$connectedChannel=gv('oauth_channel_title');$ss=session();$tasks=tasks();
function h($x):string{return htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');}
$lastSocial=(int)gv('social_timer_last','0');$socialLeft=max(0,KEDDY_SOCIAL_INTERVAL-(time()-$lastSocial));
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Keddy Bot</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0b0d12;color:#f4f6fb;font:15px system-ui}main{max-width:1100px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.brand{font-size:28px;font-weight:800}.brand span{color:#8b5cf6}.pill,.stat,.code{background:#151923;border-radius:12px;padding:10px 14px}.grid{display:grid;grid-template-columns:1.4fr .9fr;gap:18px}.card{background:#121620;border:1px solid #252b38;border-radius:18px;padding:22px}.hero{min-height:230px}.h1{font-size:34px;margin:8px 0}.muted{color:#9aa3b5}.stats{display:flex;gap:12px;margin:18px 0}.stat{flex:1}.num{font-size:25px;font-weight:800}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:11px;padding:12px 18px;background:#7c3aed;color:white;font-weight:700;cursor:pointer;text-decoration:none}.secondary{background:#252b38}.danger{background:#b4233d}.notice,.error{padding:12px;border-radius:10px;margin-bottom:16px}.notice{background:#123b2a}.error{background:#4a1721}label{display:block;margin:16px 0 7px;font-weight:700}input,textarea,select{width:100%;background:#0b0e14;border:1px solid #2b3240;color:#fff;border-radius:10px;padding:11px;font:inherit}textarea{min-height:260px}.footer{margin-top:18px;color:#727b8c;font-size:13px}.identity{margin-top:10px;padding:10px 12px;border-radius:10px;background:#0f131b;border:1px solid #252b38}.bot-ok{color:#86efac}.bot-warn{color:#fbbf24}.cmdgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:12px}.cmd{background:#0f131b;border:1px solid #252b38;border-radius:10px;padding:12px}.cmd b{color:#c4b5fd}.timer{display:flex;align-items:center;justify-content:space-between;gap:12px;background:#0f131b;border:1px solid #252b38;border-radius:12px;padding:14px;margin-top:12px}.timer .big{font-size:26px;font-weight:800}@media(max-width:800px){main{padding:16px}.grid{grid-template-columns:1fr}.h1{font-size:28px}.stats{flex-direction:column}.cmdgrid{grid-template-columns:1fr}}</style></head>
<body><main>
<div class="top"><div class="brand">🤖 Keddy <span>Bot</span></div><div class="pill">● <?=$connected?'YouTube Connected':'YouTube Not Connected'?></div></div>
<?php if($notice):?><div class="notice"><?=h($notice)?></div><?php endif;?>
<?php if($error):?><div class="error">⚠️ <?=h($error)?></div><?php endif;?>
<div class="grid"><section class="card hero"><div class="muted">SmartToolz • YouTube Live Assistant</div><h1 class="h1">Keddy Bot BTS for every streamer.</h1><p class="muted">Any streamer can connect their own YouTube channel. Keddy uses the dedicated <strong>Keddy Bot BTS</strong> identity for chat messages.</p>
<?php if($connected):?><div class="identity">Streamer connected as: <strong><?=h($connectedChannel?:'YouTube channel')?></strong><br><span class="<?=$botConnected?'bot-ok':'bot-warn'?>">● Keddy Bot BTS: <?=$botConnected?'Ready':'One-time bot connection required'?></span></div><?php endif;?>
<div class="stats"><div class="stat"><div class="muted">Mode</div><div class="num">WELCOME</div></div><div class="stat"><div class="muted">Tasks</div><div class="num">OFF</div></div><div class="stat"><div class="muted">Bot</div><div class="num">BTS</div></div></div>
<div class="actions"><?php if(!$connected):?><a class="btn" href="oauth.php">Connect YouTube</a><?php else:?><form method="post"><input type="hidden" name="action" value="start"><button class="btn">▶ Join Live &amp; Start Timer</button></form><form method="post"><input type="hidden" name="action" value="stop"><button class="btn danger">■ Stop Timer</button></form><form method="post"><input type="hidden" name="action" value="reconnect"><button class="btn secondary">↻ Reconnect Streamer</button></form><?php endif;?><?php if(!$botConnected):?><a class="btn secondary" href="bot-oauth.php">Connect Keddy Bot BTS (one time)</a><?php endif;?></div></section>
<aside class="card"><h2>Commands</h2><div class="muted">Prefilled commands are ready in the bot:</div><div class="cmdgrid"><div class="cmd"><b>!hello</b><br><span class="muted">Bot hello</span></div><div class="cmd"><b>!like</b><br><span class="muted">Ask for a like</span></div><div class="cmd"><b>!share</b><br><span class="muted">Ask viewers to share</span></div><div class="cmd"><b>!timer</b><br><span class="muted">Show timer status</span></div><div class="cmd"><b>!status</b><br><span class="muted">Show bot status</span></div><div class="cmd"><b>!help</b><br><span class="muted">Show all commands</span></div></div><div class="timer"><div><div class="muted">❤️ Like + 🔗 Share timer</div><div class="big" id="socialCountdown">--:--</div></div><div class="muted">Every 2 minutes</div></div></aside></div>
<section class="card" style="margin-top:18px"><h2>How Keddy behaves</h2><div class="cmdgrid"><div class="cmd"><b>👋 Every commenter</b><br><span class="muted">Keddy welcomes the viewer by their YouTube display name, with a cooldown per viewer to avoid chat spam.</span></div><div class="cmd"><b>❤️ Every 2 minutes</b><br><span class="muted">Keddy posts a rotating Like + Share reminder.</span></div><div class="cmd"><b>🎯 Tasks</b><br><span class="muted">Automatic instructor tasks are OFF right now.</span></div><div class="cmd"><b>🛡️ Moderator</b><br><span class="muted">Keddy Bot BTS is added to the stream chat as moderator when the API permits it.</span></div></div></section>
<section class="card" style="margin-top:18px"><h2>Timer & instructor settings</h2><form method="post"><input type="hidden" name="action" value="save"><label>Like/Share timer interval (currently fixed at 2 minutes)</label><input type="number" value="2" disabled><label>Task interval (reserved for future task mode)</label><input type="number" min="2" name="interval" value="<?=h($ss['interval'])?>"><label>Session duration (reserved for future task mode)</label><input type="number" min="2" name="duration" value="<?=h($ss['duration'])?>"><label>Prefilled seated task list</label><textarea name="tasks"><?=h(implode("\n",$tasks))?></textarea><div class="actions" style="margin-top:12px"><button class="btn">Save Settings</button></div></form><div class="footer">Current live behavior: welcome viewers + Like/Share reminder every 2 minutes. Automatic seated tasks remain OFF.</div></section>
</main>
<script>
let left=<?=$socialLeft?>;const el=document.getElementById('socialCountdown');function render(){const s=Math.max(0,left);el.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');left=Math.max(0,left-1);}render();setInterval(render,1000);
const active=<?= $ss['active']?'true':'false' ?>;if(active){const token=<?=json_encode($heartbeatToken)?>;const tick=()=>fetch('cron.php?heartbeat=1&token='+encodeURIComponent(token),{cache:'no-store'}).catch(()=>{});tick();setInterval(tick,30000);}
</script></body></html>
