<?php
declare(strict_types=1);
session_start();
require __DIR__.'/bot.php';
if(empty($_SESSION['keddy_heartbeat_token']))$_SESSION['keddy_heartbeat_token']=bin2hex(random_bytes(24));
$heartbeatToken=$_SESSION['keddy_heartbeat_token'];$error='';$notice='';
if(isset($_GET['connected']))$notice='Your YouTube channel is connected. Keddy will speak as Keddy Bot BTS.';
if(isset($_GET['bot_connected']))$notice='Keddy Bot BTS is connected. Future streamer connections can use this same bot identity.';
if(isset($_GET['welcomed'])&&$_GET['welcomed']==='1')$notice='🤖 Keddy Bot BTS joined the live and sent the welcome message.';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{$a=$_POST['action']??'';if($a==='start')startS();elseif($a==='stop')stopS();elseif($a==='next')nextS();elseif($a==='reconnect'){sv('oauth','');sv('oauth_channel_id','');sv('oauth_channel_title','');sv('chat_token','');sv('bot_welcome_live_id','');header('Location: oauth.php');exit;}elseif($a==='save'){sv('interval',(string)max(2,(int)$_POST['interval']));sv('duration',(string)max(2,(int)$_POST['duration']));$raw=preg_split('/\r\n|\r|\n/',trim((string)$_POST['tasks']));$raw=array_values(array_filter(array_map('trim',$raw)));if($raw)sj('tasks',$raw);$notice='Keddy settings saved.';}}catch(Throwable$e){$error=$e->getMessage();}}
$connected=!!gv('oauth');$botConnected=!!gv('bot_oauth');$connectedChannel=gv('oauth_channel_title');$ss=session();$tasks=tasks();
function h($x):string{return htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Keddy Bot</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0b0d12;color:#f4f6fb;font:15px system-ui}main{max-width:1100px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.brand{font-size:28px;font-weight:800}.brand span{color:#8b5cf6}.pill,.stat,.code{background:#151923;border-radius:12px;padding:10px 14px}.grid{display:grid;grid-template-columns:1.4fr .9fr;gap:18px}.card{background:#121620;border:1px solid #252b38;border-radius:18px;padding:22px}.hero{min-height:230px}.h1{font-size:34px;margin:8px 0}.muted{color:#9aa3b5}.stats{display:flex;gap:12px;margin:18px 0}.stat{flex:1}.num{font-size:25px;font-weight:800}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:11px;padding:12px 18px;background:#7c3aed;color:white;font-weight:700;cursor:pointer;text-decoration:none}.secondary{background:#252b38}.danger{background:#b4233d}.notice,.error{padding:12px;border-radius:10px;margin-bottom:16px}.notice{background:#123b2a}.error{background:#4a1721}label{display:block;margin:16px 0 7px;font-weight:700}input,textarea{width:100%;background:#0b0e14;border:1px solid #2b3240;color:#fff;border-radius:10px;padding:11px;font:inherit}textarea{min-height:260px}.footer{margin-top:18px;color:#727b8c;font-size:13px}.identity{margin-top:10px;padding:10px 12px;border-radius:10px;background:#0f131b;border:1px solid #252b38}.bot-ok{color:#86efac}.bot-warn{color:#fbbf24}@media(max-width:800px){main{padding:16px}.grid{grid-template-columns:1fr}.h1{font-size:28px}.stats{flex-direction:column}}</style></head>
<body><main>
<div class="top"><div class="brand">🤖 Keddy <span>Bot</span></div><div class="pill">● <?=$connected?'YouTube Connected':'YouTube Not Connected'?></div></div>
<?php if($notice):?><div class="notice"><?=h($notice)?></div><?php endif;?>
<?php if($error):?><div class="error">⚠️ <?=h($error)?></div><?php endif;?>
<div class="grid"><section class="card hero"><div class="muted">SmartToolz • YouTube Live Instructor</div><h1 class="h1">Your live, with Keddy Bot BTS.</h1><p class="muted">Any streamer can connect their own YouTube channel. Keddy uses the dedicated <strong>Keddy Bot BTS</strong> identity for chat messages.</p>
<?php if($connected):?><div class="identity">Streamer connected as: <strong><?=h($connectedChannel?:'YouTube channel')?></strong><br><span class="<?=$botConnected?'bot-ok':'bot-warn'?>">● Keddy Bot BTS: <?=$botConnected?'Ready':'One-time bot connection required'?></span></div><?php endif;?>
<div class="stats"><div class="stat"><div class="muted">Mode</div><div class="num">WELCOME</div></div><div class="stat"><div class="muted">Tasks</div><div class="num">OFF</div></div><div class="stat"><div class="muted">Bot</div><div class="num">BTS</div></div></div>
<div class="actions"><?php if(!$connected):?><a class="btn" href="oauth.php">Connect YouTube</a><?php else:?><form method="post"><input type="hidden" name="action" value="start"><button class="btn">▶ Join Live &amp; Welcome</button></form><form method="post"><input type="hidden" name="action" value="reconnect"><button class="btn secondary">↻ Reconnect Streamer</button></form><?php endif;?><?php if(!$botConnected):?><a class="btn secondary" href="bot-oauth.php">Connect Keddy Bot BTS (one time)</a><?php endif;?></div></section>
<aside class="card"><h2>Current mode</h2><div class="code">🤖 Welcome only</div><div class="muted">Only one welcome message is enabled right now.</div><div class="code">Tasks: OFF</div><div class="muted">No automatic tasks are posted.</div><div class="code">Moderator: AUTO</div><div class="muted">Keddy Bot BTS is added as a moderator when the streamer is connected and the API permits it.</div></aside></div>
<section class="card" style="margin-top:18px"><h2>Instructor settings</h2><form method="post"><input type="hidden" name="action" value="save"><label>Task interval (minutes)</label><input type="number" min="2" name="interval" value="<?=h($ss['interval'])?>"><label>Session duration (minutes)</label><input type="number" min="2" name="duration" value="<?=h($ss['duration'])?>"><label>Seated task list — one task per line</label><textarea name="tasks"><?=h(implode("\n",$tasks))?></textarea><div class="actions" style="margin-top:12px"><button class="btn">Save Settings</button></div></form><div class="footer">Task automation is intentionally disabled for now. OAuth/API secrets stay outside Git.</div></section>
</main></body></html>
