<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free Regex Tester Online','description'=>'Test regular expressions against text instantly in your browser. See matches and capture groups with SmartToolz.','url'=>'https://smarttoolz.in/tools/regex-tester/'];
smarttoolz_tool_page_start($tool);
?>
<main class="regex-page"><section class="tool-head"><span class="eyebrow">REGEX TESTER</span><h1>Regular Expression Tester</h1><p>Test your regex patterns instantly and see every match without uploading your text.</p></section><section class="regex-card"><label>Regular expression<input id="pattern" placeholder="e.g. \b\w+@\w+\.\w+\b" spellcheck="false"></label><label>Flags<input id="flags" value="g" placeholder="gim"></label><label>Test text<textarea id="text" placeholder="Enter text to test..."></textarea></label><div class="actions"><button id="test" class="primary">Test Regex</button><button id="clear">Clear</button></div><div class="status" id="status">Ready</div><div class="matches" id="matches"></div></section><section class="info-grid"><article><h2>What is regex?</h2><p>Regular expressions are patterns used to search, validate and manipulate text.</p></article><article><h2>Private by design</h2><p>Your pattern and test text stay in your browser during the comparison.</p></article></section></main>
<style>.regex-page{width:min(900px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.regex-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.regex-card label{display:grid;gap:7px;margin-bottom:14px;color:#344054;font-size:11px;font-weight:800}.regex-card input,.regex-card textarea{box-sizing:border-box;width:100%;padding:12px;border:1px solid #dfe3eb;border-radius:11px;background:#fcfdff;color:#172033;font:13px ui-monospace,SFMono-Regular,Menlo,monospace;outline:0}.regex-card textarea{min-height:210px;resize:vertical;line-height:1.6}.regex-card input:focus,.regex-card textarea:focus{border-color:#8d80ff}.actions{display:flex;gap:9px;margin:3px 0 12px}.actions button{padding:10px 16px;border:1px solid #dfe3eb;border-radius:10px;background:#fff;color:#344054;font-size:10px;font-weight:900;cursor:pointer}.actions .primary{border:0;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff}.status{padding:10px 12px;border-radius:10px;background:#f5f6fa;color:#667085;font-size:10px}.matches{margin-top:10px;display:grid;gap:7px}.match{padding:11px 13px;border:1px solid #e7eaf0;border-radius:10px;background:#fafbff;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-word}.match strong{display:block;margin-bottom:5px;color:#5541ff;font:10px Arial,sans-serif}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:650px){.regex-page{width:calc(100% - 20px)}.regex-card{padding:16px}.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{const p=document.getElementById('pattern'),f=document.getElementById('flags'),t=document.getElementById('text'),s=document.getElementById('status'),m=document.getElementById('matches');document.getElementById('test').onclick=()=>{m.innerHTML='';try{const r=new RegExp(p.value,f.value),str=t.value;if(!p.value){s.textContent='Enter a regular expression.';return}if(f.value.includes('g')){const found=[...str.matchAll(r)];s.textContent=`${found.length} match${found.length===1?'':'es'} found.`;found.forEach((x,i)=>{const d=document.createElement('div');d.className='match';d.innerHTML=`<strong>Match ${i+1} · index ${x.index}</strong>`;const q=document.createElement('span');q.textContent=x[0];d.append(q);m.append(d)})}else{const x=r.exec(str);s.textContent=x?`Match found at index ${x.index}.`:'No match found.';if(x){const d=document.createElement('div');d.className='match';d.textContent=x[0];m.append(d)}}}catch(e){s.textContent='Invalid regular expression or flags.'}};document.getElementById('clear').onclick=()=>{p.value='';t.value='';m.innerHTML='';s.textContent='Ready'}})();</script>
<?php smarttoolz_tool_page_end(); ?>
