<?php
declare(strict_types=1);

function lh_course16_lesson35_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-35') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Are Startup Apps?</h2><p>Startup apps are programs configured to launch automatically when you sign in to Windows. Some are useful, while others simply add background activity and make startup slower.</p><div class="lh-callout"><strong>Important:</strong> Disabling a startup app normally stops automatic launching; it does not uninstall the program.</div></section>
<section class="lh-section"><h2>Open Startup Apps</h2><ol><li>Open <strong>Task Manager</strong> with Ctrl + Shift + Esc.</li><li>Select <strong>Startup apps</strong>.</li><li>Review the app name, status and startup impact when shown.</li><li>Right-click an app for available actions.</li></ol></section>
<section class="lh-section"><h2>What Does Startup Impact Mean?</h2><p>Windows can show an estimated startup impact for supported applications. It helps you decide which optional apps deserve attention, but it is not a complete measurement of overall PC performance.</p><table class="table table-bordered"><thead><tr><th>App type</th><th>Typical approach</th></tr></thead><tbody><tr><td>Security software</td><td>Keep protection enabled unless you know a different security setup is active.</td></tr><tr><td>Cloud sync</td><td>Keep enabled if automatic synchronization is important to you.</td></tr><tr><td>Chat/music launcher</td><td>Often optional if you do not need it immediately after sign-in.</td></tr><tr><td>Unknown driver utility</td><td>Identify it before changing its startup status.</td></tr></tbody></table></section>
<section class="lh-section"><h2>How to Disable an Unnecessary App</h2><ol><li>Choose an app you recognize.</li><li>Confirm you do not need it to start automatically.</li><li>Select <strong>Disable</strong>.</li><li>Restart later and see whether startup improves.</li><li>If something you need no longer launches automatically, you can re-enable it.</li></ol></section>
<section class="lh-section"><h2>What You Should Not Disable Blindly</h2><ul><li>Security and antivirus protection.</li><li>Hardware or touchpad support you rely on.</li><li>Accessibility utilities you use.</li><li>Software whose purpose you cannot identify.</li><li>Critical enterprise or management tools on a work computer.</li></ul><div class="lh-callout"><strong>Beginner rule:</strong> Unknown does not mean unnecessary.</div></section>
<section class="lh-section"><h2>Startup Apps vs Scheduled Tasks</h2><p>Not every background program appears as a normal Startup app. Windows and applications may also use services or scheduled tasks. If a program keeps returning after you disable startup, investigate what component is actually launching it rather than repeatedly changing unrelated settings.</p></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Open Task Manager → Startup apps.</li><li>List five entries you recognize.</li><li>Mark which ones you actually need immediately after sign-in.</li><li>Choose one clearly optional app and disable it.</li><li>Restart and compare startup behavior.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What is a startup app?</li><li>Does disabling an app uninstall it?</li><li>Why should unknown entries be investigated first?</li><li>Why should security software be treated differently?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>A program configured to launch automatically at sign-in.</li><li>No.</li><li>You cannot safely decide whether it is unnecessary without knowing its purpose.</li><li>It may be responsible for real-time protection.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Startup Apps is a control panel for automatic launching. Disable only recognized, unnecessary apps and keep essential security and hardware components intact.</strong></div></section>
HTML;
}
