<?php
declare(strict_types=1);

function lh_course16_lesson46_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-46') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Is Phishing?</h2><p>Phishing is a scam technique in which an attacker pretends to be a trusted person or organization and tries to make you reveal information, click a malicious link, open an attachment or send money.</p></section>
<section class="lh-section"><h2>Common Warning Signs</h2><ul><li>Urgent threats such as “act now or your account will close”.</li><li>Unexpected requests for passwords, codes or payment details.</li><li>Links whose destination does not match the claimed organization.</li><li>Unusual spelling, grammar or formatting.</li><li>Unexpected attachments.</li><li>Requests to bypass normal security procedures.</li></ul><p>Microsoft specifically recommends slowing down when a message creates urgency and verifying the sender through another channel. citeturn0search2</p></section>
<section class="lh-section"><h2>Check the Link Safely</h2><ol><li>Do not click immediately.</li><li>Inspect the displayed link destination when possible.</li><li>Instead of using the message link, open the organization's official website yourself.</li><li>Use a trusted phone number or official contact method to verify an unusual request.</li></ol></section>
<section class="lh-section"><h2>Never Share Verification Codes</h2><p>One-time codes and authentication prompts can be valuable to attackers. If someone unexpectedly asks you to read a code to them, stop and verify the request. A legitimate support person should not need you to hand over a secret authentication code through an unsolicited message.</p></section>
<section class="lh-section"><h2>What to Do With a Suspicious Message</h2><ol><li>Do not click links or attachments.</li><li>Do not reply with personal information.</li><li>Verify independently if the message might be legitimate.</li><li>Use your mail provider's phishing-report function when available.</li><li>Delete the message after reporting when appropriate.</li></ol></section>
<section class="lh-section"><h2>Phishing Can Happen Anywhere</h2><p>Phishing is not limited to email. It can appear in text messages, social media, collaboration tools, gaming chats and phone calls. The same principle applies: pause, verify and avoid giving secrets to an unverified requester.</p></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Take a harmless example message.</li><li>Underline any urgency, unusual sender information or suspicious link.</li><li>Write how you would verify it without using the message's contact details.</li><li>List what information you would never send through an unsolicited message.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What is phishing?</li><li>Why is urgency a warning sign?</li><li>How can you verify a suspicious bank message?</li><li>Should you share a one-time authentication code with an unsolicited caller?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>A deceptive attempt to steal information or make you perform a harmful action.</li><li>It is designed to stop you from thinking and verifying.</li><li>Open the bank's official site/app yourself or use an official contact method.</li><li>No.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Phishing succeeds when people react quickly. Slow down, verify independently, never surrender secrets through unsolicited requests, and report suspicious messages.</strong></div></section>
HTML;
}
