<?php
declare(strict_types=1);

function lh_course16_lesson36_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-36') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Are App Permissions?</h2><p>App permissions control which device features or information an application can access. Examples include the camera, microphone, location, contacts, notifications and files.</p><div class="lh-callout"><strong>Think of permissions as doors:</strong> an app should get access only to the doors it actually needs.</div></section>
<section class="lh-section"><h2>Where to Review Permissions</h2><p>In Windows 11, open <strong>Settings → Privacy & security</strong> and review the available app-permission categories. Windows versions can use slightly different labels or layouts.</p><p>Review permissions for the specific app and category instead of assuming every app needs every permission.</p></section>
<section class="lh-section"><h2>Common Permission Types</h2><table class="table table-bordered"><thead><tr><th>Permission</th><th>Example reason an app may need it</th></tr></thead><tbody><tr><td>Camera</td><td>Video calls or scanning.</td></tr><tr><td>Microphone</td><td>Voice calls, recording or voice input.</td></tr><tr><td>Location</td><td>Maps or location-aware services.</td></tr><tr><td>Contacts</td><td>Communication or contact-based features.</td></tr><tr><td>Notifications</td><td>Alerts and reminders.</td></tr><tr><td>Files</td><td>Opening, saving or managing user documents.</td></tr></tbody></table></section>
<section class="lh-section"><h2>How to Make a Permission Decision</h2><ol><li>Identify the app.</li><li>Ask what feature you are trying to use.</li><li>Decide whether the requested permission makes sense for that feature.</li><li>Allow access when it is necessary and you trust the app.</li><li>Deny or restrict access when it is unnecessary.</li><li>Test the app; some features may stop working if their required permission is denied.</li></ol></section>
<section class="lh-section"><h2>Permissions Are Not the Same as Trust</h2><p>Granting a permission does not make an app trustworthy. Check where the application came from, keep it updated, and avoid installing software from suspicious sources. Likewise, denying a permission does not prove an app is malicious.</p></section>
<section class="lh-section"><h2>Browser Permissions</h2><p>Websites can also request access to features such as location, camera, microphone or notifications. A website permission should be considered separately from Windows app permissions. If a site does not need a feature, do not grant it.</p></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Open Windows Settings and find Privacy & security.</li><li>Review camera and microphone access.</li><li>Identify two apps that use each feature.</li><li>Ask whether each access is necessary for what you use the app for.</li><li>Do not change an essential permission without understanding the effect.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What does an app permission control?</li><li>Name three common permission categories.</li><li>Why should permissions be reviewed based on the feature being used?</li><li>Does permission alone prove an app is trustworthy?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>Access to selected device features or information.</li><li>Camera, microphone and location, for example.</li><li>It helps prevent unnecessary access while keeping required features working.</li><li>No. Source, reputation, updates and behavior also matter.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Give apps the access they need—not unlimited access by default. Review permissions regularly and connect every permission to a real feature you use.</strong></div></section>
HTML;
}
