<?php
declare(strict_types=1);

function lh_course16_lesson45_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-45') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Is Malware?</h2><p>Malware is malicious software designed to damage systems, disrupt activity, spy on users, steal information or perform other unwanted actions. Common categories include viruses, trojans, ransomware, spyware and other malicious programs.</p></section>
<section class="lh-section"><h2>Warning Signs</h2><ul><li>Unexpected pop-ups or redirects.</li><li>Sudden unexplained slowdowns.</li><li>Unknown applications or browser extensions.</li><li>Unusual network or data usage.</li><li>Security software warnings.</li><li>Files becoming inaccessible or unexpectedly renamed.</li></ul><p>One symptom alone does not prove infection; it is a reason to investigate.</p></section>
<section class="lh-section"><h2>Windows Security</h2><p>Windows includes the Windows Security app with Microsoft Defender Antivirus and other protection features. Microsoft recommends keeping security protection active and updated.</p><p>For a manual check, open <strong>Windows Security → Virus & threat protection → Quick scan</strong>. Deeper scan options are available when needed.</p></section>
<section class="lh-section"><h2>Safe Malware Response</h2><ol><li>Do not click suspicious pop-ups.</li><li>Disconnect from a network if you have a strong reason to suspect active compromise and need to contain it.</li><li>Open Windows Security directly rather than through a suspicious message.</li><li>Run a scan.</li><li>Follow the security product's recommended remediation.</li><li>Change important passwords from a known-clean device if account theft is suspected.</li><li>Restore important files from a clean backup when necessary.</li></ol></section>
<section class="lh-section"><h2>Prevent Malware</h2><ul><li>Keep Windows, browsers and apps updated.</li><li>Install software from trusted sources.</li><li>Be cautious with unexpected attachments and downloads.</li><li>Do not disable real-time protection just to install unknown software.</li><li>Keep important files backed up.</li></ul><div class="lh-callout"><strong>Never trust a “virus detected” browser pop-up that tells you to call an unknown phone number or install a remote-control tool.</strong></div></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Open Windows Security from Start.</li><li>Locate Virus & threat protection.</li><li>Check that protection status is healthy.</li><li>Learn where Quick scan and Scan options are located.</li><li>Do not disable protection during the exercise.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What is malware?</li><li>Name two warning signs.</li><li>Where can you start a Defender scan?</li><li>Why should security software remain updated?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>Malicious software.</li><li>Unexpected pop-ups, redirects or unexplained slowdowns, for example.</li><li>Windows Security → Virus & threat protection.</li><li>New threats require current protection intelligence and fixes.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Stay updated, keep real-time protection active, download from trusted sources and investigate unusual behavior with Windows Security instead of suspicious pop-ups.</strong></div></section>
HTML;
}
