<?php
declare(strict_types=1);

function lh_course16_lesson49_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-49') return null;
    return <<<'HTML'
<section class="lh-section"><h2>Why Have a Personal Backup Plan?</h2><p>Important files can disappear because of accidental deletion, hardware failure, theft, malware or a damaged device. A backup gives you another copy that can be restored when something goes wrong.</p></section>
<section class="lh-section"><h2>Decide What Matters</h2><p>Start by listing the files you cannot easily recreate: photos, documents, project files, certificates, records and other personal work. Reinstallable applications are usually less urgent than irreplaceable data.</p></section>
<section class="lh-section"><h2>Choose Backup Locations</h2><table class="table table-bordered"><thead><tr><th>Location</th><th>Strength</th></tr></thead><tbody><tr><td>Cloud storage</td><td>Convenient access and can support version history.</td></tr><tr><td>External drive</td><td>Useful for large offline collections.</td></tr><tr><td>Network storage</td><td>Useful for shared or managed environments.</td></tr></tbody></table><p>For important information, consider more than one backup location so a single failure does not destroy every copy.</p></section>
<section class="lh-section"><h2>Backup Is Different From Sync</h2><p>Synchronization keeps locations aligned, while a backup is intended to provide a recoverable copy. If an unwanted deletion is synchronized immediately, the deleted item may disappear from multiple locations. Version history or a separate backup can provide another recovery path.</p></section>
<section class="lh-section"><h2>Create a Simple Schedule</h2><ol><li><strong>Daily:</strong> Sync or back up active project files when practical.</li><li><strong>Weekly:</strong> Check that important backups are completing.</li><li><strong>Monthly:</strong> Test restoring a small file.</li><li><strong>Occasionally:</strong> Review whether the backup still covers your important data.</li></ol></section>
<section class="lh-section"><h2>Test Your Backups</h2><p>A backup is valuable only if it can be restored. Select a harmless file and practice restoring it to another folder. Confirm that the restored file opens correctly.</p><div class="lh-callout"><strong>Never assume “backup complete” means “recovery guaranteed.” Test it.</strong></div></section>
<section class="lh-section"><h2>Protect the Backup</h2><ul><li>Use strong account security for cloud backups.</li><li>Protect external drives from loss and physical damage.</li><li>Disconnect offline backup drives when they are not being used if appropriate.</li><li>Do not keep every backup permanently connected to the same computer.</li></ul></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>List five files you would hate to lose.</li><li>Choose a primary backup location.</li><li>Choose a second recovery option if appropriate.</li><li>Set a realistic backup schedule.</li><li>Practice restoring one non-critical file.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>Why are backups important?</li><li>How is sync different from backup?</li><li>Why should backups be tested?</li><li>Why can more than one backup location be useful?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>They provide copies that can help recover lost or damaged data.</li><li>Sync mirrors changes; a backup is intended to provide a recoverable copy.</li><li>To confirm that recovery actually works.</li><li>A single device or service can fail, be lost or be compromised.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Your backup plan should answer three questions: What matters? Where is it backed up? How will I restore it? A simple tested plan is better than an impressive plan you never use.</strong></div></section>
HTML;
}
