<?php
declare(strict_types=1);

function lh_course16_lesson50_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-50') return null;
    return <<<'HTML'
<section class="lh-section"><h2>Your Computer Skills Project</h2><p>This final lesson turns the course into a practical project. You will organize files, use Windows settings, practice safe sharing, review security and build a backup habit.</p><div class="lh-callout"><strong>Goal:</strong> Finish with a repeatable computer workflow—not just a list of facts you memorized.</div></section>
<section class="lh-section"><h2>Part 1 — Organize a Project Folder</h2><ol><li>Create a project folder with a clear name.</li><li>Add subfolders such as <strong>Notes</strong>, <strong>Assets</strong>, <strong>Drafts</strong> and <strong>Final</strong>.</li><li>Create three harmless practice files.</li><li>Rename them using a consistent naming style.</li></ol></section>
<section class="lh-section"><h2>Part 2 — Capture and Package</h2><ol><li>Take a screenshot of the project folder using Snipping Tool.</li><li>Save the screenshot with a descriptive filename.</li><li>Create a ZIP archive of the practice project.</li><li>Extract the ZIP into a separate test folder.</li><li>Confirm the files are intact.</li></ol></section>
<section class="lh-section"><h2>Part 3 — Check Your Windows Setup</h2><p>Review the major areas learned in this course: Settings, Accessibility, Date & time, language, startup apps, application permissions and Task Manager. Do not change important settings simply for the project; the goal is to know where they are and what they do.</p></section>
<section class="lh-section"><h2>Part 4 — Security Check</h2><ol><li>Open Windows Security.</li><li>Locate Virus & threat protection.</li><li>Review whether security protection is active.</li><li>Identify the location of Quick scan.</li><li>Review one example phishing message and list its warning signs.</li><li>Review your public-computer safety checklist.</li></ol></section>
<section class="lh-section"><h2>Part 5 — Safe Sharing Plan</h2><p>Imagine that a classmate or coworker needs the project. Decide whether they need view or edit access. Write down the recipient, file, permission and a plan for removing access after the project ends.</p></section>
<section class="lh-section"><h2>Part 6 — Backup Plan</h2><ol><li>Choose the project files that matter.</li><li>Choose a backup location.</li><li>Create the backup.</li><li>Restore one harmless file to verify the process.</li><li>Write down when you will repeat the backup.</li></ol></section>
<section class="lh-section"><h2>Final Skills Checklist</h2><table class="table table-bordered"><thead><tr><th>Skill</th><th>Can I do it?</th></tr></thead><tbody><tr><td>Use Task Manager to inspect resource usage</td><td>☐</td></tr><tr><td>Review and manage startup apps</td><td>☐</td></tr><tr><td>Find Windows Settings categories</td><td>☐</td></tr><tr><td>Use accessibility tools</td><td>☐</td></tr><tr><td>Correct date/time and language settings</td><td>☐</td></tr><tr><td>Take and safely share screenshots</td><td>☐</td></tr><tr><td>Open and manage PDFs</td><td>☐</td></tr><tr><td>Create/extract ZIP archives</td><td>☐</td></tr><tr><td>Organize documents</td><td>☐</td></tr><tr><td>Share files with appropriate permissions</td><td>☐</td></tr><tr><td>Recognize malware and phishing warning signs</td><td>☐</td></tr><tr><td>Use public computers more safely</td><td>☐</td></tr><tr><td>Review privacy settings</td><td>☐</td></tr><tr><td>Maintain a tested backup plan</td><td>☐</td></tr></tbody></table></section>
<section class="lh-section"><h2>Final Reflection</h2><ol><li>Which computer task used to feel difficult but now feels simple?</li><li>Which security habit will you use every day?</li><li>Which skill needs more practice?</li><li>What will you add to your personal backup plan?</li></ol></section>
<section class="lh-section"><h2>Course Completion Challenge</h2><p>Complete the project without following a step-by-step guide the second time. Start with a blank folder and see whether you can independently organize it, capture it, compress it, secure it, share it safely and back it up.</p><div class="lh-callout"><strong>You are finished when you can explain not only “how” to perform a task, but also “why” you are doing it and what could go wrong.</strong></div></section>
<section class="lh-section"><h2>Final Takeaway</h2><div class="lh-callout"><strong>Computer skills are habits: observe before changing, organize before losing, verify before trusting, protect before sharing, and back up before disaster.</strong></div></section>
HTML;
}
