<?php
declare(strict_types=1);

function lh_course16_lesson48_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-48') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Is Data Privacy?</h2><p>Data privacy is about controlling what personal information is collected, why it is used, who can access it and how long it is kept. Good privacy habits reduce unnecessary exposure.</p></section>
<section class="lh-section"><h2>Think Before You Share</h2><p>Before giving an app, website or person your information, ask: <strong>What data is being requested? Why is it needed? Is this source trustworthy? Is there a less revealing option?</strong></p></section>
<section class="lh-section"><h2>Types of Personal Data</h2><table class="table table-bordered"><thead><tr><th>Data</th><th>Examples</th></tr></thead><tbody><tr><td>Identity</td><td>Name, address, government identifiers.</td></tr><tr><td>Contact</td><td>Email address and phone number.</td></tr><tr><td>Account</td><td>Usernames, authentication information and recovery details.</td></tr><tr><td>Financial</td><td>Bank and payment information.</td></tr><tr><td>Activity</td><td>Browsing, app usage or location information.</td></tr></tbody></table></section>
<section class="lh-section"><h2>Windows Privacy Controls</h2><p>Windows provides privacy and security settings where you can review permissions for features such as camera, microphone, location and other access. Review these settings periodically and remove unnecessary access where appropriate.</p></section>
<section class="lh-section"><h2>Strong Privacy Habits</h2><ul><li>Use unique passwords and a password manager when appropriate.</li><li>Enable multi-factor authentication on important accounts.</li><li>Keep software updated.</li><li>Review app permissions.</li><li>Be careful with public Wi-Fi and shared computers.</li><li>Limit what you post publicly.</li><li>Delete old accounts and data when practical.</li></ul></section>
<section class="lh-section"><h2>Privacy vs Convenience</h2><p>Many services offer convenience in exchange for data. The goal is not to reject every useful service, but to understand the trade-off and choose deliberately.</p><div class="lh-callout"><strong>Good privacy is intentional:</strong> share information because you choose to, not because a screen pressured you to click “Allow”.</div></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Review permissions for three installed apps.</li><li>Write down which sensitive permissions they use.</li><li>Ask whether each permission matches a feature you use.</li><li>Review one important online account's security and privacy settings.</li><li>Remove one unnecessary permission or public profile detail if appropriate.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What is data privacy?</li><li>Why should you question an app's requested permissions?</li><li>Name three types of personal data.</li><li>Does convenience always justify sharing more information?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>Controlling how personal information is collected, used and accessed.</li><li>To avoid unnecessary exposure.</li><li>Identity, contact and financial data, for example.</li><li>No. Consider the purpose, trust and alternatives.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Privacy starts with awareness. Know what data you are sharing, why it is needed and who can access it—and choose the minimum necessary exposure.</strong></div></section>
HTML;
}
