<?php
declare(strict_types=1);

function lh_course16_lesson37_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-37') return null;
    return <<<'HTML'
<section class="lh-section"><h2>Windows Settings: Your Control Center</h2><p>The Windows Settings app is the main place to configure the operating system. It brings hardware, network, accounts, personalization, apps, accessibility, privacy and updates together.</p></section>
<section class="lh-section"><h2>Main Areas to Know</h2><table class="table table-bordered"><thead><tr><th>Area</th><th>Typical tasks</th></tr></thead><tbody><tr><td>System</td><td>Display, sound, power, storage, notifications and recovery.</td></tr><tr><td>Bluetooth & devices</td><td>Printers, Bluetooth devices, mouse, keyboard and other hardware.</td></tr><tr><td>Network & internet</td><td>Wi-Fi, Ethernet, VPN and network settings.</td></tr><tr><td>Personalization</td><td>Backgrounds, themes, colors and lock screen.</td></tr><tr><td>Apps</td><td>Installed apps, optional features and app-related settings.</td></tr><tr><td>Accounts</td><td>Sign-in, users, backup and account options.</td></tr><tr><td>Time & language</td><td>Date, time, region and language settings.</td></tr><tr><td>Accessibility</td><td>Text size, Narrator, Magnifier, captions and other assistance.</td></tr><tr><td>Privacy & security</td><td>Permissions and security controls.</td></tr><tr><td>Windows Update</td><td>Updates and update-related options.</td></tr></tbody></table></section>
<section class="lh-section"><h2>Use Settings Search</h2><p>If you know what you want to change but not where it is, use the Settings search box. Searching for “printer”, “Bluetooth”, “display”, “backup” or “microphone” can be faster than browsing every category.</p></section>
<section class="lh-section"><h2>Change One Setting at a Time</h2><ol><li>Describe the problem or goal.</li><li>Search for the relevant setting.</li><li>Read the current value before changing it.</li><li>Change only what you understand.</li><li>Test the result.</li><li>Record the previous value if the setting is important.</li></ol><div class="lh-callout"><strong>Good habit:</strong> Avoid changing unrelated settings just because they look interesting.</div></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Open Settings.</li><li>Find your display settings.</li><li>Find Wi-Fi/network settings.</li><li>Find installed apps.</li><li>Find Windows Update.</li><li>Find Privacy & security.</li><li>Use Settings search to locate a setting you have never used before.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>Which Settings area manages display and power?</li><li>Where would you look for Wi-Fi?</li><li>Where are app permissions commonly managed?</li><li>Why is Settings search useful?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>System.</li><li>Network & internet.</li><li>Privacy & security.</li><li>It quickly locates settings without navigating many menus.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Learn the major Settings categories and use search. When troubleshooting, change one relevant setting at a time and test the result.</strong></div></section>
HTML;
}
