<?php
declare(strict_types=1);

function lh_course16_lesson40_computer_basics_override(array $lesson, int $position): ?string
{
    if ((string)($lesson['slug'] ?? '') !== 'course-16-lesson-40') return null;
    return <<<'HTML'
<section class="lh-section"><h2>What Is a Screenshot?</h2><p>A screenshot is a still image of what appears on your screen. Screen capture can also refer to recording video of screen activity. Screenshots are useful for documentation, troubleshooting, tutorials and sharing information.</p></section>
<section class="lh-section"><h2>Useful Windows Shortcuts</h2><table class="table table-bordered"><thead><tr><th>Shortcut</th><th>Typical use</th></tr></thead><tbody><tr><td>Win + Shift + S</td><td>Open the Snipping Tool capture interface.</td></tr><tr><td>PrtScn</td><td>Capture the screen using the behavior configured by Windows.</td></tr><tr><td>Win + PrtScn</td><td>On supported Windows configurations, capture the screen and save it automatically.</td></tr><tr><td>Alt + PrtScn</td><td>Capture the active window on supported configurations.</td></tr></tbody></table></section>
<section class="lh-section"><h2>Using Snipping Tool</h2><ol><li>Press <strong>Win + Shift + S</strong> or open Snipping Tool.</li><li>Choose the capture mode available on your Windows version.</li><li>Select the area or window you want to capture.</li><li>Review the image.</li><li>Save it with a useful filename or copy it to another app.</li></ol><div class="lh-callout"><strong>Tip:</strong> Capture only the information needed. A smaller screenshot is easier to share and understand.</div></section>
<section class="lh-section"><h2>Screen Recording</h2><p>Depending on Windows version and installed components, screen recording can be available through Snipping Tool or Xbox Game Bar. Recording features and shortcuts can vary, so check the tool shown on your PC.</p><p>Before recording, close private information and make sure you have permission to record other people's content or conversations.</p></section>
<section class="lh-section"><h2>Good Screenshot Habits</h2><ul><li>Crop out passwords, private messages and unnecessary personal information.</li><li>Include enough context to explain the problem.</li><li>Use clear filenames such as <strong>printer-error-2026-09-02.png</strong>.</li><li>Keep important captures in the correct project folder.</li><li>Do not publish someone else's private information without permission.</li></ul></section>
<section class="lh-section"><h2>Practical Activity</h2><ol><li>Open a simple window containing non-sensitive information.</li><li>Use Win + Shift + S to capture part of it.</li><li>Open the captured image in the available editor.</li><li>Crop or annotate it if useful.</li><li>Save it with a descriptive filename.</li></ol></section>
<section class="lh-section"><h2>Quick Self-Check</h2><ol><li>What is a screenshot?</li><li>Which shortcut opens the Snipping Tool capture interface?</li><li>Why should screenshots be checked for private information?</li><li>Why is a descriptive filename useful?</li></ol><details class="mt-3"><summary><strong>Show Answers</strong></summary><ol class="mt-3"><li>A still image of screen content.</li><li>Win + Shift + S.</li><li>Because screenshots can accidentally expose passwords, messages or other sensitive data.</li><li>It makes the capture easier to find and understand later.</li></ol></details></section>
<section class="lh-section"><h2>Key Takeaway</h2><div class="lh-callout"><strong>Capture only what you need, remove sensitive information, and save screenshots with clear names. Screen capture is a powerful communication tool when used carefully.</strong></div></section>
HTML;
}
