<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free UUID Generator Online','description'=>'Generate random UUIDs instantly online for free. Create one or multiple UUID v4 identifiers and copy them with SmartToolz.','url'=>'https://smarttoolz.in/tools/uuid-generator/'];
smarttoolz_tool_page_start($tool);
?>
<main class="uuid-page"><section class="tool-head"><span class="eyebrow">UUID GENERATOR</span><h1>Generate UUIDs</h1><p>Create secure random UUID v4 identifiers instantly in your browser.</p></section><section class="uuid-card"><div class="controls"><label>Number of UUIDs<select id="count"><option>1</option><option>5</option><option>10</option><option>25</option><option>50</option></select></label><button id="generate" class="primary">Generate UUIDs</button></div><div id="results" class="results"></div><div class="bottom"><span id="status">Ready</span><button id="copyAll">Copy All</button></div></section><section class="info-grid"><article><h2>What is a UUID?</h2><p>A UUID is a 128-bit identifier designed to be practically unique. UUID v4 values are generated randomly and are commonly used for IDs in applications and databases.</p></article><article><h2>How to use</h2><ol><li>Choose how many UUIDs you need.</li><li>Click Generate UUIDs.</li><li>Copy one UUID or all results.</li></ol></article></section></main>
<style>.uuid-page{width:min(900px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0 auto;color:#667085;font-size:15px}.uuid-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.controls{display:flex;gap:12px;align-items:end}.controls label{display:grid;gap:7px;flex:1;color:#344054;font-size:11px;font-weight:800}.controls select{height:46px;padding:0 12px;border:1px solid #dfe3eb;border-radius:11px;background:#fff;color:#172033}.controls button{height:46px;padding:0 20px;border:0;border-radius:11px;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff;font-size:11px;font-weight:900;cursor:pointer}.results{display:grid;gap:8px;margin-top:18px}.uuid-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:11px 12px;border:1px solid #e7eaf0;border-radius:11px;background:#fafbff}.uuid-row code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#263052;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.uuid-row button,.bottom button{padding:8px 11px;border:1px solid #dfe3eb;border-radius:9px;background:#fff;color:#4d3ee5;font-size:9px;font-weight:900;cursor:pointer}.bottom{display:flex;justify-content:space-between;align-items:center;margin-top:13px}.bottom span{color:#69738e;font-size:10px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p,.info-grid li{color:#667085;font-size:12px;line-height:1.75}.info-grid ol{margin:0;padding-left:20px}@media(max-width:600px){.uuid-page{width:calc(100% - 20px)}.uuid-card{padding:16px}.controls{flex-direction:column;align-items:stretch}.controls button{width:100%}.info-grid{grid-template-columns:1fr}.uuid-row{grid-template-columns:1fr}.uuid-row button{width:max-content}}
</style><script>(()=>{const results=document.getElementById('results'),count=document.getElementById('count'),status=document.getElementById('status');const uuid=()=>crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});function generate(){results.innerHTML='';for(let i=0;i<Number(count.value);i++){const value=uuid(),row=document.createElement('div');row.className='uuid-row';const code=document.createElement('code');code.textContent=value;const btn=document.createElement('button');btn.textContent='Copy';btn.onclick=async()=>{await navigator.clipboard.writeText(value);btn.textContent='Copied';setTimeout(()=>btn.textContent='Copy',900)};row.append(code,btn);results.append(row)}status.textContent=`Generated ${count.value} UUID${Number(count.value)===1?'':'s'}.`}document.getElementById('generate').onclick=generate;document.getElementById('copyAll').onclick=async()=>{const values=[...results.querySelectorAll('code')].map(x=>x.textContent);if(!values.length){status.textContent='Generate UUIDs first.';return}await navigator.clipboard.writeText(values.join('\n'));status.textContent='All UUIDs copied.'};generate()})();</script>
<?php smarttoolz_tool_page_end(); ?>
