<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/lib/tool-page.php';
$tool=['title'=>'Free Text Repeater Online','description'=>'Repeat any text multiple times with custom separators instantly in your browser. Fast, simple and private.','url'=>'https://smarttoolz.in/tools/text-repeater/'];
smarttoolz_tool_page_start($tool);
?>
<main class="repeat-page"><section class="tool-head"><span class="eyebrow">TEXT REPEATER</span><h1>Repeat Text Online</h1><p>Repeat words, sentences or any text as many times as you need.</p></section><section class="repeat-card"><label>Text to repeat<textarea id="input" placeholder="Enter text here..."></textarea></label><div class="controls"><label>Repeat count<input id="count" type="number" min="1" max="10000" value="5"></label><label>Separator<select id="separator"><option value="newline">New line</option><option value="space">Space</option><option value="comma">Comma</option><option value="custom">Custom</option></select></label></div><label id="customWrap" class="custom" hidden>Custom separator<input id="custom" placeholder="e.g. | or ---"></label><div class="actions"><button id="repeat" class="primary">Repeat Text</button><button id="clear">Clear</button></div><div class="result"><div class="result-head"><span>OUTPUT</span><span id="stats">0 characters</span></div><textarea id="output" readonly placeholder="Repeated text will appear here..."></textarea><button id="copy">Copy Output</button></div></section><section class="info-grid"><article><h2>Quick text repetition</h2><p>Useful for testing, templates, placeholder content, lists and repetitive text generation.</p></article><article><h2>Runs in your browser</h2><p>Your text stays on your device while the repetition is generated.</p></article></section></main>
<style>.repeat-page{width:min(900px,calc(100% - 32px));margin:0 auto 70px}.tool-head{text-align:center;padding:48px 0 24px}.eyebrow{color:#5b43ff;font-size:10px;font-weight:900;letter-spacing:1.8px}.tool-head h1{margin:14px 0 8px;font-size:clamp(38px,6vw,56px);line-height:1;letter-spacing:-2.5px}.tool-head p{margin:0;color:#667085;font-size:15px}.repeat-card{padding:24px;background:#fff;border:1px solid #e7eaf0;border-radius:24px;box-shadow:0 18px 50px rgba(16,24,40,.07)}.repeat-card label{display:grid;gap:7px;margin-bottom:14px;color:#344054;font-size:11px;font-weight:800}.repeat-card textarea,.repeat-card input,.repeat-card select{box-sizing:border-box;width:100%;padding:12px;border:1px solid #dfe3eb;border-radius:11px;background:#fcfdff;color:#172033;font:13px ui-monospace,SFMono-Regular,Menlo,monospace;outline:0}.repeat-card textarea{min-height:180px;resize:vertical;line-height:1.6}.repeat-card input,.repeat-card select{height:46px}.controls{display:grid;grid-template-columns:1fr 1fr;gap:12px}.custom{margin-top:12px}.actions{display:flex;gap:9px;margin:2px 0 14px}.actions button,.result>button{padding:10px 16px;border:1px solid #dfe3eb;border-radius:10px;background:#fff;color:#344054;font-size:10px;font-weight:900;cursor:pointer}.actions .primary{border:0;background:linear-gradient(90deg,#5d46ff,#3e7dff);color:#fff}.result{padding:16px;border:1px solid #e7eaf0;border-radius:14px;background:#fafbff}.result-head{display:flex;justify-content:space-between;margin-bottom:8px}.result-head span{font-size:10px;color:#69738e;font-weight:800}.result textarea{min-height:180px;background:#fff}.result>button{margin-top:9px;background:#111936;border-color:#111936;color:#fff}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.info-grid article{padding:22px;border:1px solid #e7eaf0;border-radius:18px;background:#fff}.info-grid h2{margin:0 0 10px;font-size:17px}.info-grid p{margin:0;color:#667085;font-size:12px;line-height:1.75}@media(max-width:650px){.repeat-page{width:calc(100% - 20px)}.repeat-card{padding:16px}.controls,.info-grid{grid-template-columns:1fr}}
</style><script>(()=>{const input=document.getElementById('input'),count=document.getElementById('count'),sep=document.getElementById('separator'),customWrap=document.getElementById('customWrap'),custom=document.getElementById('custom'),output=document.getElementById('output'),stats=document.getElementById('stats');sep.onchange=()=>customWrap.hidden=sep.value!=='custom';document.getElementById('repeat').onclick=()=>{const text=input.value;if(!text){output.value='';stats.textContent='Enter text first.';return}const n=Math.min(10000,Math.max(1,Number(count.value)||1));const s=sep.value==='newline'?'\n':sep.value==='space'?' ':sep.value==='comma'?', ':custom.value;output.value=Array(n).fill(text).join(s);stats.textContent=`${output.value.length.toLocaleString()} characters · ${n.toLocaleString()} repetitions`};document.getElementById('copy').onclick=async()=>{if(!output.value)return;await navigator.clipboard.writeText(output.value);document.getElementById('copy').textContent='Copied';setTimeout(()=>document.getElementById('copy').textContent='Copy Output',900)};document.getElementById('clear').onclick=()=>{input.value='';output.value='';stats.textContent='0 characters'}})();</script>
<?php smarttoolz_tool_page_end(); ?>
