<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once $_SERVER['DOCUMENT_ROOT'] . '/creator-ai/auth/config.php';
const SMARTTOOLZ_TRIAL_LIMIT = 5;
function smarttoolz_trial_db(): PDO { return db(); }
function smarttoolz_trial_install(): void { static $done=false; if($done)return; $done=true; $db=smarttoolz_trial_db(); $db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_guest_trials (guest_key CHAR(64) NOT NULL, tool_slug VARCHAR(150) NOT NULL, uses INT UNSIGNED NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(guest_key,tool_slug), INDEX idx_guest_trial_key(guest_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); $db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(30) NOT NULL DEFAULT 'info',title VARCHAR(180) NOT NULL,message VARCHAR(500) NOT NULL,read_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_notification_user_created(user_id,created_at),INDEX idx_notification_unread(user_id,read_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); }
function smarttoolz_current_user_id(): ?int { $id=(int)($_SESSION['user_id']??0); return $id>0?$id:null; }
function smarttoolz_guest_key(): string { if(!empty($_COOKIE['smarttoolz_guest_key'])&&preg_match('/^[a-f0-9]{64}$/',$_COOKIE['smarttoolz_guest_key'])) return $_COOKIE['smarttoolz_guest_key']; $key=hash('sha256',bin2hex(random_bytes(32))); setcookie('smarttoolz_guest_key',$key,['expires'=>time()+31536000,'path'=>'/smart-toolz','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']); $_COOKIE['smarttoolz_guest_key']=$key; return $key; }
function smarttoolz_is_admin(int $userId): bool { try{$q=smarttoolz_trial_db()->prepare('SELECT role FROM creator_users WHERE id=? LIMIT 1');$q->execute([$userId]);return in_array((string)$q->fetchColumn(),['admin','superadmin'],true);}catch(Throwable $e){return false;} }
function smarttoolz_clean_tool_slug(string $slug): string {$slug=basename(trim($slug));$slug=preg_replace('/\.php$/i','',$slug)??'';if(!preg_match('/^[a-zA-Z0-9_-]{1,150}$/',$slug))throw new InvalidArgumentException('Invalid tool.');return strtolower($slug);}
function smarttoolz_guest_trial_status(string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$q=smarttoolz_trial_db()->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? LIMIT 1');$q->execute([$key,$toolSlug]);$used=min(SMARTTOOLZ_TRIAL_LIMIT,max(0,(int)$q->fetchColumn()));return ['limit'=>SMARTTOOLZ_TRIAL_LIMIT,'used'=>$used,'remaining'=>SMARTTOOLZ_TRIAL_LIMIT-$used,'unlimited'=>false,'guest'=>true];}
function smarttoolz_trial_status(int $userId,string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId))return ['limit'=>SMARTTOOLZ_TRIAL_LIMIT,'used'=>0,'remaining'=>SMARTTOOLZ_TRIAL_LIMIT,'unlimited'=>true];$q=smarttoolz_trial_db()->prepare('SELECT uses FROM smarttoolz_tool_trials WHERE user_id=? AND tool_slug=? LIMIT 1');$q->execute([$userId,$toolSlug]);$used=min(SMARTTOOLZ_TRIAL_LIMIT,max(0,(int)$q->fetchColumn()));return ['limit'=>SMARTTOOLZ_TRIAL_LIMIT,'used'=>$used,'remaining'=>SMARTTOOLZ_TRIAL_LIMIT-$used,'unlimited'=>false];}
function smarttoolz_notify(int $userId,string $type,string $title,string $message): void {try{smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('INSERT INTO smarttoolz_notifications(user_id,type,title,message) VALUES(?,?,?,?)');$q->execute([$userId,substr($type,0,30),substr($title,0,180),substr($message,0,500)]);}catch(Throwable $e){error_log('SmartToolz notification error: '.$e->getMessage());}}
function smarttoolz_guest_trial_consume(string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$db=smarttoolz_trial_db();$q=$db->prepare('INSERT IGNORE INTO smarttoolz_guest_trials(guest_key,tool_slug,uses) VALUES(?,?,0)');$q->execute([$key,$toolSlug]);$db->beginTransaction();try{$q=$db->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? FOR UPDATE');$q->execute([$key,$toolSlug]);$used=(int)$q->fetchColumn();if($used>=SMARTTOOLZ_TRIAL_LIMIT){$db->rollBack();return ['ok'=>false,'limit'=>5,'used'=>5,'remaining'=>0,'guest'=>true,'reason'=>'trial_exhausted','message'=>'Your 5 free trials for this tool are finished. Please login to continue using credits.'];}$newUsed=$used+1;$q=$db->prepare('UPDATE smarttoolz_guest_trials SET uses=? WHERE guest_key=? AND tool_slug=?');$q->execute([$newUsed,$key,$toolSlug]);$remaining=SMARTTOOLZ_TRIAL_LIMIT-$newUsed;$db->commit();return ['ok'=>true,'limit'=>5,'used'=>$newUsed,'remaining'=>$remaining,'guest'=>true];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function smarttoolz_trial_consume(int $userId,string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId)){smarttoolz_notify($userId,'tool','Tool used','You used '.ucwords(str_replace(['-','_'],' ',$toolSlug)).'. Admin accounts have unlimited tool access.');return ['ok'=>true,'limit'=>5,'used'=>0,'remaining'=>5,'unlimited'=>true];}$db=smarttoolz_trial_db();$q=$db->prepare('INSERT IGNORE INTO smarttoolz_tool_trials(user_id,tool_slug,uses) VALUES(?,?,0)');$q->execute([$userId,$toolSlug]);$db->beginTransaction();try{$q=$db->prepare('SELECT uses FROM smarttoolz_tool_trials WHERE user_id=? AND tool_slug=? FOR UPDATE');$q->execute([$userId,$toolSlug]);$used=(int)$q->fetchColumn();if($used>=5){$db->rollBack();return ['ok'=>false,'limit'=>5,'used'=>5,'remaining'=>0,'unlimited'=>false,'reason'=>'credits_required'];}$newUsed=$used+1;$q=$db->prepare('UPDATE smarttoolz_tool_trials SET uses=? WHERE user_id=? AND tool_slug=?');$q->execute([$newUsed,$userId,$toolSlug]);$db->commit();return ['ok'=>true,'limit'=>5,'used'=>$newUsed,'remaining'=>5-$newUsed,'unlimited'=>false];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function smarttoolz_notification_list(int $userId,int $limit=20): array {smarttoolz_trial_install();$limit=max(1,min(50,$limit));$q=smarttoolz_trial_db()->prepare("SELECT id,type,title,message,read_at,created_at FROM smarttoolz_notifications WHERE user_id=? ORDER BY id DESC LIMIT $limit");$q->execute([$userId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function smarttoolz_notification_unread_count(int $userId): int {smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('SELECT COUNT(*) FROM smarttoolz_notifications WHERE user_id=? AND read_at IS NULL');$q->execute([$userId]);return (int)$q->fetchColumn();}
