<?php
declare(strict_types=1);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
require_once $_SERVER['DOCUMENT_ROOT'].'/creator-ai/auth/config.php';
const SMARTTOOLZ_TRIAL_LIMIT=5;
function smarttoolz_trial_db():PDO{return db();}
function smarttoolz_trial_install():void{static $done=false;if($done)return;$done=true;$db=smarttoolz_trial_db();$db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_guest_trials (guest_key CHAR(64) NOT NULL, tool_slug VARCHAR(150) NOT NULL, uses INT UNSIGNED NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(guest_key,tool_slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(30) NOT NULL DEFAULT 'info',title VARCHAR(180) NOT NULL,message VARCHAR(500) NOT NULL,read_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(user_id,created_at),INDEX(user_id,read_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
function smarttoolz_current_user_id():?int{$id=(int)($_SESSION['user_id']??0);return $id>0?$id:null;}
function smarttoolz_guest_key():string{if(!empty($_COOKIE['smarttoolz_guest_key'])&&preg_match('/^[a-f0-9]{64}$/',$_COOKIE['smarttoolz_guest_key'])){$key=$_COOKIE['smarttoolz_guest_key'];$_SESSION['smarttoolz_guest_key']=$key;return $key;}if(!empty($_SESSION['smarttoolz_guest_key'])&&preg_match('/^[a-f0-9]{64}$/',$_SESSION['smarttoolz_guest_key'])){$key=$_SESSION['smarttoolz_guest_key'];if(!headers_sent())setcookie('smarttoolz_guest_key',$key,['expires'=>time()+31536000,'path'=>'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);$_COOKIE['smarttoolz_guest_key']=$key;return $key;}$key=hash('sha256',bin2hex(random_bytes(32)));$_SESSION['smarttoolz_guest_key']=$key;if(!headers_sent())setcookie('smarttoolz_guest_key',$key,['expires'=>time()+31536000,'path'=>'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);$_COOKIE['smarttoolz_guest_key']=$key;return $key;}
function smarttoolz_is_admin(int $userId):bool{try{$q=smarttoolz_trial_db()->prepare('SELECT role FROM creator_users WHERE id=? LIMIT 1');$q->execute([$userId]);return in_array((string)$q->fetchColumn(),['admin','superadmin'],true);}catch(Throwable $e){return false;}}
function smarttoolz_clean_tool_slug(string $slug):string{$slug=basename(trim($slug));$slug=preg_replace('/\.php$/i','',$slug)??'';if(!preg_match('/^[a-zA-Z0-9_-]{1,150}$/',$slug))throw new InvalidArgumentException('Invalid tool.');return strtolower($slug);}
function smarttoolz_guest_trial_status(string $toolSlug):array{smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$q=smarttoolz_trial_db()->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? LIMIT 1');$q->execute([$key,$toolSlug]);$used=min(5,max(0,(int)$q->fetchColumn()));return ['limit'=>5,'used'=>$used,'remaining'=>5-$used,'unlimited'=>false,'guest'=>true];}
function smarttoolz_trial_status(int $userId,string $toolSlug):array{smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId))return ['limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>true,'credits_only'=>false];$q=smarttoolz_trial_db()->prepare('SELECT credits FROM creator_users WHERE id=? LIMIT 1');$q->execute([$userId]);$credits=max(0,(int)$q->fetchColumn());return ['limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>false,'guest'=>false,'credits_only'=>true,'credits'=>$credits];}
function smarttoolz_notify(int $userId,string $type,string $title,string $message):void{try{smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('INSERT INTO smarttoolz_notifications(user_id,type,title,message) VALUES(?,?,?,?)');$q->execute([$userId,substr($type,0,30),substr($title,0,180),substr($message,0,500)]);}catch(Throwable $e){error_log('SmartToolz notification error: '.$e->getMessage());}}
function smarttoolz_guest_trial_consume(string $toolSlug):array{smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$db=smarttoolz_trial_db();$q=$db->prepare('INSERT IGNORE INTO smarttoolz_guest_trials(guest_key,tool_slug,uses) VALUES(?,?,0)');$q->execute([$key,$toolSlug]);$db->beginTransaction();try{$q=$db->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? FOR UPDATE');$q->execute([$key,$toolSlug]);$used=(int)$q->fetchColumn();if($used>=5){$db->rollBack();return ['ok'=>false,'limit'=>5,'used'=>5,'remaining'=>0,'guest'=>true,'reason'=>'trial_exhausted','message'=>'Your 5 free trials for this tool are finished. Please login to continue using credits.'];}$newUsed=$used+1;$q=$db->prepare('UPDATE smarttoolz_guest_trials SET uses=? WHERE guest_key=? AND tool_slug=?');$q->execute([$newUsed,$key,$toolSlug]);$db->commit();return ['ok'=>true,'limit'=>5,'used'=>$newUsed,'remaining'=>5-$newUsed,'guest'=>true];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function smarttoolz_trial_consume(int $userId,string $toolSlug):array{smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId)){smarttoolz_notify($userId,'tool','Tool used','You used '.ucwords(str_replace(['-','_'],' ',$toolSlug)).'. Admin accounts have unlimited tool access.');return ['ok'=>true,'limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>true,'credits'=>null];}$db=smarttoolz_trial_db();$db->beginTransaction();try{$q=$db->prepare('SELECT credits FROM creator_users WHERE id=? FOR UPDATE');$q->execute([$userId]);$credits=(int)$q->fetchColumn();if($credits<=0){$db->rollBack();smarttoolz_notify($userId,'warning','No credits remaining','You tried to use '.ucwords(str_replace(['-','_'],' ',$toolSlug)).', but your credits are exhausted.');return ['ok'=>false,'reason'=>'no_credits','credits'=>0,'credits_required'=>true,'message'=>'You have no credits remaining. Please add credits to continue.'];}$q=$db->prepare('UPDATE creator_users SET credits=credits-1 WHERE id=? AND credits>0');$q->execute([$userId]);$remaining=$credits-1;$db->commit();smarttoolz_notify($userId,'tool','Tool used','You used '.ucwords(str_replace(['-','_'],' ',$toolSlug)).'. 1 credit was deducted. '.$remaining.' credits remaining.');return ['ok'=>true,'credits_required'=>true,'credits'=>$remaining,'deducted'=>1,'message'=>'1 credit deducted.'];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function smarttoolz_notification_list(int $userId,int $limit=20):array{smarttoolz_trial_install();$limit=max(1,min(50,$limit));$q=smarttoolz_trial_db()->prepare("SELECT id,type,title,message,read_at,created_at FROM smarttoolz_notifications WHERE user_id=? ORDER BY id DESC LIMIT $limit");$q->execute([$userId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function smarttoolz_notification_unread_count(int $userId):int{smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('SELECT COUNT(*) FROM smarttoolz_notifications WHERE user_id=? AND read_at IS NULL');$q->execute([$userId]);return (int)$q->fetchColumn();}
