<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require_once $_SERVER['DOCUMENT_ROOT'] . '/creator-ai/auth/config.php';
const SMARTTOOLZ_TRIAL_LIMIT = 5;
function smarttoolz_trial_db(): PDO { return db(); }
function smarttoolz_trial_install(): void { static $done=false; if($done)return; $done=true; $db=smarttoolz_trial_db(); $db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_guest_trials (guest_key CHAR(64) NOT NULL, tool_slug VARCHAR(150) NOT NULL, uses INT UNSIGNED NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(guest_key,tool_slug), INDEX idx_guest_trial_key(guest_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); $db->exec("CREATE TABLE IF NOT EXISTS smarttoolz_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(30) NOT NULL DEFAULT 'info',title VARCHAR(180) NOT NULL,message VARCHAR(500) NOT NULL,read_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_notification_user_created(user_id,created_at),INDEX idx_notification_unread(user_id,read_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); }
function smarttoolz_current_user_id(): ?int { $id=(int)($_SESSION['user_id']??0); return $id>0?$id:null; }
function smarttoolz_guest_key(): string { if(!empty($_SESSION['smarttoolz_guest_key'])&&preg_match('/^[a-f0-9]{64}$/',$_SESSION['smarttoolz_guest_key'])) return $_SESSION['smarttoolz_guest_key']; if(!empty($_COOKIE['smarttoolz_guest_key'])&&preg_match('/^[a-f0-9]{64}$/',$_COOKIE['smarttoolz_guest_key'])){$_SESSION['smarttoolz_guest_key']=$_COOKIE['smarttoolz_guest_key'];return $_COOKIE['smarttoolz_guest_key'];} $key=hash('sha256',bin2hex(random_bytes(32)));$_SESSION['smarttoolz_guest_key']=$key;if(!headers_sent()){setcookie('smarttoolz_guest_key',$key,['expires'=>time()+31536000,'path'=>'/smart-toolz','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);}$_COOKIE['smarttoolz_guest_key']=$key;return $key; }
function smarttoolz_is_admin(int $userId): bool { try{$q=smarttoolz_trial_db()->prepare('SELECT role FROM creator_users WHERE id=? LIMIT 1');$q->execute([$userId]);return in_array((string)$q->fetchColumn(),['admin','superadmin'],true);}catch(Throwable $e){return false;} }
function smarttoolz_clean_tool_slug(string $slug): string {$slug=basename(trim($slug));$slug=preg_replace('/\.php$/i','',$slug)??'';if(!preg_match('/^[a-zA-Z0-9_-]{1,150}$/',$slug))throw new InvalidArgumentException('Invalid tool.');return strtolower($slug);}
function smarttoolz_guest_trial_status(string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$q=smarttoolz_trial_db()->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? LIMIT 1');$q->execute([$key,$toolSlug]);$used=min(SMARTTOOLZ_TRIAL_LIMIT,max(0,(int)$q->fetchColumn()));return ['limit'=>SMARTTOOLZ_TRIAL_LIMIT,'used'=>$used,'remaining'=>SMARTTOOLZ_TRIAL_LIMIT-$used,'unlimited'=>false,'guest'=>true];}
function smarttoolz_trial_status(int $userId,string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId))return ['limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>true,'credits_only'=>false];return ['limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>false,'guest'=>false,'credits_only'=>true];}
function smarttoolz_notify(int $userId,string $type,string $title,string $message): void {try{smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('INSERT INTO smarttoolz_notifications(user_id,type,title,message) VALUES(?,?,?,?)');$q->execute([$userId,substr($type,0,30),substr($title,0,180),substr($message,0,500)]);}catch(Throwable $e){error_log('SmartToolz notification error: '.$e->getMessage());}}
function smarttoolz_guest_trial_consume(string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);$key=smarttoolz_guest_key();$db=smarttoolz_trial_db();$q=$db->prepare('INSERT IGNORE INTO smarttoolz_guest_trials(guest_key,tool_slug,uses) VALUES(?,?,0)');$q->execute([$key,$toolSlug]);$db->beginTransaction();try{$q=$db->prepare('SELECT uses FROM smarttoolz_guest_trials WHERE guest_key=? AND tool_slug=? FOR UPDATE');$q->execute([$key,$toolSlug]);$used=(int)$q->fetchColumn();if($used>=SMARTTOOLZ_TRIAL_LIMIT){$db->rollBack();return ['ok'=>false,'limit'=>5,'used'=>5,'remaining'=>0,'guest'=>true,'reason'=>'trial_exhausted','message'=>'Your 5 free trials for this tool are finished. Please login to continue using credits.'];}$newUsed=$used+1;$q=$db->prepare('UPDATE smarttoolz_guest_trials SET uses=? WHERE guest_key=? AND tool_slug=?');$q->execute([$newUsed,$key,$toolSlug]);$remaining=SMARTTOOLZ_TRIAL_LIMIT-$newUsed;$db->commit();return ['ok'=>true,'limit'=>5,'used'=>$newUsed,'remaining'=>$remaining,'guest'=>true];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function smarttoolz_trial_consume(int $userId,string $toolSlug): array {smarttoolz_trial_install();$toolSlug=smarttoolz_clean_tool_slug($toolSlug);if(smarttoolz_is_admin($userId)){smarttoolz_notify($userId,'tool','Tool used','You used '.ucwords(str_replace(['-','_'],' ',$toolSlug)).'. Admin accounts have unlimited tool access.');return ['ok'=>true,'limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>true];}return ['ok'=>false,'limit'=>0,'used'=>0,'remaining'=>0,'unlimited'=>false,'reason'=>'credits_required','message'=>'Logged-in users use credits. 1 successful generation = 1 credit.'];}
function smarttoolz_notification_list(int $userId,int $limit=20): array {smarttoolz_trial_install();$limit=max(1,min(50,$limit));$q=smarttoolz_trial_db()->prepare("SELECT id,type,title,message,read_at,created_at FROM smarttoolz_notifications WHERE user_id=? ORDER BY id DESC LIMIT $limit");$q->execute([$userId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function smarttoolz_notification_unread_count(int $userId): int {smarttoolz_trial_install();$q=smarttoolz_trial_db()->prepare('SELECT COUNT(*) FROM smarttoolz_notifications WHERE user_id=? AND read_at IS NULL');$q->execute([$userId]);return (int)$q->fetchColumn();}

/* Guest trial UI hook. A download never consumes a trial. A successful generation can consume again without a page reload. */
if (!smarttoolz_current_user_id() && str_contains((string)($_SERVER['REQUEST_URI'] ?? ''), '/tools/') && !str_contains((string)($_SERVER['REQUEST_URI'] ?? ''), '/api/')) {
    register_shutdown_function(function (): void {
        $tool = basename((string)($_SERVER['SCRIPT_NAME'] ?? ''), '.php');
        if ($tool === '') return;
        echo '<script>(function(){var tool='.json_encode($tool).',busy=false,lastSig="",timer=0;function node(){return document.querySelector(".result")||document.querySelector("[data-tool-result]")||document.querySelector(".out");}function sig(){var n=node();if(!n)return "";return n.innerHTML+"|"+n.textContent+"|"+n.getAttribute("style");}function paint(d){var n=document.querySelector(".trial-note");if(n&&d&&d.ok)n.innerHTML="🎁 <b>"+d.used+" / "+d.limit+" used</b> — "+d.remaining+" free trials remaining for this tool.";}function consume(){if(busy)return;busy=true;fetch("/smart-toolz/api/trial.php?action=consume&tool="+encodeURIComponent(tool),{cache:"no-store"}).then(function(r){return r.json()}).then(function(d){paint(d);if(d.ok)lastSig=sig();}).catch(function(){}).finally(function(){busy=false;});}window.smartToolzTrialSuccess=function(){clearTimeout(timer);timer=setTimeout(function(){var s=sig();if(s&&s!==lastSig){consume();}else if(s){consume();}},30);};function check(){var n=node();if(!n)return;var visible=getComputedStyle(n).display!=="none"&&n.offsetHeight>0;var s=sig();if(visible&&s&&s!==lastSig&&!busy){consume();}}var obs=new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(check,180);});obs.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["style","src","href","value"]});setInterval(check,700);setTimeout(function(){var n=node();if(n&&getComputedStyle(n).display!=="none"&&n.offsetHeight>0)check();},300);})();</script>';
    });
}
