<?php
/**
 * Plugin Name: SmartToolz Video
 * Description: SmartToolz Video platform. WordPress core remains untouched; application behavior is provided by this plugin.
 * Version: 1.4.0
 * Author: SmartToolz
 * Text Domain: smarttoolz-video
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'SMARTTOOLZ_VIDEO_VERSION', '1.4.0' );
define( 'SMARTTOOLZ_VIDEO_FILE', __FILE__ );
define( 'SMARTTOOLZ_VIDEO_DIR', plugin_dir_path( __FILE__ ) );
define( 'SMARTTOOLZ_VIDEO_URL', plugin_dir_url( __FILE__ ) );
function smarttoolz_video_show_admin_bar( $show ) { if ( is_admin() ) return $show; $user=wp_get_current_user(); if(!$user||!$user->exists())return false; return in_array('administrator',(array)$user->roles,true); }
add_filter('show_admin_bar','smarttoolz_video_show_admin_bar',999);
function smarttoolz_video_hide_admin_bar_css(){if(is_admin())return;$user=wp_get_current_user();if(!$user||!$user->exists()||!in_array('administrator',(array)$user->roles,true))echo '<style id="smarttoolz-hide-wp-admin-bar">#wpadminbar{display:none!important}html{margin-top:0!important}</style>';}
add_action('wp_head','smarttoolz_video_hide_admin_bar_css',999);
require_once SMARTTOOLZ_VIDEO_DIR.'includes/videos.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/creator-settings.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/bootstrap.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/channel-media-upload.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/theme-installer.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/auth.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/admin-settings.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/app.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/video-settings.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/player.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/ads.php';
require_once SMARTTOOLZ_VIDEO_DIR.'includes/route-fallback.php';
function smarttoolz_video_admin_menu(){add_menu_page('SmartToolz','SmartToolz','manage_options','smarttoolz','smarttoolz_video_dashboard_page','dashicons-video-alt3',25);add_submenu_page('smarttoolz','Dashboard','Dashboard','manage_options','smarttoolz','smarttoolz_video_dashboard_page');add_submenu_page('smarttoolz','Page Settings','Page Settings','manage_options','smarttoolz-video-pages','smarttoolz_video_page_settings');add_submenu_page('smarttoolz','Theme Setup','Theme Setup','manage_options','smarttoolz-video-theme','smarttoolz_video_theme_settings');}
add_action('admin_menu','smarttoolz_video_admin_menu');
function smarttoolz_video_dashboard_action_notice($message,$success=true){return '<div class="notice '.($success?'notice-success':'notice-error').' is-dismissible"><p>'.esc_html($message).'</p></div>';}
function smarttoolz_video_dashboard_page(){if(!current_user_can('manage_options'))return;$notice='';if(isset($_POST['stv_dashboard_action'],$_POST['stv_dashboard_nonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stv_dashboard_nonce'])),'stv_dashboard_action')){$action=sanitize_key(wp_unslash($_POST['stv_dashboard_action']));if('install_theme'===$action){$result=smarttoolz_video_install_theme();$notice=is_wp_error($result)?smarttoolz_video_dashboard_action_notice($result->get_error_message(),false):smarttoolz_video_dashboard_action_notice('SmartToolz Video Theme installed successfully.');}elseif('activate_theme'===$action){$result=smarttoolz_video_activate_theme();$notice=is_wp_error($result)?smarttoolz_video_dashboard_action_notice($result->get_error_message(),false):smarttoolz_video_dashboard_action_notice('SmartToolz Video Theme activated and homepage synchronized.');}elseif('set_home'===$action){$result=smarttoolz_video_set_static_homepage();$notice=$result?smarttoolz_video_dashboard_action_notice('SmartToolz Home is now the static homepage.'):smarttoolz_video_dashboard_action_notice('Could not set SmartToolz Home as the static homepage.',false);}elseif('repair_pages'===$action){smarttoolz_video_sync_pages();$notice=smarttoolz_video_dashboard_action_notice('All SmartToolz pages were synchronized and repaired.');}}
$installed=smarttoolz_video_theme_installed();$active=smarttoolz_video_theme_is_active();$ids=(array)get_option('smarttoolz_video_page_ids',array());$home_id=isset($ids['home'])?absint($ids['home']):0;$static_home='page'===get_option('show_on_front','posts')&&$home_id&&absint(get_option('page_on_front',0))===$home_id;
?><div class="wrap"><div style="display:flex;align-items:center;gap:12px;margin:8px 0 20px;"><div style="width:44px;height:44px;border-radius:12px;background:#ff0033;color:#fff;display:flex;align-items:center;justify-content:center;font-size:21px;font-weight:800;">▶</div><div><h1 style="margin:0;">SmartToolz</h1><p style="margin:3px 0 0;color:#646970;">Video-sharing platform control center</p></div></div><?php echo $notice; ?><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;max-width:1100px;"><div style="background:#fff;border:1px solid #dcdcde;border-radius:12px;padding:20px;"><h2 style="margin-top:0;">Recommended Actions</h2><p style="color:#646970;">Complete the SmartToolz setup for the best video-site experience.</p><?php foreach(array('install_theme'=>'Install SmartToolz Theme','activate_theme'=>'Activate SmartToolz Theme','set_home'=>'Set SmartToolz Home as Homepage','repair_pages'=>'Repair & Sync Pages') as $action=>$label):?><form method="post" style="margin:0 0 10px;"><?php wp_nonce_field('stv_dashboard_action','stv_dashboard_nonce');?><input type="hidden" name="stv_dashboard_action" value="<?php echo esc_attr($action);?>"><button type="submit" class="button <?php echo 'activate_theme'===$action?'button-primary':'button-secondary';?>" style="width:100%;text-align:left;"><?php echo esc_html($label);?></button></form><?php endforeach;?></div><div style="background:#111827;color:#fff;border-radius:12px;padding:20px;"><h2 style="margin-top:0;color:#fff;">SmartToolz Status</h2><p><strong>Theme:</strong> <?php echo $active?'Active':($installed?'Installed':'Not installed');?></p><p><strong>Static Home:</strong> <?php echo $static_home?'Active':'Not set';?></p><p><strong>Pages:</strong> <?php echo count(smarttoolz_video_page_definitions());?> managed sections</p><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-video-pages'));?>" class="button button-secondary">Open Page Settings</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-account-access'));?>" class="button button-secondary" style="margin-left:8px;">Account & Access</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-video-settings'));?>" class="button button-secondary" style="margin-left:8px;">Video Settings</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-video-player'));?>" class="button button-secondary" style="margin-left:8px;">Player Settings</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-video-ads'));?>" class="button button-secondary" style="margin-left:8px;">Ads Setup</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-google-auth'));?>" class="button button-secondary" style="margin-left:8px;">Google Login</a><a href="<?php echo esc_url(admin_url('admin.php?page=smarttoolz-channel-settings'));?>" class="button button-secondary" style="margin-left:8px;">Channel Settings</a></div></div></div><?php }
function smarttoolz_video_page_settings(){if(!current_user_can('manage_options'))return;$notice='';if(isset($_POST['stv_sync_pages'],$_POST['stv_sync_nonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stv_sync_nonce'])),'stv_sync_pages')){smarttoolz_video_sync_pages();$notice='<div class="notice notice-success is-dismissible"><p>SmartToolz Video pages synced successfully.</p></div>';}if(isset($_POST['stv_set_home'],$_POST['stv_home_nonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stv_home_nonce'])),'stv_set_home'))$notice=smarttoolz_video_set_static_homepage()?'<div class="notice notice-success is-dismissible"><p>SmartToolz Home is now the static homepage.</p></div>':'<div class="notice notice-error is-dismissible"><p>Could not set SmartToolz Home as the static homepage.</p></div>';$definitions=smarttoolz_video_page_definitions();$ids=(array)get_option('smarttoolz_video_page_ids',array());$home_id=isset($ids['home'])?absint($ids['home']):0;$is_static_home='page'===get_option('show_on_front','posts')&&$home_id&&absint(get_option('page_on_front',0))===$home_id;
?><div class="wrap"><h1>Page Settings</h1><p>Manage and repair all SmartToolz pages. WordPress core files are not modified.</p><?php echo $notice;?><div style="margin:16px 0;padding:16px 18px;background:#fff;border:1px solid #ccd0d4;max-width:900px;"><h2 style="margin-top:0;">Static Homepage</h2><p>SmartToolz Home is kept as the site's static front page.</p><p><strong style="color:#008a20;"><?php echo $is_static_home?'Active':'Not active';?></strong></p><form method="post"><?php wp_nonce_field('stv_set_home','stv_home_nonce');?><input type="hidden" name="stv_set_home" value="1"><?php submit_button($is_static_home?'Home Page Already Set':'Set SmartToolz Home as Homepage','primary','submit',false);?></form></div><form method="post"><?php wp_nonce_field('stv_sync_pages','stv_sync_nonce');?><input type="hidden" name="stv_sync_pages" value="1"><?php submit_button('Sync / Repair Pages','secondary','submit',false);?></form><h2>Managed Pages</h2><table class="widefat striped"><thead><tr><th>Section</th><th>Page ID</th><th>Status</th><th>URL</th></tr></thead><tbody><?php foreach($definitions as $key=>$page):$id=isset($ids[$key])?absint($ids[$key]):0;$valid=$id&&'page'===get_post_type($id)&&'trash'!==get_post_status($id);$url=$valid?get_permalink($id):home_url('/'.trim(smarttoolz_video_page_path($key,$definitions),'/').'/');?><tr><td><?php echo esc_html($page['title']);?></td><td><?php echo $id?esc_html($id):'—';?></td><td><?php echo $valid?'<span style="color:#008a20">Active</span>':'<span style="color:#b32d2e">Missing</span>';?></td><td><a href="<?php echo esc_url($url);?>" target="_blank" rel="noopener"><?php echo esc_html($url);?></a></td></tr><?php endforeach;?></tbody></table></div><?php }
function smarttoolz_video_theme_settings(){if(!current_user_can('manage_options'))return;$notice='';if(isset($_POST['stv_install_theme'],$_POST['stv_theme_nonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stv_theme_nonce'])),'stv_theme_action')){$result=smarttoolz_video_install_theme();$notice=is_wp_error($result)?'<div class="notice notice-error is-dismissible"><p>'.esc_html($result->get_error_message()).'</p></div>':'<div class="notice notice-success is-dismissible"><p>SmartToolz Video Theme installed successfully.</p></div>';}if(isset($_POST['stv_activate_theme'],$_POST['stv_theme_activate_nonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stv_theme_activate_nonce'])),'stv_activate_theme')){$result=smarttoolz_video_activate_theme();$notice=is_wp_error($result)?'<div class="notice notice-error is-dismissible"><p>'.esc_html($result->get_error_message()).'</p></div>':'<div class="notice notice-success is-dismissible"><p>SmartToolz Video Theme activated successfully.</p></div>';} $installed=smarttoolz_video_theme_installed();$active=smarttoolz_video_theme_is_active();
?><div class="wrap"><h1>Theme Setup</h1><p>Install and activate the SmartToolz video-sharing theme without changing any WordPress core file.</p><?php echo $notice;?><table class="widefat striped" style="max-width:1000px;margin-top:16px;"><tbody><tr><th style="width:220px;">Theme</th><td><?php echo esc_html(smarttoolz_video_theme_name());?></td></tr><tr><th>Installation</th><td><?php echo $installed?'<span style="color:#008a20;font-weight:600">Installed</span>':'<span style="color:#b32d2e;font-weight:600">Not installed</span>';?></td></tr><tr><th>Activation</th><td><?php echo $active?'<span style="color:#008a20;font-weight:600">Active</span>':'<span style="color:#b32d2e;font-weight:600">Not active</span>';?></td></tr></tbody></table><div style="display:flex;gap:10px;margin-top:16px;"><form method="post"><?php wp_nonce_field('stv_theme_action','stv_theme_nonce');?><input type="hidden" name="stv_install_theme" value="1"><?php submit_button($installed?'Reinstall Theme':'Install Theme','secondary','submit',false);?></form><form method="post"><?php wp_nonce_field('stv_activate_theme','stv_theme_activate_nonce');?><input type="hidden" name="stv_activate_theme" value="1"><?php submit_button($active?'Theme Already Active':'Activate Theme','primary','submit',false);?></form></div></div><?php }
register_activation_hook(__FILE__,'smarttoolz_video_activate_plugin');register_deactivation_hook(__FILE__,'smarttoolz_video_deactivate_plugin');
